### DISCUSSION TITLE
Problem error: I/O error while setting tls.certs:

### DISCUSSION THREAD

**Discussion by Zeldri** [dani-garcia/vaultwarden#1260] [General]
Hi,
First of all I know there is many posts about this problem, but I can't find why this is not working on my side.
My docker-compose.yml file:
```
version: '2'
services:
    bitwarden:
        container_name: rw-bitwarden
        volumes:
            - '/opt/docker/bitwarden/data/:/data/'
        ports:
            - '8990:80'
            - '8991:443'
        environment:
            ROCKET_TLS: "{certs='/data/ssl/cert1.pem',key='/data/ssl/privkey1.pem'}"
        image: 'bitwardenrs/server:latest'
```
Content of `/opt/docker/bitwarden/data/ssl`:
![image](https://user-images.githubusercontent.com/30011220/101368618-a4c50000-38a7-11eb-8061-d5114e7c7bbf.png)

Content inside the container in path `/data/ssl`:
![image](https://user-images.githubusercontent.com/30011220/101368962-100ed200-38a8-11eb-9fba-554cd2bfcfee.png)

Every time that I try to start the container, I get the same error, I have access to the files, I can cat them.
I tried with `fullchain1.pem` and `cert1.pem`
Those files aren't symlinks
