### DISCUSSION TITLE
MySQL version is not compatible with MySQL v8's default password hashing mechanism

### DISCUSSION THREAD

**Discussion by timwis** [dani-garcia/vaultwarden#1403] [Q&A]
### Subject of the issue
In January 2018, MySQL [announced](https://mysqlserverteam.com/mysql-8-0-4-new-default-authentication-plugin-caching_sha2_password/) they were changing the default authentication plugin for MySQL server from `mysql_native_password` to `caching_sha2_password` in MySQL v8.0.4. This required mysql clients to support the `caching_sha2_password` method in order to connect.

The `bitwardenrs/msyql-server` image does not appear to support this method, which results in an error when attempting to connect to a modern MySQL (v8.0.4+) database:

```
Can't connect to DB: BadConnection("Plugin caching_sha2_password could not be loaded: /usr//usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory
```

This can be worked around by using a user account that uses the `mysql_native_password` authentication method (as [described here](https://tableplus.com/blog/2018/07/failed-to-load-caching-sha2-password-authentication-plugin-solved.html)), but ideally we'd be able to take advantage of the latest (and most secure) authentication method.

I _assume_ this is a problem with [the runtime image's `libmariadbclient-dev`](https://github.com/dani-garcia/bitwarden_rs/blob/master/docker/amd64/mysql/Dockerfile#L86) supporting this authentication plugin, or perhaps how it's locating the plugin file, but I haven't been able to figure it out. [MariaDB's docs](https://mariadb.com/kb/en/authentication-plugin-sha-256/) suggest it should be supported (I assume it's the C library).

### Your environment

* Bitwarden_rs version: 1.13.1-325039c3

* Install method: Docker image
* Clients used: N/A
* Reverse proxy and version: Caddy, but error is shown at bitwardenrs docker image startup
* Version of mysql/postgresql: MySQL 8.0.17 (digital ocean managed cluster)
* Other relevant information: N/A

### Steps to reproduce

Docker-compose file

```yml
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server-mysql
    volumes:
      - ./bitwarden-data/:/data/
    environment:
      DATABASE_URL: mysql://$BITWARDEN_DB_USERNAME:$BITWARDEN_DB_PASSWORD@$BITWARDEN_DB_HOSTNAME:$BITWARDEN_DB_PORT/$BITWARDEN_DB_DATABASE
      ADMIN_TOKEN: $BITWARDEN_ADMIN_TOKEN
      ENABLE_DB_WAL: 'false'
      RUST_BACKTRACE: 1 # detailed crash logs
```

### Expected behaviour

Bitwarden should connect to the MySQL database

### Actual behaviour

Error thrown, as described in subject section above.

### Relevant logs

See subject section above.

[a comment by an automated account is not shown]
