### DISCUSSION TITLE
Why can't I find my database file?

### DISCUSSION THREAD

**Discussion by arieslee** [dani-garcia/vaultwarden#1409] [Q&A]
my docker-compose.yml
```
version: "3"

services:
  bitwarden:
    image: bitwardenrs/server
    container_name: bitwardenrs
    restart: always
    ports:
        - "127.0.0.1:8087:80" 
        - "127.0.0.1:3012:3012"
    volumes:
      - ./data:/home/bw-data
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false" 
      WEB_VAULT_ENABLED: "true"
```

However, the database file cannot be found in the `data` directory or `/home/ bw-data` directory

The two directories are empty
