### DISCUSSION TITLE
A possibility to use local ip instead domain

### DISCUSSION THREAD

**Discussion by Darkyere** [dani-garcia/vaultwarden#1491] [Q&A]
I have a Raspberry PI 4 on which i wont to have my BitWardenrs server.

And i just want to WireGuard into my network and get access to my BitWardenrs server though its IP address.

Following the guide on 
[Using Docker-Compose](https://github.com/dani-garcia/bitwarden_rs/wiki/Using-Docker-Compose)
I go to the bottom of the page and choose
[DNS-alias-mode](https://github.com/acmesh-official/acme.sh/wiki/DNS-alias-mode)

But i cant seem to figure out how to do this with certificates and just a local IP on my LAN.

This is my config

```
# docker-compose.yml
version: '3'

services:
 bitwarden:
  image: bitwardenrs/server:latest
  restart: always
  volumes:
      - ./bw-data:/data
      - ./ssl:/ssl
  ports:
    - 443:80
  environment:
   ROCKET_TLS: '{certs = "/ssl/fullchain.pem", key = "/ssl/key.pem"}'
   LOG_FILE: '/data/bitwarden.log'
   SIGNUPS_ALLOWED: 'true'
```

----

Any help would be appreciated

**Comment by fe-data** [comment]
https://github.com/dani-garcia/bitwarden_rs/wiki/Running-a-private-bitwarden_rs-instance-with-Let%27s-Encrypt-certs

**Reply by Darkyere** [reply]
thank you for responding.
Sry for my delay i haven't had time.
I will definitely look at it and give it a try.
Thank you for the right place to go to.

**Comment by Darkyere** [comment]
Okay i tried looking at this again.

I cant figure out how to make this work with the docker-compose from 

[Using Docker Compose](https://github.com/dani-garcia/bitwarden_rs/wiki/Using-Docker-Compose)

and the info from 

[Running a private bitwarden_rs instance with Let's Encrypt certs](https://github.com/dani-garcia/bitwarden_rs/wiki/Running-a-private-bitwarden_rs-instance-with-Let%27s-Encrypt-certs)

My files looks like this.

---

docker-compose.yaml

```
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
    volumes:
      - ./bw-data:/data

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      - DOMAIN=1234.duckdns.org
      - DUCKDNS_TOKEN=DuckDNSToken
#      - EMAIL=       # The email address to use for ACME registration.
      - LOG_FILE=/data/access.log
```

The Caddyfile

```
{$DOMAIN}:443 {
    tls {
        dns lego_deprecated duckdns
    }
    reverse_proxy localhost:8080
    reverse_proxy /notifications/hub localhost:3012
}
```

----

caddy.env

```
DOMAIN=1234.duckdns.org
DUCKDNS_TOKEN=DuckDNSToken
```

----

When looking at caddy docker logs it seems like caddy2 doesnt have the lego-deprecated module in it.

`run: adapting config using caddyfile: parsing caddyfile tokens for 'tls': /etc/caddy/Caddyfile:3 - Error during parsing: getting DNS provider module named 'lego_deprecated': module not registered: dns.providers.lego_deprecated`

----

I would really like to have it configured in a docker-compose file and running in docker.

Can u somehow tell me how i need to configure the files so i can make this work.

Ty for listening and best regards,
Darkyere

**Reply by jjlin** [reply]
The stock Caddy builds (including the one in the Docker image) don't include the DNS challenge modules. The simplest thing would be to [get a custom Caddy build](https://github.com/dani-garcia/bitwarden_rs/wiki/Running-a-private-bitwarden_rs-instance-with-Let%27s-Encrypt-certs#getting-a-custom-caddy-build) and bind-mount the custom build into the `caddy:2` container, e.g.
```yaml
    volumes:
      - ./caddy.dns:/usr/bin/caddy  # assuming your custom Caddy build is named `caddy.dns`
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
```

**Comment by Darkyere** [comment]
This got me a step further.
Now both bitwardenrs and caddy starts up.

But i am getting a ssl error in firefox 

```
Secure Connection Failed

An error occurred during a connection to 192.168.1.7. Peer reports it experienced an internal error.

Error code: SSL_ERROR_INTERNAL_ERROR_ALERT

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

Learn more…
```

----

It seems like bitwardenrs never receives the certificate.

Is this because there is missing a connection possibly the 

ROCKET_PORT=8080

Between the 2 containers.

Or that the container is running in its own ip and being forwarded to 192.168.1.7

----

On the first run caddy logs said it got a certificate for my 1234.duckdns.org
So it seems like it pulls down the ssl certificate.

So i think i need to configure either bitwardenrs, caddy or both to communicate the ssl certificate somehow.

----

Just for reference i will post my configs

**docker-compose.yaml**

```
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: unless-stopped
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
    volumes:
      - ./bw-data:/data

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./caddy:/usr/bin/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      - DOMAIN=1234.duckdns.org
      - DUCKDNS_TOKEN=<DuckDNSToken>
      - EMAIL=ThisISMyMail@gmail.com       # The email address to use for ACME registration.
      - LOG_FILE=/data/access.log
```

**Caddyfile**

```
{$DOMAIN}:443 {
    tls {
        dns lego_deprecated duckdns
    }
    reverse_proxy localhost:8080
    reverse_proxy /notifications/hub localhost:3012
}
```

----

Some docker logs

**Bitwarden**

```
/--------------------------------------------------------------------\
|                       Starting Bitwarden_RS                        |
|                           Version 1.20.0                           |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://bitwardenrs.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/bitwarden_rs/issues/new           |
\--------------------------------------------------------------------/

FO] No .env file found.

[2021-04-07 07:41:39.570][bitwarden_rs][INFO] JWT keys don't exist, checking if OpenSSL is available...

OpenSSL 1.1.1d  10 Sep 2019

[2021-04-07 07:41:39.607][bitwarden_rs][INFO] OpenSSL detected, creating keys...

Generating RSA private key, 2048 bit long modulus (2 primes)

.............................................+++++

..............................................................................................................................................................+++++

e is 65537 (0x010001)

writing RSA key

writing RSA key

[2021-04-07 07:41:39.979][bitwarden_rs][INFO] Keys created correctly.

Running migration 20180114171611
Running migration 20180217205753
Running migration 20180427155151
Running migration 20180508161616
Running migration 20180525232323
Running migration 20180601112529
Running migration 20180711181453
Running migration 20180827172114
Running migration 20180910111213
Running migration 20180919144557
Running migration 20181127152651
Running migration 20190526216651
Running migration 20191010083032
Running migration 20191117011009
Running migration 20200313205045
Running migration 20200409235005
Running migration 20200701214531
Running migration 20200802025025
Running migration 20201130224000
Running migration 20201209173101
Running migration 20210311190243
Running migration 20210315163412

[2021-04-07 07:41:40.337][bitwarden_rs::api::core::sends][INFO] Initiating send deletion

[2021-04-07 07:41:40.342][start][INFO] Rocket has launched from http://0.0.0.0:8080

[2021-04-07 07:41:40.343][parity_ws][INFO] Listening for new connections on 0.0.0.0:3012.
```

**Caddy**

```

{"level":"info","ts":1617781299.6489336,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}

{"level":"info","ts":1617781299.6576982,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}

{"level":"info","ts":1617781299.659747,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}

{"level":"info","ts":1617781299.6597846,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}

{"level":"info","ts":1617781299.6618054,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["1234.duckdns.org"]}

{"level":"info","ts":1617781299.6632001,"logger":"tls","msg":"cleaned up storage units"}

{"level":"info","ts":1617781299.6633372,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0005e8000"}

{"level":"info","ts":1617781299.66338,"msg":"autosaved config","file":"/config/caddy/autosave.json"}

{"level":"info","ts":1617781299.6633904,"msg":"serving initial configuration"}

{"level":"info","ts":1617781299.6642182,"logger":"tls.obtain","msg":"acquiring lock","identifier":"1234.duckdns.org"}

{"level":"info","ts":1617781299.6651473,"logger":"tls.obtain","msg":"lock acquired","identifier":"1234.duckdns.org"}

{"level":"info","ts":1617781300.8958776,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["1234.duckdns.org"]}

{"level":"info","ts":1617781300.8959658,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["1234.duckdns.org"]}

{"level":"info","ts":1617781301.3291357,"logger":"tls.issuance.acme.acme_client","msg":"trying to solve challenge","identifier":"1234.duckdns.org","challenge_type":"dns-01","ca":"https://acme-v02.api.letsencrypt.org/directory"}

{"level":"info","ts":1617781308.0992904,"logger":"tls.issuance.acme.acme_client","msg":"validations succeeded; finalizing order","order":"https://acme-v02.api.letsencrypt.org/acme/order/118321044/8915669227"}

{"level":"info","ts":1617781309.0703478,"logger":"tls.issuance.acme.acme_client","msg":"successfully downloaded available certificate chains","count":2,"first_url":"https://acme-v02.api.letsencrypt.org/acme/cert/04ae9baca310b3ec72ef73834369c2d8c8ce"}

{"level":"info","ts":1617781309.0730858,"logger":"tls.obtain","msg":"certificate obtained successfully","identifier":"1234.duckdns.org"}

{"level":"info","ts":1617781309.0735931,"logger":"tls.obtain","msg":"releasing lock","identifier":"1234.duckdns.org"}

{"level":"error","ts":1617781568.1769109,"logger":"http.log.error","msg":"dial tcp 127.0.0.1:8080: connect: connection refused","request":{"remote_addr":"192.168.1.97:54385","proto":"HTTP/2.0","method":"GET","host":"1234.duckdns.org","uri":"/","headers":{"Upgrade-Insecure-Requests":["1"],"Te":["trailers"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"],"Accept-Language":["en-US,en;q=0.5"],"Accept-Encoding":["gzip, deflate, br"],"Cookie":["XSRF_TOKEN=1222440606"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"thisisrandom.duckdns.org"}},"duration":0.001394964,"status":502,"err_id":"xwd778qxi","err_trace":"reverseproxy.statusError (reverseproxy.go:783)"}
```
----

Can u figure out what is needed to make this work ?

Ty for spending your time on this,
much appreciated
