### DISCUSSION TITLE
ICON_BLACKLIST_REGEX with domain not working

### DISCUSSION THREAD

**Discussion by darootler** [dani-garcia/vaultwarden#1496] [Q&A] [answered]
I am running bitwarden_rs with docker compose as follows:

```
version: '3'

services:
  bitwardenrs:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
    environment:
      ICON_BLACKLIST_REGEX: '.*mygreatdomain\.biz'
      DOMAIN: https://secret.domain:12345
      ROCKET_TLS: '{certs="/data/pub.pem",key="/data/priv.pem"}'
      SIGNUPS_ALLOWED: 'false'
      SIGNUPS_DOMAINS_WHITELIST: 'secret.domain'
      SMTP_HOST: 'smtp.secret.domain'
      SMTP_FROM: 'bitwarden_rs@secret.domain'
      SMTP_PORT: 587
      SMTP_SSL: 'true'
    image: bitwardenrs/server:latest
    restart: always
    ports:
      - 12345:80
    volumes:
      - /my/persistent/share/data:/data
```

I want to exclude some domains from the icon service, in this example i want to exclude "mygreatdomain.biz" from the icon service. As you can see this is not working:

`[2021-03-16 15:05:31.122][request][INFO] GET /icons/mygreatdomain.biz/icon.png`

Am i doing something wrong?

Regards
Richard
