### DISCUSSION TITLE
Cannot accept user to an organization using docker image

### DISCUSSION THREAD

**Discussion by ahaw** [dani-garcia/vaultwarden#1500] [Q&A]
When I try to approve the user I get the error message "An error has occurred.
An unexpected error has occurred.". 
I was able to approve a single user but nothing after it.

I tried to check logs but nothing I don't see there anything relevant.

My docker compose file:
```
 bitwarden:
#  entrypoint: ["echo", "Service bitwarden disabled"]
  restart: always
  container_name: bitwarden
  image: bitwardenrs/server:alpine
  hostname: bitwarden
  volumes:
   - ./bitwarden/:/data/
  environment:
   - WEBSOCKET_ENABLED=false
   - SIGNUPS_ALLOWED=false
   - ADMIN_TOKEN=<token>
   - DOMAIN=https://mydomain.com/bw
   - LOG_LEVEL=trace
   - EXTENDED_LOGGING=true

```
Im also using envoy proxy to forward https traffic (no wss proxying as I thought it's unneded)

```
static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 10000
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          access_log:
          - name: envoy.access_loggers.file
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
              path: /dev/stdout
          http_filters:
          - name: envoy.filters.http.router
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/bw/"
                route:
                  host_rewrite_literal: bitwarden
#                  prefix_rewrite: "/"
                  cluster: bitwarden
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
            tls_certificates:
              - certificate_chain:
                {
                  filename: "/certs/fullchain1.pem"
                }
                private_key:
                {
                  filename: "/certs/privkey1.pem"
                }
  clusters:
  - name: bitwarden
    connect_timeout: 30s
    type: LOGICAL_DNS
    dns_lookup_family: V4_ONLY
    load_assignment:
      cluster_name: bitwarden
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: bitwarden
                port_value: 80

```
