### DISCUSSION TITLE
Docker container showing as unhealthy

### DISCUSSION THREAD

**Discussion by FloatingMilkshake** [dani-garcia/vaultwarden#1505] [Q&A] [answered]
Hi! I just set up bitwarden_rs on Docker with [swag](https://docs.linuxserver.io/general/swag) (reverse proxy) and DuckDNS (dynamic DNS) and I'm really liking it. I've noticed though that the Docker container shows up as unhealthy when I run `docker container ls`...I saw an [issue](https://github.com/dani-garcia/bitwarden_rs/issues/795) about this but the underlying error was different from mine. The suggestion was to just disable the health-check but I'd rather figure out why I'm seeing `unhealthy`.

Here's some information that might help:

**Bitwarden RS version:** 1.19.0
**Install method:** Docker using `docker-compose`:
```
---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=[redacted].duckdns.org
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=[redacted]
    volumes:
      - /home/pihole/appdata/swag:/config
    ports:
      - 443:443
    restart: always
    
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
      - DOMAIN=https://<DOMAIN>/bitwarden
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=[redacted]
    volumes:
      - ./bw-data:/data
    ports:
      - 80:80
      - 3012:3012

  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/New_York
      - SUBDOMAINS=[redacted]
      - TOKEN=[redacted]
      - LOG_FILE=true #optional
    volumes:
      - /home/pihole/appdata/duckdns:/config #optional
    restart: always
```
**Reverse proxy and version:** [swag](https://docs.linuxserver.io/general/swag), not sure how to find the version

Reproduction steps are simple, just start the container and wait for the status to change from `starting` to `unhealthy`. Expected behavior is, of course, a healthy container. Actual behavior is, well...an unhealthy container.

The main log (`docker logs bitwarden`) doesn't show anything of interest.

Running `docker exec -ti bitwarden healthcheck.sh` returns this:
```
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "healthcheck.sh": executable file not found in $PATH: unknown
```
Running it with a forward-slash before `healthcheck.sh` (so `docker exec -ti bitwarden /healthcheck.sh`) returns this:
```
curl: (22) The requested URL returned error: 404 Not Found
```
Running `docker exec -ti bitwarden curl -v http://localhost:80/alive` returns this:
```
* Expire in 0 ms for 6 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 1 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
* Expire in 0 ms for 1 (transfer 0x559607b68ec0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 150000 ms for 3 (transfer 0x559607b68ec0)
* Expire in 200 ms for 4 (transfer 0x559607b68ec0)
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /alive HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Server: Rocket
< Feature-Policy: accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; sync-xhr 'self' https://haveibeenpwned.com https://twofactorauth.org; usb 'none'; vr 'none'
< Referrer-Policy: same-origin
< X-Frame-Options: SAMEORIGIN
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Content-Security-Policy: frame-ancestors 'self' chrome-extension://nngceckbapebfimnlniiiahkandclblb moz-extension://* ;
< Cache-Control: no-cache, no-store, max-age=0
< Access-Control-Allow-Origin:
< Content-Length: 29
< Date: Wed, 17 Mar 2021 16:21:40 GMT
<
* Connection #0 to host localhost left intact
```
