### DISCUSSION TITLE
Send item not sync automatic

### DISCUSSION THREAD

**Discussion by cloverzrg** [dani-garcia/vaultwarden#1562] [Q&A]
### Subject of the issue

The send item not sync(the password item work)
### Deployment environment

* bitwarden_rs version:1.20.0

* Install method:docker-compose

* Clients used: web vault, chrome extensions
```
version: '3.3'

services:
   bitwardenrs:
     image: bitwardenrs/server:latest
     container_name: bitwardenrs
     volumes:
       - ./data:/data
     environment:
       TZ: Asia/Shanghai
     restart: always
     networks:
       - traefik-net
     env_file:
       - ./conf.env
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.bitwarden.rule=Host(`bitwarden.xxx.com`)"
       - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
       - "traefik.http.routers.bitwarden-ws.rule=Host(`bitwarden.xxx.com`) && Path(`/notifications/hub`)"
       - "traefik.http.services.bitwarden-ws.loadbalancer.server.port=3012"
       - "traefik.http.routers.bitwarden.service=bitwarden"
       - "traefik.http.routers.bitwarden-ws.service=bitwarden-ws"


networks:
  traefik-net:
    external:
      name: traefik-net
```

### Steps to reproduce

Add a send item in web value, but not found in the chrome extension
and i edit a Login item in web value, the change synced in the chrome extensions. so my sync config should work.
I had to sync the send item by click the "sync" button in chrome extension
