### DISCUSSION TITLE
Docker environment variables have no effect on the running instance

### DISCUSSION THREAD

**Discussion by rspindler** [dani-garcia/vaultwarden#1594] [Q&A]
### Subject of the issue
The environment variable settings in the docker-compose file don't seem to have any effect on the running instance of the bitwardenrs server.

I did configure mine as follows:

```
version: '3'

services:
  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: always
    ports:
      - 8082:80
      - 3021:3021
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUP_ALLOWD=false
      - ADMIN_TOKEN=removed
    volumes:
      - ./data:/data
```

(For security reasons, I removed the admin token)

The port setup is necessary like that because I have a few more services running on the same machine. I do use a reverse proxy, which is located on a whole different machine and handles all of my internal servers. The proxy is using the configuration from here: https://github.com/dani-garcia/bitwarden_rs/wiki/Proxy-examples

Neither `SIGNUP_ALLOWED` nor `ADMIN_TOKEN` really do change anything. The message I get when I try to open the admin page in the browser is _The admin panel is disabled, please configure the 'ADMIN_TOKEN' variable to enable it_.

And I can sign up for new accounts on the web vault, which is basically what I want to disable, since I plan to make my the server available from outside of my home network.

### Deployment environment

* bitwarden_rs version: 1.20.0 with bitwardenrs/server:latest

* Install method: Docker image, using docker-compose

* Clients used: web vault

* Reverse proxy and version: nginx, most recent nginx:alpine image available. I use a acentral reverse proxy on a RPI to handle all my in-house network stuff.

* Other relevant details:

### Steps to reproduce
See above - configure a file and start it. The try to open the admin page

### Expected behaviour
Admin page is available

### Actual behaviour
Admin page is not available
