### DISCUSSION TITLE
Using external mysql db

### DISCUSSION THREAD

**Discussion by yodaphone** [dani-garcia/vaultwarden#1612] [Q&A]
I have a mysql server running on a VM. How do i make bitwarden_rs use that instead of the built in sqlite3? this is my docker compose. can someone please help?

```
version: "3"
# bitwarden

services:
 bitwarden:
  image: bitwardenrs/server:latest
  container_name: bitwarden
  restart: always
  volumes:
      - /opt/bitwarden/data:/data/
  ports:
    - 8088:80
    - 3012:3012
  environment:
    LOG_FILE: '/opt/bitwarden/bitwarden.log'
    LOG_LEVEL: 'debug'
    EXTENDED_LOGGING: 'true'
    WEB_VAULT_ENABLED: 'true'
    WEBSOCKET_ENABLED: 'true'
    WEBSOCKET_PORT: '3012'
    ADMIN_TOKEN: '12345'
    SIGNUPS_ALLOWED: 'true'
    DATABASE_URL: 'mysql://bitwarden_rs:rZN4Cy8nr@192.168.11.67:3306/bitwarden_rs'

```
