### DISCUSSION TITLE
Can't access Vaultwarden

### DISCUSSION THREAD

**Discussion by dave-ctrl** [dani-garcia/vaultwarden#1698] [Q&A]
Hi everyone,

I recently got me a Raspberry PI and as my first project, I wanted to host Vaultwarden on it.
Since I have DS-Lite-Tunnel and therefore only a private IPv4, I decided to host it only internal.

I set up Docker-Compose, Caddy and Vaultwarden. Both, Caddy and Vaultwarten are starting, but for some reason I can't get access to Vaultwarden.

I set up DuckDNS (basically just registered there and created a Domain) and got me the custom build for my Raspberry for DNS-Challenge. 
 
For some reason I can't get access to Vaultwarden. I tried it with the DuckDNS Domain-Name and http(s)://INTERNAL-IP
When I try to access it with the Domain Name, I get the following error in Chrome: DNS_PROBE_FINISHED_NXDOMAIN

When I access it with the internal IP, this comes up: ERR_SSL_PROTOCOL_ERROR

I really don't know what I'm missing here.

# My Caddyfile looks like this:
    
```
{$DOMAIN}:443 {
  tls {
    dns duckdns {$DUCKDNS_TOKEN}
  }
  reverse_proxy /notifications/hub vaultwarden:3012
  reverse_proxy vaultwarden:8080
}    
```
# My docker-compose.yml looks like this:
```
version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
    volumes:
      - ./vw-data:/data

  caddy:
    image: caddy:2
    container_name: caddy3
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy:/usr/bin/caddy
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      - DOMAIN=<DuckDNS-Domain>
      - EMAIL=<MyMail>
      - DUCKDNS_TOKEN=<DuckDNS-Token>
      - LOG_FILE=/data/access.log
```

# The Docker Log for Caddy looks like this:
```
{"level":"info","ts":1621066722.5159807,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
{"level":"warn","ts":1621066722.5222723,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
{"level":"info","ts":1621066722.5276735,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"info","ts":1621066722.528502,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x3a4e230"}
{"level":"info","ts":1621066722.5289357,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
{"level":"info","ts":1621066722.5292563,"logger":"http","msg":"enabling automatic HTTP->HTTPS redirects","server_name":"srv0"}
{"level":"info","ts":1621066722.5305314,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
{"level":"info","ts":1621066722.53113,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["DuckDNS-Domain"]}
{"level":"info","ts":1621066722.532402,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1621066722.5356154,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
{"level":"info","ts":1621066722.5358534,"msg":"serving initial configuration"}
```

Since I'm very new to all of this, any help is very much appreciated.
Have a great day.
