### DISCUSSION TITLE
Cannot install when using docker compose.

### DISCUSSION THREAD

**Discussion by magic3584** [dani-garcia/vaultwarden#1762] [Q&A]
I followed this https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose section **Caddy with HTTP challenge**
The **docker-compose.yml**
```` yml
version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
    volumes:
      - ./vw-data:/data

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80  # Needed for the ACME HTTP-01 challenge.
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      - DOMAIN=http://bw.domain.com  # Your domain, prefixed with http or https.
      - EMAIL=myemail.com       # The email address to use for ACME registration.
      - LOG_FILE=/data/access.log
 ````

But I cannot open **http://bw.domain.com**

```` shell
root@localhost:~/bitwarden# docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED              STATUS                         PORTS                                            NAMES
0caff6aa8431        vaultwarden/server:latest         "/usr/bin/dumb-init �"   About a minute ago   Up About a minute (healthy)    80/tcp, 3012/tcp                                 vaultwarden
d318742e39e3        caddy:2                           "caddy run --config �"   About a minute ago   Restarting (1) 3 seconds ago                                                    caddy
````
