### DISCUSSION TITLE
Clients not syncing (Android & Firefox)

### DISCUSSION THREAD

**Discussion by InfInt** [dani-garcia/vaultwarden#2126] [Q&A]
Hello everyone,
I am running a vaultwarden docker container for a while now and had everything working just fine. Just after I tried to manually update a password on my phone I realized that the syncing had stop working. I checked the last sync date on phone and desktop and the dates are way in the past. I suspect this is an issue, but I can't tell what is actually going wrong at this moment. So I'll post my information here and hope that you can help me to solve this or figure out what the real issue is:

Android last sucessfull sync was 11/20/2021
and firefox 03/2021

When I initiate  a manual sync I get a spinning wheel and  it errors out with: `syncing failed`
These are the last log lines of the vaultwarden service:
<details><summary>Show service log</summary>

```
[2021-12-03 09:31:50.867][request][INFO] GET /admin,
[2021-12-03 09:31:50.887][response][INFO] GET /admin (admin_page) => 200 OK,
[2021-12-03 09:32:08.074][request][INFO] GET /admin/diagnostics,
[2021-12-03 09:32:08.885][response][INFO] GET /admin/diagnostics (diagnostics) => 200 OK,
[2021-12-03 09:33:42.330][request][INFO] GET /admin/diagnostics/config,
[2021-12-03 09:33:42.331][response][INFO] GET /admin/diagnostics/config (get_diagnostics_config) => 200 OK,
[2021-12-03 09:43:16.472][request][INFO] GET /icons/github.com/icon.png,
[2021-12-03 09:43:16.472][response][INFO] GET /icons/<domain>/icon.png (icon) => 200 OK
```

</details>
Nothing much for an error

### My environment (Generated via diagnostics page)
* Vaultwarden version: v1.23.0
* Web-vault version: v2.23.0c
* Running within Docker: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.35.4
* Clients used: Firefox, Android
* Reverse proxy and version: Traefik v2.5.4
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** DOMAIN, SIGNUPS_ALLOWED, ADMIN_TOKEN, SMTP_HOST, SMTP_SSL, SMTP_PORT, SMTP_FROM, SMTP_USERNAME, SMTP_PASSWORD

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_ip_header_enabled": true,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_max_conns": 10,
  "database_url": "****/**.*******",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://****.****.***",
  "domain_origin": "*****://****.****.***",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 5 * * * *",
  "emergency_request_timeout_schedule": "0 5 * * * *",
  "enable_db_wal": true,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "invitation_org_name": "Bitwarden Vault",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "org_attachment_limit": null,
  "org_creation_users": "",
  "password_iterations": 100000,
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": true,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_explicit_tls": false,
  "smtp_from": "****@****.****.***",
  "smtp_from_name": "Bitwarden Vault",
  "smtp_host": "****.****.***",
  "smtp_password": "***",
  "smtp_port": 587,
  "smtp_ssl": true,
  "smtp_timeout": 15,
  "smtp_username": "****@****.****.***",
  "templates_folder": "data/templates",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": true,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

And my docker compose file looks as follows:
<details><summary>Show docker compose file</summary>

```yaml
version: '3.8'

services:
  bitwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - "3012:3012"
    volumes:
      - /opt/bitwarden/bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'false'   # set to false to disable signups
      ADMIN_TOKEN: 'xxxxxxxxxxxxxxxxxxxxxxxx'
      DOMAIN: 'https://pass.xxxx.dev'
      SMTP_HOST: 'mail.xxxx.dev'
      SMTP_FROM: 'info@pass.xxxxx.dev'
      SMTP_PORT: 587
      SMTP_SSL: 'true'
      SMTP_USERNAME: 'info@pass.xxxxx.dev'
      SMTP_PASSWORD: 'xxxxxx'
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.bitwarden.entrypoints=web"
        - "traefik.http.routers.bitwarden.rule=Host(`pass.xxxxxx.dev`)"
        - "traefik.http.routers.bitwarden.service=bitwarden"
        - "traefik.http.middlewares.bitwarden-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.bitwarden.middlewares=bitwarden-https-redirect"
        - "traefik.http.routers.bitwarden-secure.entrypoints=websecure"
        - "traefik.http.routers.bitwarden-secure.rule=Host(`pass.xxxxx.dev`)"
        - "traefik.http.routers.bitwarden-secure.tls=true"
        - "traefik.http.routers.bitwarden-secure.tls.certresolver=letsencrypt"
        - "traefik.http.routers.bitwarden-secure.service=bitwarden"
        - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.bitwarden-secure.middlewares=secHeaders@file"
        - "traefik.http.routers.bitwarden-websocket.rule=Host(`pass.xxxxx.dev`) && Path(`/notifications/hub`)"
        - "traefik.http.routers.bitwarden-websocket.service=bitwarden-websocket"
        - "traefik.http.services.bitwarden-websocket.loadbalancer.server.port=3012"

    networks:
      - proxy

networks:
  proxy:
    external: true
 ```
</details>

I have redacted just the domain part.
My secHeaders file is define as:

<details><summary>Show secHeaders file</summary>

```yaml
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
http:
  middlewares:
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        #HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
```
</details>

Please let me know if there is anything I can provide to help. 
Thank you.
