### DISCUSSION TITLE
Local only Vaultwarden not accessible

### DISCUSSION THREAD

**Discussion by Gafielt** [dani-garcia/vaultwarden#2190] [Q&A] [answered]
I everyone,
I want to use vaultwarden on a pi 4 (like many of you). Currently I fail hard to get to the main page at all. I followed to instructions in the [tutorial](https://github.com/dani-garcia/vaultwarden/wiki/Running-a-private-vaultwarden-instance-with-Let's-Encrypt-certs) and used the [docker compose method](https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose#caddy-with-dns-challenge). Currently all I get is a running vaultwarden and caddy container. The vaultwarden is accessable via the normal ports and functions properly. I can just not access it via the domain i have created with duck dns (ERR_CONNECTION_REFUSED). On my path of fixing I stumbled up on this discussion [here](https://github.com/dani-garcia/vaultwarden/discussions/1491), which did not help me (sadly).

I currently think it has something to do with caddy, because I can't see any logs on startup and it is restarting constantly (which could be quite normal). I use portainer as an easy way to handle my docker containers and view logs etc, but installed the stack like it is mentioned in the tutorial. I know that the viewing of the logs works, since i fixed a bug earlier through them, which where similar to the ones in the other discussion.

Docker compose:
```
version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true  # Enable WebSocket notifications.
    volumes:
      - ./vw-data:/data

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy:/usr/bin/caddy  # Your custom build of Caddy.
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      - DOMAIN=https://<mySubDomain>.duckdns.org  # Your domain.
      - EMAIL=<myEmail>                 # The email address to use for ACME registration.
      - DUCKDNS_TOKEN=<myToken>                  # Your Duck DNS token.
      - LOG_FILE=/data/access.log
```

CaddyFile
```
{$DOMAIN}:443 {
  log {
    level INFO
    output file {$LOG_FILE} {
      roll_size 10MB
      roll_keep 10
    }
  }

  # Use the ACME DNS-01 challenge to get a cert for the configured domain.
  tls {
        dns duckdns {$DUCKDNS_TOKEN}
  }

  # This setting may have compatibility issues with some browsers
  # (e.g., attachment downloading on Firefox). Try disabling this
  # if you encounter issues.
  encode gzip

  # Notifications redirected to the WebSocket server
  reverse_proxy /notifications/hub vaultwarden:3012

  # Proxy everything else to Rocket
  reverse_proxy vaultwarden:80
}
```

I am thankful to every recommondation to solve this since I am searching for many hours now!
