### DISCUSSION TITLE
Dark mode by default?

### DISCUSSION THREAD

**Discussion by kangaroo72** [dani-garcia/vaultwarden#2220] [Ideas]
Hi,
I'm running Vaultwarden 2.25.0.
Is it possible, to get the dark mode by default?

Thanks,

Tom

**Comment by BlackDex** [comment]
If I'm correct this is a per user setting stored within local storage of the browser. I do not think that this is possible. But i haven't checked thoroughly.

**Comment by kangaroo72** [comment]
yes, you're right. It's a "per user setting". A "force" to dark would be nice :-)

**Comment by Masgalor** [comment]
Before I can help you with that problem we need to clarify something.
It is highly unlikely you are running vaultwarden 2.25.0, because that version dose not exist, the current stable version is 1.23.1.
What you are referring to is the webvault, a web-client developed by bitwarden, like every other client.

Now that we know that this change has to be made in the client, locate the folder containing the webvault.
There will be one file called ```index.html``` and one ```sso-connector.html```.
Both contain the line ```class="theme_light"```, change it to ```class="theme_dark"``` and clear your browser cache.
Now the client will start in dark mode by default.

**Comment by kangaroo72** [comment]
Hi @Masgalor. Indeed it's 1.23.1 - I messed that up...
Thanks for your help!!

**Comment by BlackDex** [comment]
You can do this automatically when using containers by creating a startup script.
See: https://github.com/dani-garcia/vaultwarden/wiki/Starting-a-Container#customizing-container-startup

Create a script in either `/etc/vaultwarden.d` or as the wiki shows `init.sh` and use the code example below.
That will change the `index.html` and `sso-connector.html` to use have the `theme_dark` there everytime the container starts.

```bash
#!/usr/bin/env sh
sed -i 's#class="theme_light"#class="theme_dark"#' /web-vault/index.html
sed -i 's#class="theme_light"#class="theme_dark"#' /web-vault/sso-connector.html
```

**Reply by S1rM0rk3** [reply]
# Is there an update on this yet?

Does not work for me. The script runs and changes the two CSS classes, but no effect is seen. 
I also checked the changes in the files manually.

Has this ever worked for anyone, can anyone confirm that the script works?

###  My script 

- _Does not work_

I did not change anything except `#!/usr/bin/env sh` to `#!/bin/sh` and added `echo "setting up dark mode"`.

```sh
#!/bin/sh
echo "setting up dark mode"
sed -i 's#class="theme_light"#class="theme_dark"#' /web-vault/index.html
sed -i 's#class="theme_light"#class="theme_dark"#' /web-vault/sso-connector.html
```

Using version 1.27.0 (2022.12.0)

**Reply by Masgalor** [reply]
Hey @S1rM0rk3 ,
bitwarden has changed a lot about how themes are applied so it is not easy to keep this workaroung up to date.

The codeblock you posted was working until version 2022.10.0 from there it was neccessary to add 
```
sed -i 's#this.theme=S.Light#this.theme=S.Dark#' /web-vault/app/main.*.js
```

But this is no longer working since version 2022.12.0, I haven't had time to figure out what needs to be changed now.

**Reply by BlackDex** [reply]
Looks like there is some more JavaScript which is active.

**Reply by Masgalor** [reply]
In case someone is waiting for a solution, this is working with 2023.3.0b.
```
#!/usr/bin/env sh
sed -i 's#class="theme_light"#class="theme_dark"#' /web-vault/index.html
sed -i 's#class="theme_light"#class="theme_dark"#' /web-vault/sso-connector.html
sed -i 's#this.theme=Ct.f.Light#this.theme=Ct.f.Dark#' /web-vault/app/main.*.js
```

**Reply by BlackDex** [reply]
It would be better if we could fix the web-vault (Upstream Bitwarden) to use the user preferred mode of course.
Not sure if that has been requested already.

**Reply by Fmstrat** [reply]
As of today, you don't need to change much, just the default in the `global` local storage variable. Here's a script I use in the docker container to set a primary theme color and change to the "system" theme (auto-selects light/dark based on system theme):

**init.sh:**
```
#!/bin/sh

rm /web-vault/app/*.css.map

THEME_RGB=$(printf "%d %d %d\n" 0x${THEME_COLOR:0:2} 0x${THEME_COLOR:2:2} 0x${THEME_COLOR:4:2})
sed -i "s|6a99f0|${THEME_COLOR}|g" /web-vault/app/*.css
sed -i "s|175ddc|${THEME_COLOR}|g" /web-vault/app/*.css
sed -i "s|106 153 240|${THEME_RGB}|g" /web-vault/app/*.css
sed -i "s|23 93 220|${THEME_RGB}|g" /web-vault/app/*.css

THEME_BG_RGB=$(printf "%d %d %d\n" 0x${THEME_BG_COLOR:0:2} 0x${THEME_BG_COLOR:2:2} 0x${THEME_BG_COLOR:4:2})
sed -i "s|1f242e|${THEME_BG_COLOR}|g" /web-vault/app/*.css
sed -i "s|31 36 46|${THEME_BG_RGB}|g" /web-vault/app/*.css

sed -i "s|this.theme=Ct.f.Light|this.theme=Ct.f.System|g" /web-vault/app/main.*.js

/start.sh
```

**docker-compose.yml:**
```
  vaultwarden-web:
    container_name: vaultwarden-web
    image: vaultwarden/server:alpine
    environment:
      THEME_COLOR: "313131"
      THEME_BG_COLOR: "171717"
      ...
    depends_on:
      - vaultwarden-db
    volumes:
      - ./init.sh:/init.sh
      ...
    command: /init.sh

**Comment by kangaroo72** [comment]
@Fmstrat you're running this script in your docker-container? Doesn't work for me...

´´´start.sh: 4: Bad substitution´´´

**Reply by Fmstrat** [reply]
I've updated the comment: https://github.com/dani-garcia/vaultwarden/discussions/2220#discussioncomment-6000886

You're likely missing the ENV variables. I also added in a BG color.

**Reply by info-git** [reply]
For me it wasn't the missing env variables, it was the string to rgb conversion that was failing. I'm wondering if it's because it's not bash running the script or something. I did the conversion in bash where it worked, and used the converted strings directly in the script. 
```bash
THEME_COLOR="FFA428"
THEME_BG_COLOR="009639"
THEME_RGB="255 164 40"
THEME_BG_RGB="0 150 57"
```

**Comment by c4bler** [comment]
It seems like to get this working on current version (at least on the login page) this worked for me:
```
#!/bin/sh
sed -i 's#class="theme_light"#class="theme_dark"#' /web-vault/index.html
sed -i 's#class="theme_light"#class="theme_dark"#' /web-vault/sso-connector.html
sed -i "s|this.theme=Xe.f8.Light|this.theme=Xe.f8.System|g" /web-vault/app/main.*.js
```

Inside the docker-compose.yml:
```
volumes:
            - "/opt/vaultwarden/vw-data/:/data/"
            - "/opt/vaultwarden/scripts/init.sh:/etc/vaultwarden.sh"
 ```

In case this changes I found the correct string via a grep from inside the docker container:
```
docker exec -it vaultwarden /bin/bash
grep -r -oE '.{0,20}this.theme=.{0,20}' /web-vault/app
```

**Comment by ghost** [comment]
Does this still work? It would be great to have just only dark mode everywhere because my eyes are strained very easily using dark mode and since the browsers i tend to use across devices don't always keep the settings stored locally it would be great to have something server side that i will know regardless of what device i open it on it will be in dark mode. Thanks.

**Comment by necaran** [comment]
The script for 1.33.0:
```sh
#!/bin/sh
# https://github.com/bitwarden/clients/blob/web-v2025.1.1/apps/web/src/index.html#L2
sed -i 's/theme_light/theme_dark/g' /web-vault/*.html
# https://github.com/bitwarden/clients/blob/web-v2025.1.1/apps/web/src/app/core/core.module.ts#L226-L227
sed -i 's/.Light),deps:/.Dark),deps:/g' /web-vault/app/main.*.js
```

**Reply by ghostersk** [reply]
This seem to work. But for some reason when I opened the main page in incognito window it still showed as light, I went to check the files if they had updated the code, then I refreshed the page again and it was dark.
Thank you all. I hate light mode.

I made the code as per the Vaultwarden docu:
```
#!/bin/bash
# /etc/vaultwarden.sh
# https://github.com/dani-garcia/vaultwarden/wiki/Starting-a-Container#customizing-container-startup
echo "Starting Up"
if [ ! -e /.init ]; then
  touch /.init
  # run your init steps...
  # https://github.com/bitwarden/clients/blob/web-v2025.1.1/apps/web/src/index.html#L2
  sed -i 's/theme_light/theme_dark/g' /web-vault/*.html
  # https://github.com/bitwarden/clients/blob/web-v2025.1.1/apps/web/src/app/core/core.module.ts#L226-L227
  sed -i 's/.Light),deps:/.Dark),deps:/g' /web-vault/app/main.*.js
fi
```
docker compose:
```
volumes:
      - /opt/settings/vaultwarden:/data
      - /opt/settings/vaultwarden/vaultwarden.sh:/etc/vaultwarden.sh
 ```

**Comment by Dubz** [comment]
To add to this, why not just save the user's preference on the server side and load it upon login? That way everyone gets to keep their preferred environment as they wish. I'm all for dark mode by default, but I can understand and respect some sick people who want to use light mode 😊

**Reply by BlackDex** [reply]
This setting is not saved or loaded server side.
It's fully client-side local storage only.

**Reply by Dubz** [reply]
So, I'll reiterate then:
> Why not just save the user's preference on the server side and load it upon login?

If you want the shortened version:
> Why not?

**Comment by Dubz** [comment]
The alternative approach to keep both sides at peace: set the default to match the system as everything else should be these days.

**Reply by stefan0xC** [reply]
That should be possible. I've created a PR for the upcoming web-vault version: https://github.com/vaultwarden/vw_web_builds/pull/17

**Reply by necaran** [reply]
@stefan0xC
But it is still light theme when the page is loading, and thus causes "white flash" in dark mode.
The HTML files are still in light mode by default and unfortunately `theme_system` is not a valid class name.
```html
<html class="theme_light">
```
On the other hand, making it `theme_dark` by default can also affect UX for light theme users.

A possible workaround is to add `color-scheme` to HTML files and a `prefers-color-scheme` rule to [tailwind.css](https://github.com/vaultwarden/vw_web_builds/blob/v2025.5.1/apps/web/src/scss/tailwind.css).
The `:not([lang])` pseudo-class ensures that the rule is only applied during loading, and thus does not break theme selection in Preferences.
Because the `lang` attribute is added after the page is loaded and the scripts are properly executed.
```html
<style>html{color-scheme:light dark}</style>
```
```css
@media (prefers-color-scheme: dark) {
  html:not([lang]) {
    img.new-logo-themed {
      content: url("../images/logo-white.svg");
    }
    --color-transparent-hover: rgb(255 255 255 / 0.02);
    --color-shadow: 0 0 0;

    --color-background: 32 39 51;
    --color-background-alt: 18 26 39;
    --color-background-alt2: 47 52 61;
    --color-background-alt3: 48 57 70;
    --color-background-alt4: 18 26 39;

    --color-primary-100: 26 39 78;
    --color-primary-300: 26 65 172;
    --color-primary-600: 101 171 255;
    --color-primary-700: 170 195 239;

    --color-secondary-100: 48 57 70;
    --color-secondary-300: 82 91 106;
    --color-secondary-500: 121 128 142;
    --color-secondary-600: 143 152 166;
    --color-secondary-700: 158 167 181;

    --color-success-100: 11 111 21;
    --color-success-600: 107 241 120;
    --color-success-700: 191 236 195;

    --color-danger-100: 149 27 42;
    --color-danger-600: 255 78 99;
    --color-danger-700: 255 236 239;

    --color-warning-100: 172 88 0;
    --color-warning-600: 255 191 0;
    --color-warning-700: 255 248 228;

    --color-info-100: 26 65 172;
    --color-info-600: 121 161 233;
    --color-info-700: 219 229 246;

    --color-notification-100: 117 37 83;
    --color-notification-600: 255 143 208;

    --color-art-primary: 243 246 249;
    --color-art-accent: 44 221 233;

    --color-text-main: 243 246 249;
    --color-text-muted: 136 152 181;
    --color-text-contrast: 18 26 39;
    --color-text-alt2: 255 255 255;
    --color-text-code: 255 143 208;

    --color-marketing-logo: 255 255 255;

    --tw-ring-offset-color: #1f242e;
  }
}
```
