### DISCUSSION TITLE
Can't get Fail2Ban to work (new install)

### DISCUSSION THREAD

**Discussion by evrydayzawrkday** [dani-garcia/vaultwarden#2300] [Q&A] [answered]
Hey all,

I cannot seem to get fail2ban to work. Configuration is below:

- NGINX is hosted on a separate server, and it is passing the real IP through (confirmed, as I see fail2ban working)
- Vaultwarden is running on an Ubuntu 20.04 LTS server using Docker Compose as shown below:

```
version: '3'
services:
    bitwarden:
        container_name: bitwarden
        environment:
            - 'YUBICO_CLIENT_ID=ABC123'
            - 'YUBICO_SECRET_KEY=ABC123'
            - DOMAIN=https://password.nope.io
            - SIGNUPS_ALLOWED=true
            - LOG_FILE=/data/vaultwarden.log
            - LOG_LEVEL=warn
            - EXTENDED_LOGGING=true
        volumes:
            - '/docker/bitwarden:/data/'
        ports:
            - '8080:80'
        image: 'vaultwarden/server:latest'
```

- I have fail2ban configured as shown within the wiki originally, but made a small modification (changed the iptables.conf to DROP v. Reject, along with change the iptables chain to DOCKER-USERS).

**.../filter.d/vaultwarden.local**
```
[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*Username or password is incorrect\. Try again\. IP: <ADDR>\. Username:.*$
ignoreregex =
```

**.../jail.d/vaultwarden.local**
```
[vaultwarden]
enabled = true
port = 8080,80,443,8081
filter = vaultwarden
action = iptables-allports[name=vaultwarden-test, chain=DOCKER-USER]
logpath = /docker/bitwarden/vaultwarden.log
maxretry = 3
bantime = 14400
findtime = 14400
```

- I have confirmed that if I enter in the password wrong three times it does add the real IP to the iptables chain to drop the connectivity, but it is not actually doing so. I have tried switching out to utilize the iptables chains "DOCKER" and "FORWARD" with no changes in behavior.

![Capture](https://user-images.githubusercontent.com/19562039/153694934-f01156b6-550d-41b4-9f43-42cc34c5a78e.PNG)

Honestly, any help would be appreciated. I am stumped to what this could be, as it almost feels like iptables is ignoring the block request.

PS: This is the first time using iptables in years, so any help or references would be awesome.

**EDIT**

Edited the formatting. In case you want to see the NGINX config, that is also below:
![nginx](https://user-images.githubusercontent.com/19562039/153695054-0c472e55-91ec-49d7-83b6-4050a65d426b.PNG)
