### DISCUSSION TITLE
Organisational support doesn't work

### DISCUSSION THREAD

**Discussion by tapashdatta** [dani-garcia/vaultwarden#2443] [Q&A]
### Subject of the issue
Organisational support doesn't work

### Deployment environment
* vaultwarden version: latest

* Install method: docker image

* Clients used:  web vault
* 
* Reverse proxy and version: nginx proxy manager

* MySQL/MariaDB or PostgreSQL version: sqlite

### Steps to reproduce

my yml version is attached. 
- Create a new organisation for the admin user
-  Invite a new user in the organisation with access to container within organisation.
-  User has full access to database but no access to the organisation invited.
-  Invitation email was clicked to join

```
version: '3'

services:
  vaultwarden:
    restart: always
    container_name: vaultwarden
    image: vaultwarden/server:latest
    volumes:
      - ./vw-data/:/data/
    ports:
      - 8062:80
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_FROM=cm@mydomain.org
      - SMTP_FROM_NAME=Password Vault
      - SMTP_SECURITY=starttls
      - SMTP_PORT=587
      - SMTP_USERNAME=cm@mydomain.org
      - SMTP_PASSWORD=xdfdfsdfmtfyfnb
      - SMTP_TIMEOUT=30
      - SMTP_AUTH_MECHANISM="Plain"
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=https://mydomain.org
      - INVITATION_ORG_NAME=Password
      - INVITATIONS_ALLOWED=true
      - ADMIN_TOKEN=another-really-long-Str0n6-passw0rol-you-will-need
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_DOMAINS_WHITELIST=mydomain.org
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=6
      - EMERGENCY_ACCESS_ALLOWED=true
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
```

### Expected behaviour
Expect to be add on the organisation vault automatically. And show the container that was permission.

### Actual behaviour

- Create a new organisation for an admin
-  Invite a new user in the organisation with access to container within organisation.
-  User has full access to database but no access to the organisation invited.
-  Invitation email was clicked to join
