### DISCUSSION TITLE
feature request

### DISCUSSION THREAD

**Discussion by RatedR9** [dani-garcia/vaultwarden#2454] [Ideas]
can [vaultwarden] support a script to choice custom bind port so that can easily use host network mode

**Comment by BlackDex** [comment]
Would setting an env variable work?
https://github.com/dani-garcia/vaultwarden/blob/3abf173d8954c982383285b29b39d15043e974cb/.env.template#L329

**Reply by RatedR9** [reply]
Thanks, I will try it in my spare time

**Reply by RatedR9** [reply]
> Would setting an env variable work?
> 
> https://github.com/dani-garcia/vaultwarden/blob/3abf173d8954c982383285b29b39d15043e974cb/.env.template#L329

i tried it ,such as touch .env file and  add env in docker-compose.yml file but both not work

**Comment by BlackDex** [comment]
Then I'm not sure what you want to accomplish.

Because, if i use a `docker-compose.yml` file like this:

```yml
---
version: '3.8'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    network_mode: host
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./data/:/data/
    environment:
      - TZ=Europe/Amsterdam
      - ROCKET_PORT=8888
      - LOG_FILE=/data/vaultwarden.log
      - WEBSOCKET_ENABLED=true
      - WEBSOCKET_PORT=3013
```

That works perfectly fine. It will run Vaultwarden web-interface on port 8888 and the web-socket on 3013 (default is 3012)
