### DISCUSSION TITLE
Can't connect to database after update docker image to 1.25.0

### DISCUSSION THREAD

**Discussion by Hobbabobba** [dani-garcia/vaultwarden#2511] [Q&A] [answered]
### Subject of the issue

Updated docker image to vaultwarden/server:1.25.0

After that container can´t start

### Deployment environment

* vaultwarden version: 1.25.0

* Install method: Docker-Compose

``` 
version: "2"
services:
  bitwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=xxx
      - SMTP_PASSWORD=xxxx
      - SMTP_USERNAME=mail@domain.com
      - SMTP_SSL=true
      - SMTP_PORT=587
      - SMTP_FROM=yyyy
      - SMTP_HOST=yyy
    volumes:
      - /volume1/docker/bitwarden_rs:/data
    ports:
      - 3012:3012
      - 6680:80
    restart: always
``` 

* Clients used: 

web vault
Desktop
Android
iOS

* Other relevant details:

### Troubleshooting data

``` 
)
Running migration 20220302210038
Executing migration script 20220302210038/up.sql
[2022-05-26 21:23:36.150][vaultwarden::util][WARN] Can't connect to database, retrying: DieselMig.
[CAUSE] QueryError(
    DatabaseError(
        __Unknown,
        "UNIQUE constraint failed: devices_new.uuid, devices_new.user_uuid",
    ),
)
```
