### DISCUSSION TITLE
Feature Request: key-connector for master-passwordless SSO

### DISCUSSION THREAD

**Discussion by Kab1r** [dani-garcia/vaultwarden#2583] [Ideas]
Bitwarden's upstream [key-connector](https://github.com/bitwarden/key-connector/) stores encryption keys used to encrypt vaults instead of master passwords. This allows for user accounts that authenticate using SSO to entirely omit master passwords.

**Comment by BlackDex** [comment]
For this feature we first need SSO support which is in progress as a PR.

Ill add it to the list.

**Comment by binaryben** [comment]
Please help me make sure I am right in my understanding of how this process works:

1. Currently the users master password encrypts the vaults
2. This is zero knowledge. Forgotten password = unrecoverable vault
3. `key-connector` means another key is used to encrypt the vault
4. The encryption key is stored in a data store - upstream provides anything from a JSON file to a RDBMS to a noSQL option

If my assumptions/understanding are correct, what protects the encryption key? Even though I use best practice to protect my vaultwarden instance, I still get a lot of peace of mind knowing that a bad actor with access would still have a hard time decrypting my passwords without the master key.

I know it's getting ahead of the horse when SSO support is still in development/testing... it would be nice to know the same peace of mind is possible with key-connector in place. 😊

**Reply by Kab1r** [reply]
The process is a little complicated, but as far as I know, the only thing you missed is that there are two kinds of keys involved. 'user-keys', the ones you mention, are visible to clients. So instead of storing these in plaintext, they are encrypted by another key that is not visible to clients and then stored.

It seems to me that `key-connector` is fundamentally less safe because if a bad actor gets access to the infrastructure and obtains the two keys, they can decrypt a vault.

Please correct me if I am wrong about any of this.


Upstream documentation:
https://bitwarden.com/help/about-key-connector/

**Reply by binaryben** [reply]
> It seems to me that `key-connector` is fundamentally less safe because if a bad actor gets access to the infrastructure and obtains the two keys, they can decrypt a vault.

Thanks, that is my understanding and concern as well. Hopefully others will weigh in to correct us or confirm our understanding!

**Reply by lollilol** [reply]
Maybe implementing the trusted devices feature with the feature that you actually don't need a master password. (imho requiring a master password defeats the purpose of sso in a company context)

But then you would need to implement the policy "only allow one organization" where then you would be able to set the policy to force new accounts into account recovery, so that their vault is decryptable with the organization key, which admins/owners of the can then do.

that would also be the official bitwarden way

**Comment by mbgonicus** [comment]
If I understand it correctly, then the [Key Connector is part of the Bitwarden License Agreement](https://github.com/bitwarden/key-connector/blob/master/LICENSE.txt) which only allows using it for non-prodction development:

>  2.1   Commercial Module License. 
Subject to Your compliance with this Agreement,
Bitwarden hereby grants to You a limited, non-exclusive, non-transferable,
royalty-free license to use the Commercial Modules for the sole purposes of
internal development and internal testing, and only in a non-production
environment.

So adding the feature to use Key Connector with vaultwarden would only be allowed if you pay for a Bitwarden license, in which case you can just use Bitwarden completely?  Or the functionality of Key Connector must be clones by a free open source project?

**Comment by bone6000** [comment]
is there any way to avoid master-password when using SSO if key connector is still not available?

**Reply by belerovon** [reply]
No is not. That is currently the design of bitwarden.

**Comment by madduck** [comment]
I understand the security decision by Bitwarden to keep the user's "master password" independent of SSO, and there are surely use-cases, where this is the right approach. Also, Bitwarden want to sell their licence, and key-connector is part of that.

In the company context (and where else would you really use SSO?), there is no such thing as per-user secrecy. If Bob signed up to a portal as part of his work, and I fire Bob, I need to be able to get his credentials without relying on the portal giving them to me because I took over Bob's email address. This is a simple example only, after all. Other examples include banks, government institutions, etc., some of which don't sport email password revovery options.

What's to stop us from computing the master password from an SSO claim? I cannot imagine this being very difficult either to implement incl. making it configurable, and I would fund such work. Or are there reasons this is impossible?

**Comment by acul021** [comment]
I took a stab at this: dani-garcia/vaultwarden#7419 adds the server side. The connector itself is a separate service I wrote from scratch against the GPL client code (https://github.com/acul021/key-connector), so the Bitwarden license problem mentioned above does not apply. Vaultwarden never stores any key material, the connector keeps the keys encrypted at rest on its own host.

**Reply by masterwishx** [reply]
Ohh that's why after added sso authentik, after sso login Im redirected to locked vault and need to enter master password?

**Reply by lollilol** [reply]
works for me! love it!

**Reply by acul021** [reply]
@masterwishx yeah that's expected. SSO just logs you in, your vault is still encrypted with your master password so you get the unlock screen after. the key connector is the thing that gets rid of that, without it you'll always have to enter the master password.

one thing to keep in mind: for admins/owners the master key isn't removed, and it's actually recommended (by bitwarden) to keep at least one owner who still has a master password. if you do want to drop it for an admin/owner, you can demote them (remove the owner/admin role) which drops the master password, then promote them back again.

**Reply by masterwishx** [reply]
> yeah that's expected

Yep, Thanks it took time to understand it :)  i Hope your pr will be integrated here.
Added SSO mostly for ability to let me reset users (family) master passwords ...

**Reply by madduck** [reply]
> I took a stab at this: #7419 adds the server side. The connector itself is a separate service I wrote from scratch against the GPL client code (https://github.com/acul021/key-connector), so the Bitwarden license problem mentioned above does not apply. Vaultwarden never stores any key material, the connector keeps the keys encrypted at rest on its own host.

Hey,

I would really like to deploy this, as we are just starting with Vaultwarden in our organisation, and do not want to burden anyone with the master password. We would love to be beta testers.

Is there a docker build somewhere that we can use? I just spent an hour trying to build it myself, but it just fails in various forms, and I also cannot get CI to work on Github: https://github.com/madduck/OIDCWarden/actions

**Reply by acul021** [reply]
Hi @madduck,

There are prebuilt images for both parts, so you don't need to build anything yourself:

- `ghcr.io/acul021/vaultwarden:testing-alpine` (Vaultwarden with the server side from #7419)
- `ghcr.io/acul021/key-connector:testing`

This is the compose file I run, with my hostnames and secrets replaced by placeholders. I use Traefik as reverse proxy, so the labels are Traefik-specific. If you run nginx or Caddy, drop them and proxy the two hostnames to ports 80 and 8081 yourself. SSO is required, the Key Connector only works for SSO users.

```yaml
services:
  vaultwarden:
    restart: always
    image: ghcr.io/acul021/vaultwarden:testing-alpine
    networks:
      - proxy
    environment:
      - "DOMAIN=https://vault.example.tld"
      - "INVITATION_ORG_NAME=Example Org"
      - "SIGNUPS_DOMAINS_WHITELIST=example.tld"
      - "SIGNUPS_VERIFY=true"
      - "ADMIN_TOKEN=<admin-token>"
      - "SMTP_HOST=smtp.example.tld"
      - "SMTP_FROM_NAME=Example Vault"
      - "SMTP_FROM=no-reply@example.tld"
      - "SMTP_PORT=587"
      - "SMTP_SSL=true"
      - "SMTP_USERNAME=no-reply@example.tld"
      - "SMTP_PASSWORD=<smtp-password>"
      # SSO (required for the Key Connector)
      - "SSO_ENABLED=true"
      - "SSO_AUTHORITY=https://idp.example.tld/application/o/vaultwarden/"
      - "SSO_CLIENT_ID=vaultwarden"
      - "SSO_CLIENT_SECRET=<oidc-client-secret>"
      # Key Connector
      - "KEY_CONNECTOR_ENABLED=true"
      - "KEY_CONNECTOR_URL=https://kc.example.tld"
      - "KEY_CONNECTOR_ORG_NAME=Example Org"
      - "ALLOWED_CONNECT_SRC=https://kc.example.tld"
    volumes:
      - "data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.example.tld`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      start_period: 30s
      start_interval: 5s
      interval: 30s
      timeout: 5s
      retries: 3

  key-connector:
    restart: always
    image: ghcr.io/acul021/key-connector:testing
    networks:
      - proxy
    environment:
      # Issuer and signing key are fetched from Vaultwarden's OIDC discovery document
      - "KC_IDENTITY_AUTHORITY=https://vault.example.tld/identity"
      - "KC_DATABASE_URL=sqlite:///data/keyconnector.db?mode=rwc"
      - "KC_CORS_ALLOWED_ORIGINS=https://vault.example.tld"
      # 32 random bytes, base64 encoded: openssl rand -base64 32
      - "KC_ENCRYPTION_KEY=<base64-encryption-key>"
    volumes:
      - "kc-data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.key-connector.rule=Host(`kc.example.tld`)"
      - "traefik.http.routers.key-connector.entrypoints=websecure"
      - "traefik.http.routers.key-connector.tls=true"
      - "traefik.http.routers.key-connector.tls.certresolver=letsencrypt"
      - "traefik.http.services.key-connector.loadbalancer.server.port=8081"

volumes:
  data:
  kc-data:

networks:
  proxy:
    external: true
```
A few notes:

- The Key Connector needs its own hostname, the clients talk to it directly. `ALLOWED_CONNECT_SRC` and `KC_CORS_ALLOWED_ORIGINS` have to match, otherwise the web vault blocks the requests.
- With `KC_IDENTITY_AUTHORITY` the connector discovers Vaultwarden's issuer and signing key itself and refreshes them every 10 minutes. If you prefer a static key instead, set `KC_JWT_ISSUER=https://vault.example.tld|login` and `KC_IDENTITY_PUBLIC_KEY_PATH`, and export the public key with `openssl rsa -in data/rsa_key.pem -pubout -out identity.pub.pem`.
- Losing `KC_ENCRYPTION_KEY` or the sqlite database means losing the user keys, so back both up.

This is testing-grade software. I run it for a small staging setup, feedback from another deployment would help. If you get stuck on the setup or hit a bug, open an issue in the key-connector repo and I'll pick it up there.
