### DISCUSSION TITLE
What's in the data directory when using the docker with mysql/mariadb?

### DISCUSSION THREAD

**Discussion by hellodword** [dani-garcia/vaultwarden#2596] [Q&A] [answered]
```
# tree /data
/data
|-- attachments
|-- icon_cache
|-- rsa_key.pem
|-- rsa_key.pub.pem
|-- sends
`-- tmp
```

**I only use vaultwarden to manager my passwords/TOTPs without `attachments`, and I do not use `send` or `generator`**.

So `/data/attachments` and `/data/sends` are useless for me, am I right?

And what's the `/data/rsa_key*.pem`?

And is there any other file in the `/data` important for me?

I backed up my vaultwarden instance with `mysqldump`, and tested it with a simple docker-compose:

```yaml
version: '3'

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  bitwarden:
    image: vaultwarden/server:latest
    env_file:
      - ./.env
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:8080:80/tcp"
```

It worked, but I'm not very sure.

Thanks.
