### DISCUSSION TITLE
Waf help

### DISCUSSION THREAD

**Discussion by shreyasajj** [dani-garcia/vaultwarden#2719] [Q&A]
Im stuggling to setup my waf up, 
It successfuly proxies to vaultwarden and shows up in traefik
But when I look in the logs the websocket fails to connect
`WebSocketTransport.js:99 WebSocket connection to 'wss://vaultwarden.example.com/notifications/hub?{accesstoken}' failed: `
I followed the wiki but im not sure.

**Here is my waf:**
```
 vaultwarden-waf:
    image: owasp/modsecurity-crs:apache
    container_name: vaultwarden-waf
    networks:
      - t2_proxy
    security_opt:
      - no-new-privileges:true
    environment:
      PARANOIA: 1
      ANOMALY_INBOUND: 10
      ANOMALY_OUTBOUND: 5
      ALLOWED_METHODS: "GET POST PUT DELETE OPTIONS PATCH HEAD"
      PROXY: 0
      REMOTEIP_INT_PROXY: "192.168.10.1/24"
      BACKEND: "http://vaultwarden:80"
      BACKEND_WS: "ws://vaultwarden:3012"
      ERRORLOG: "/var/log/waf/waf.log"
    volumes:
      - $DOCKERDIR/vaultwarden-waf/waf:/var/log/waf
      - $DOCKERDIR/vaultwarden-waf/waf-rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      - $DOCKERDIR/vaultwarden-waf/waf-rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.vaultwarden-rtr.entrypoints=https"
      - "traefik.http.routers.vaultwarden-rtr.rule=Host(`vaultwarden.$DOMAINNAME`)"
#      - "traefik.http.routers.vaultwarden-rtr.priority=10"
      ## Middlewares
      - "traefik.http.routers.vaultwarden-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.vaultwarden-rtr.service=vaultwarden-svc"
      - "traefik.http.services.vaultwarden-svc.loadbalancer.server.port=80"
      ## Vaultwarden WebSocket
      - "traefik.http.routers.vaultwardenHub-rtr.entrypoints=https"
      - "traefik.http.routers.vaultwardenHub-rtr.rule=Host(`vaultwarden.$DOMAINNAME`) && Path(`/notifications/hub`)"
#      - "traefik.http.routers.vaultwardenHub-rtr.priority=20"
      - "traefik.http.routers.vaultwardenHub-rtr.service=vaultwardenHub-svc"
      - "traefik.http.services.vaultwardenHub-svc.loadbalancer.server.port=3012"
      ## Admin Page
      - "traefik.http.routers.vaultwardenAdmin-rtr.entrypoints=https"
      - "traefik.http.routers.vaultwardenAdmin-rtr.rule=(Host(`vaultwarden.$DOMAINNAME`) && PathPrefix(`/admin`))"
#      - "traefik.http.routers.vaultwardenAdmin-rtr.priority=20"
      - "traefik.http.routers.vaultwardenAdmin-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.vaultwardenAdmin-rtr.service=vaultwarden-svc" 
```    

 **Here my Vaultwarden**

```
 vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: always
    networks:
      - t2_proxy
      - bw-net
#    ports:
#      - "80:80"
#      - "3012:3012"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/vaultwarden:/data
      - /var/log/docker:/var/log/docker
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SIGNUPS_ALLOWED=false # Change to false after first login
      - INVITATIONS_ALLOWED=true # Send invitation using admin page
      - WEBSOCKET_ENABLED=true
      - LOG_FILE=/var/log/docker/vaultwarden.log
      - SMTP_HOST=$SMTP_HOST
      - SMTP_FROM=$SMTP_EMAIL
      - SMTP_PORT=$SMTP_PORT
      - SMTP_SECURITY=starttls
      - SMTP_USERNAME=$SMTP_EMAIL
      - SMTP_PASSWORD=$SMTP_PASS
      - DOMAIN=https://vaultwarden.$DOMAINNAME
      - LOG_LEVEL=warn
      - ADMIN_TOKEN=$VAULTWARDEN_ADMIN_TOKEN
```
