### DISCUSSION TITLE
feat: allow sensitive environment variables to be the path to a file that contains the value

### DISCUSSION THREAD

**Discussion by aentwist** [dani-garcia/vaultwarden#2759] [Ideas]
In Docker, environment variables are not truly secure as they exist in images and are not masked. The only truly secure method to incorporate secrets is by mounting files containing them through to containers. Docker Swarm, and now Compose, implement this with [`secrets`](https://github.com/compose-spec/compose-spec/blob/master/spec.md#secrets).

Some applications allow configuration to be specified as the path to a file containing a value instead of the value directly for this kind of reason. I would like this to be possible with Vaultwarden, particularly regarding the admin token and SMTP credentials.

This would be implemented with a new set of configuration environment variables to avoid dual-purposing existing ones, breaking changes, etc. New environment variables would have the same names as their direct-valued counterparts, besides the addition of a meaningful suffix, likely `_PATH` or `_FILE`.

For example,

```yaml
services:
  vw:
    secrets:
      - smtp_username
    environment:
      SMTP_USERNAME_PATH: /run/secrets/smtp-username.txt

secrets:
  smtp_username:
    file: ./.secrets/smtp-username.txt
```

[GitGuardian](https://docs.gitguardian.com/secrets-detection/detectors/specifics/smtp_credentials) seems to mark SMTP host, port, username, and password as sensitive. Thus, these four configuration environment variables along with the admin token comprise the MVP for this idea.

**Comment by jjlin** [comment]
This was already implemented some years ago in #1244, but never documented AFAICT.

**Reply by aentwist** [reply]
Just tried it out, can confirm. The suffix is `_FILE`. This is available for all configuration environment variables. Definitely needs documentation in the wiki!

**Comment by ahmaddxb** [comment]
What im i doing wrong here, cant get it to work?

```
secrets
  vaultwarden_admin_token:
    file: $DOCKERDIR/secrets/vaultwarden_admin_token

  vaultwarden:
    environment:
      - ADMIN_TOKEN_FILE=/run/secrets/vaultwarden_admin_token
```
