### DISCUSSION TITLE
Setting env `_smtp_img_src` has no effect

### DISCUSSION THREAD

**Discussion by JensSpanier** [dani-garcia/vaultwarden#3127] [Q&A] [answered]
Hi!
I'm trying to set the config `_smtp_img_src` which was introduced here: https://github.com/dani-garcia/vaultwarden/commit/ea19c2250e0812659461c8abaf8f1a85e69c7423

My `docker-compose.yml` looks like this:

```yml
version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - ./vw-data:/data
      - ./images/favicon-16x16.png:/web-vault/images/favicon-16x16.png:ro
      - ./images/favicon-32x32.png:/web-vault/images/favicon-32x32.png:ro
      - ./images/icon-white.png:/web-vault/images/icon-white.png:ro
      - ./images/logo-dark@2x.png:/web-vault/images/logo-dark@2x.png:ro
      - ./images/logo-white@2x.png:/web-vault/images/logo-white@2x.png:ro
    ports:
      - 127.0.0.1:8086:80
      - 127.0.0.1:8087:3012
    environment:
      DATABASE_URL: mysql://***:***@***/***
      WEBSOCKET_ENABLED: 'true'
      _SMTP_IMG_SRC: https://***.***/vault-smtp-images/
```

But in the admin page the value of `_smtp_img_src` is still `https://***.***/vw_static/`.

How can I set `_smtp_img_src`?
