### DISCUSSION TITLE
502 Bad Gateway

### DISCUSSION THREAD

**Discussion by jgralfs** [dani-garcia/vaultwarden#3161] [Q&A]
I am running vaultwarden/server:latest in an almalinux 9 container on a proxmox host unsing the nginx proxy manager as a proxy.

I am able to start the container and everything is working fine but after a few minutes I get 502 Bad Gateway errors. When restarting the container everything works again for a few minutes.

**Comment by jgralfs** [comment]
docker-compose.yml looks like this:

```
version: '3'
services:
 vaultwarden:
  image: vaultwarden/server:latest
  environment:
    SIGNUPS_ALLOWED: "false"
    ROCKET_ADDRESS: "0.0.0.0"
  restart: unless-stopped
  ports:
    - "80:80"
  volumes:
    - /srv/vaultwarden:/data
```
