### DISCUSSION TITLE
VW logs report router/gateway IP not pc's

### DISCUSSION THREAD

**Discussion by avsteele** [dani-garcia/vaultwarden#3190] [Q&A] [answered]
### Subject of the issue

When connecting to the web vault or using the BW client from one particular PC & browser (Firefox) Vaultwarden logs report source IP as that of public-facing ip of the gateway, not the actually IP originating the request (i.e `192.168.1.x`)

Bizarrely, this only occurs when using one of my PCs (windows 10 home laptop on WiFi), and only when using Firefox. All addons are disabled, except the VW client. Logins from the VW client also report the public ip. I tried clearing browser cache, flushing dns, rebooting, and a few other things.

### Deployment environment

* vaultwarden version: 1.27.0

* Install method: docker

* Clients used: web vault

* Reverse proxy and version: nginx

* Other relevant details:

### Steps to reproduce
* Start VW via docker-compose
```
version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    ports:
      - 172.17.0.1:8080:80
      - 172.17.0.1:3012:3012
    restart: always
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - LOG_FILE=/data/vaultwarden.log
      - LOG_LEVEL=info
      - TIME_ZONE="US/Eastern"
    volumes:
      - ./data:/data
```

* log in or try to from the problem PC via Firefox on Windows 10 home

### Expected behaviour
Log IPs to be the same regardless of which browser I use.

### Actual behaviour
Logged IP differs from Edge vs Firefox when accessing the web vault.

### Troubleshooting data
Glad to provide add'l details.

I understand this may see like a strange issue. But the different behavior from two browsers on the same PC lead me to believe it might be a VW issue and not one with my PC/setup/DNS. I can ssh in from the problem pc to the same FQDN and `auth.log` reports the lan-local IP as well.

Also confusing, another PC (win 10 pro) on the same LAN using Firefox does **not** have this issue. So I'm very confused.
