### DISCUSSION TITLE
Docker+Traefik+ModSecurity Setup Help Please

### DISCUSSION THREAD

**Discussion by Bromelioideae** [dani-garcia/vaultwarden#3197] [Q&A]
I have put a few hours into trying to get this config working but I just can't figure out what I am doing wrong. Forgive the ramble but I need to give a little context. My server is a 1 GB ram free tier instance on Oracle Cloud. I am running Ubuntu 22.04 and it is updated. The specs are not an issue as I have successfully run dockered vaultwarden served by nginx for several years and recently migrated to docker+traefik+vaultwarden and everything is still running smoothly with that config. In an attempt to add another security layer I followed the [guide](https://github.com/dani-garcia/vaultwarden/wiki/Docker---Traefik---ModSecurity-Setup) in the wiki and made the appropriate changes to the docker-compose.yml:

```
version: '3.7'

services:
  traefik:
    image: traefik:latest
    container_name: traefik3
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=*****@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=acme.json
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./le:/letsencrypt
waf:
    image: owasp/modsecurity-crs:apache
    container_name: waf3
    environment:
      PARANOIA: 1
      ANOMALY_INBOUND: 10
      ANOMALY_OUTBOUND: 5
      PROXY: 1
      REMOTEIP_INT_PROXY: "172.20.0.1/16"
      BACKEND: "http://vw3:80"
      BACKEND_WS: "ws://vw3:80/notifications/hub"
      ERRORLOG: "/var/log/waf/waf.log"
      TZ: "America/Bogota"
    volumes:
     - ./waf:/var/log/waf
     - ./waf-rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.CONF
     - ./waf-rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.CONF
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true
      - traefik.http.routers.vw-ui-https.rule=Host(`vw3.domain.cyou`)
      - traefik.http.routers.vw-ui-https.entrypoints=websecure
      - traefik.http.routers.vw-ui-https.tls=true
      - traefik.http.routers.vw-ui-https.service=vw-ui
      - traefik.http.routers.vw-ui-http.rule=Host(`vw3.domain.cyou`)
      - traefik.http.routers.vw-ui-http.entrypoints=web
      - traefik.http.routers.vw-ui-http.middlewares=redirect-https
      - traefik.http.routers.vw-ui-http.service=vw-ui
      - traefik.http.services.vw-ui.loadbalancer.server.port=80
      - traefik.http.routers.vw-websocket-https.rule=Host(`vw3.domain.cyou`) && Path(`/notifications/hub`)
      - traefik.http.routers.vw-websocket-https.entrypoints=websecure
      - traefik.http.routers.vw-websocket-https.tls=true
      - traefik.http.routers.vw-websocket-https.service=vw-websocket
      - traefik.http.routers.vw-websocket-http.rule=Host(`vw3.domain.cyou`) && Path(`/notifications/hub`)
      - traefik.http.routers.vw-websocket-http.entrypoints=web
      - traefik.http.routers.vw-websocket-http.middlewares=redirect-https
      - traefik.http.routers.vw-websocket-http.service=vw-websocket
      - traefik.http.services.vw-websocket.loadbalancer.server.port=3012

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden3
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: "true"
      SENDS_ALLOWED: "true"
      PASSWORD_ITERATIONS: 600000
      SIGNUPS_ALLOWED: "false"
      SIGNUPS_VERIFY: "true"
      SIGNUPS_DOMAINS_WHITELIST: "domain.cyou"
      #ADMIN_TOKEN: "Nice long token" #generate with openssl rand
      DOMAIN: "https://vw3.domain.cyou"
      #SMTP_HOST: "smtp server"
      #SMTP_FROM: "sender email e.g: you@domain.tld"
      SMTP_FROM_NAME: "sender name"
      SMTP_SECURITY: "starttls"
      SMTP_PORT: 587
      SMTP_USERNAME: "smtp username"
      SMTP_PASSWORD: "smtp password"
      SMTP_TIMEOUT: 15
      LOG_FILE: "/data/vaultwarden.log"
      LOG_LEVEL: "warn"
      EXTENDED_LOGGING: "true"
      TZ: "America/Bogota"
    volumes:
      - ./vaultwarden:/data

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.1/16
```
I initially had an issue with the shortened hostname `(http://vw3)` but I resolved that by adding `127.0.01 vw3` to `/etc/hosts`. I am currently stuck on `Bad Request Your browser sent a request that this server could not understand` response in the browser. Fortunately, I had `tail -f waf.log` running and I just now saw that waf.log was being filled with the following message while the browser was on the page:
`[Sun Jan 29 10:49:37.866650 2023] [security2:error] [pid 1753:tid 140259822081792] [client 127.0.0.1:37184] [client 127.0.0.1] ModSecurity: Warning. Matched phrase "/.env" at REQUEST_FILENAME. [file "/etc/modsecurity.d/owasp-crs/rules/REQUEST-930-APPLICATION-ATTACK-LFI.conf"] [line "125"] [id "930130"] [msg "Restricted File Access Attempt"] [data "Matched Data: /.env found within REQUEST_FILENAME: /saas/.env"] [severity "CRITICAL"] [ver "OWASP_CRS/3.3.4"] [tag "modsecurity"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-lfi"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/255/153/126"] [tag "PCI/6.5.4"] [hostname "vw3.[actual_hostname].cyou"] [uri "/saas/.env"] [unique_id "Y9aVkUPksVR7nwmfhkb3OAAAAUE"], referer: https://www.google.com/`

These messages kept appearing until I got:
`[Sun Jan 29 10:50:48.183293 2023] [mpm_event:error] [pid 1:tid 140260126321984] AH03490: scoreboard is full, not at MaxRequestWorkers.Increase ServerLimit.`

I took down the containers at that point. When the containers are running everything looks normal and I get no errors. Output from `docker logs` and `docker ps` below:
```
$ docker logs d50bc76e0c00
$ docker logs 2cc069b08627
time="2023-01-29T16:16:37Z" level=info msg="Configuration loaded from flags."
ubuntu@bw:~/aio$ docker logs eeba5e2881e0
/--------------------------------------------------------------------\
|                        Starting Vaultwarden                        |
|                           Version 1.27.0                           |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://vaultwarden.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/vaultwarden/issues/new            |
\--------------------------------------------------------------------/

[INFO] No .env file found.

$ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS                   PORTS                                                                      NAMES
d50bc76e0c00   owasp/modsecurity-crs:apache   "/docker-entrypoint.…"   3 minutes ago   Up 3 minutes (healthy)   80/tcp                                                                     waf3
2cc069b08627   traefik:latest                 "/entrypoint.sh --pr…"   3 minutes ago   Up 3 minutes             0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   traefik3
eeba5e2881e0   vaultwarden/server:latest      "/start.sh"              3 minutes ago   Up 3 minutes (healthy)   80/tcp, 3012/tcp                                                           vaultwarden3
```
Even though I get no output from `docker logs` for the owasp container it is definitely doing something based on `waf.log`. When I try `curl localhost`, `curl vw3` or `curl [host IP]`, I get the same `404 page not found` error.

I am pleased to see that the modsecurity WAF is doing something with this config as I tried to implement docker+owasp/modsecurity-crs:apache on a working docker+traefik+vaultwarden setup but I am also failing miserably at that. I am sure when I get the solution I will slap myself for missing it but regardless this has been a wonderful learning experience. At this point I believe the configuration issue is between modsecurity and vaultwarden but I really have no idea and I am at the end of my limited capabilities in linux system administration. I also note the disclaimer that `This is only tested on Debian (but should work on similar systems like Ubuntu or Raspbian)` but hope springs eternal that this isn't a platform incompatibility issue. I have searched these forums and elsewhere and cannot find a comparable issue. Help please.
