### DISCUSSION TITLE
Docker+Traefik+Vaultwarden WebSocket Notification Issue

### DISCUSSION THREAD

**Discussion by Bromelioideae** [dani-garcia/vaultwarden#3209] [Q&A]
I thought my Docker+Traefik+Vaultwarden confir was working perfectly but I just realised notifications are not. I went to `https://vw2.[example].com/notifications/hub` and got `Bad Gateway`. If I add a trailing slash I get `{}`. My docker-compose.yml:
```
version: '3.7'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    command:
      #- --experimental.plugins.traefik-modsecurity-plugin.modulename=github.com/acouvreur/traefik-modsecurity-plugin
      #- --experimental.plugins.traefik-modsecurity-plugin.version=v1.2.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      # Add folder for WAF log
      #- ./data/logs:/var/log/waf
      # Add folder with dynamic configuration yml
      - ./data/configurations:/configurations
      # Add folder for Rules
      #- ./data/waf-rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      #- ./data/waf-rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik2.[example].com`)"
      - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.middlewares.waf.plugin.traefik-modsecurity-plugin.modSecurityUrl=http://waf:80"
      - "traefik.http.middlewares.waf.plugin.traefik-modsecurity-plugin.maxBodySize=10485760"
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vw
    restart: always
    volumes:
      - /home/ubuntu/vaultwarden/vw-data:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - PASSWORD_ITERATIONS=600000
      - SIGNUPS_ALLOWED=false
      - LOG_FILE=/data/vaultwarden.log
      - LOG_LEVEL=warn
      - EXTENDED_LOGGING=true
      - TZ=America/Bogota
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # OWASP WAF
      #- "traefik.http.routers.vaultwarden-secure.middlewares=waf@docker"
      # Entry Point for https
      - "traefik.http.routers.vaultwarden-secure.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-secure.rule=Host(`vw2.[example].com`)"
      - "traefik.http.routers.vaultwarden-secure.service=vaultwarden-service"
      - "traefik.http.services.vaultwarden-service.loadbalancer.server.port=80"
      # websocket
      - "traefik.http.routers.vaultwarden-ws.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden-ws.rule=Host(`vw2.[example].com`) && Path(`/notifications/hub`)"
      - "traefik.http.middlewares.vaultwarden-ws=bw-stripPrefix@file"
      - "traefik.http.routers.vaultwarden-ws.service=vaultwarden-websocket"
      - "traefik.http.services.vaultwarden-websocket.loadbalancer.server.port=3012"
networks:
  proxy:
    external: true
```
I don't know what I am missing.

**Comment by RealOrangeOne** [comment]
Interesting. It's a websocket endpoint, so it doing strange things when you open it in the browser is expected. If you open the vault and check the network tab, does it successfully make a websocket connection?

![image](https://user-images.githubusercontent.com/6527489/215843023-3cf690a5-ccbd-4df5-8d1b-6849c03c147f.png)

(Status `101` means successful in this case).

There's a proxy example at https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples, and here's mine for reference: https://github.com/RealOrangeOne/infrastructure/blob/master/ansible/roles/vaultwarden/files/docker-compose.yml

**Reply by Bromelioideae** [reply]
This one is beating me. I edited my `docker-compose.yml` to match yours but I still get `HTTP/1.1 502 Bad Gateway` (I had already checked with the Proxy-examples and they matched).

**Reply by RealOrangeOne** [reply]
Are you getting that the dev tools or when you go to visit the URL directly?

**Reply by Bromelioideae** [reply]
Sorry to be getting back so late on this. I was using the `http get` command in the terminal to see the actually http response code before I found out I get that info with dev tools.

So I had a revelatory moment away from the PC and realised I didn't expose port 3012 in Traefik. I thought I could simply add:
```
  websocket:
    address: :3012
```
to my entryPoints: in traefik.yml but apart from appearing in the Traefik dashboard it had no effect.  Still beating me.

**Reply by RealOrangeOne** [reply]
You don't need to expose 3012 in Traefik. Traefik proxies _to_ that port, it still serves it on 80/443.

Using `http get` from the command line has the same issue I mentioned above by visiting the URL directly. If you log in to the web vault, look at the dev tools, do you get a successful websocket connection?

It's a websocket, so using something which doesn't expect websockets will always behave weirdly. Sure, showing something nicer would be better, but showing "Bad gateway" isn't an issue.

**Comment by lastsamurai26** [comment]
```
version: '3'
services:
  bitwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=${WEBSOCKET_ENABLED}
      - SENDS_ALLOWED=${SENDS_ALLOWED}
      - DOMAIN=${DOMAIN}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_SECURITY=${SMTP_SECURITY}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_TIMEOUT=${SMTP_TIMEOUT}
      - SMTP_AUTH_MECHANISM=${SMTP_AUTH_MECHANISM}

    volumes:
       - /opt/containers/bitwarden/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.http.routers.vtwn-rtr-ui.rule=Host(`vtwn.domain.me`)"
      - "traefik.http.routers.vtwn-rtr-ui.entrypoints=https"
      - "traefik.http.routers.vtwn-rtr-ui.tls=true"
      - "traefik.http.routers.vtwn-rtr-ui.tls.certresolver=le"
      - "traefik.http.routers.vtwn-rtr-ui.service=vtwn-svc-ui"
      - "traefik.http.services.vtwn-svc-ui.loadbalancer.server.port=80"
      - "traefik.http.routers.vtwn-rtr-ui.middlewares=default@file"


      - "traefik.http.routers.vtwn-wss-rtr.rule=Host(`vtwn.domain.me`) && Path(`/notifications/hub/`)"
      - "traefik.http.routers.vtwn-wss-rtr.entrypoints=https"
      - "traefik.http.routers.vtwn-wss-rtr.tls=true"
      - "traefik.http.routers.vtwn-wss-rtr.tls.certresolver=le"
      - "traefik.http.routers.vtwn-wss-rtr.service=vtwn-wss-svc"
      - "traefik.http.services.vtwn-wss-svc.loadbalancer.server.port=3012"
      - "traefik.http.middlewares.vtwn-wss-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.vtwn-wss-rtr.middlewares=vtwn-wss-headers,default@file"
      networks:
      - traefik_web
networks:
  traefik_web:
   external: true 
```


i can't get websocket to work :-(
