### DISCUSSION TITLE
Docker Secrets integration

### DISCUSSION THREAD

**Discussion by jonathan8devs** [dani-garcia/vaultwarden#3462] [Ideas]
It would be desirable for Vaultwarden to support Docker Secrets as well.

This is very practical, especially in a Docker Swarm or in an automatic deploy. Databases such as PostgreSQL also support this feature.

Currently you can use this via a small detour in Vaultwarden, but since the tip https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page#secure-the-admin_token I have not yet made it work again.

1. i have defined several secrets in my docker compose.
2. next I add a volumes with which I can integrate bash scripts:

```yaml
service:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    depends_on:
      - vaultwarden-db
    restart: always
    volumes:
      - ./scripts:/etc/vaultwarden.d
```

4. now I create a bash script in the created folder:

```bash
export DATABASE_URL=mysql://vaultwarden:$(cat /run/secrets/vaultwarden_mariadb_password)@vaultwarden-db/vaultwarden
export ADMIN_TOKEN=$(cat /run/secrets/vaultwarden_admin_token)
export SMTP_PASSWORD=$(cat /run/secrets/vaultwarden_smtp_password)
```

I would like to share my solution, but I would be very happy if it generally takes hold in Vaultwarden :)

Resources:
- https://docs.docker.com/engine/swarm/secrets/
- https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page#secure-the-admin_token
