### DISCUSSION TITLE
Docker+Traefik+Vaultwarden WebSocket Error 502 websocket

### DISCUSSION THREAD

**Discussion by dronmaxman** [dani-garcia/vaultwarden#3516] [Q&A]
I think its some mistake in vaultwarden wiki.
https://github.com/dani-garcia/vaultwarden/wiki/Docker---Traefik---ModSecurity-Setup

1. waf set label   - traefik.http.services.vw-websocket.loadbalancer.server.port=3012 but waf don't listening port 3012 so I got 502 error.
2. waf env BACKEND_WS: "ws://vaultwarden:80/notifications/hub" but vaultwarden listen 3012 for websocket.

This example docker-compose.yml doesn't work with websocket, it's time to update it.

**Comment by BlackDex** [comment]
A quick look at that page it doesn't look like the WAF is listening on 3012, but only the final endpoint for the websockets as far as i can tell.
I don't use traefik my self, so i have no clue if all is correct.

But,  you should double check the logs of Vaultwarden, and make sure you have `WEBSOCKET_ENABLED` set to `true` and you have that port opened/passed through.

**Reply by dronmaxman** [reply]
Yes, WEBSOCKET_ENABLED is set to true
```
root@vs-kv-web-vw01 [ ~ ]# docker ps
CONTAINER ID   IMAGE                         COMMAND                  CREATED         STATUS                            PORTS                                                                      NAMES
f83dc6c795be   vaultwarden/server:latest     "/start.sh"              7 seconds ago   Up 5 seconds (health: starting)   80/tcp, 3012/tcp                                                           vaultwarden
a167ec212d6d   traefik:latest                "/entrypoint.sh --pr…"   7 seconds ago   Up 5 seconds                      0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   traefik
6a6bc8fccfc9   owasp/modsecurity-crs:nginx   "/docker-entrypoint.…"   7 seconds ago   Up 5 seconds (health: starting)   80/tcp
```

**Comment by dronmaxman** [comment]
At the moment I have excluded waf from the docker-compose and websocker works as expected. I can deduce that the websocket is definitely running on port 3012.

```
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=false
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --log.level=DEBUG
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./tls.yml:/etc/traefik/dynamic_conf/tls.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssl:/etc/ssl/traefik

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: "true"
      SENDS_ALLOWED: "true"
      PASSWORD_ITERATIONS: 500000
      SIGNUPS_ALLOWED: "true"
      SIGNUPS_VERIFY: "true"
      #SIGNUPS_DOMAINS_WHITELIST: "yourdomain.tld"
      ADMIN_TOKEN: "SuPPerADMINstr" #generate with openssl rand
      DOMAIN: "https://bpass.example.com"
      SMTP_HOST: "mail.example.ua"
      #SMTP_FROM: "bpass@example.com"
      SMTP_FROM: "test.user5@example.ua"
      SMTP_FROM_NAME: "Bpass"
      SMTP_SECURITY: "off"
      SMTP_PORT: 25
#      SMTP_USERNAME: "smtp username"
#      SMTP_PASSWORD: "smtp password"
      SMTP_TIMEOUT: 15
      LOG_FILE: "/data/vaultwarden.log"
      #LOG_LEVEL: "warn"
      LOG_LEVEL: "DEBUG"
      EXTENDED_LOGGING: "true"
      TZ: "Europe/Kiev"
    volumes:
      - ./vw-data:/data
    labels:
      - traefik.enable=true
      - traefik.backend=vaultwarden
      - traefik.http.middlewares.redirect-https.redirectScheme.scheme=https
      - traefik.http.middlewares.redirect-https.redirectScheme.permanent=true

      - traefik.http.services.vw-ui.loadbalancer.server.port=80
      - traefik.http.routers.vw-ui-https.rule=Host(`bpass.example.com`)
      - traefik.http.routers.vw-ui-https.entrypoints=websecure
      - traefik.http.routers.vw-ui-https.tls=true
      - traefik.http.routers.vw-ui-https.service=vw-ui

      - traefik.http.routers.vw-ui-http.rule=Host(`bpass.example.com`) || Host(`bpass.example.com`) && Path(`/notifications/hub/negotiate`)
      - traefik.http.routers.vw-ui-http.entrypoints=web
      - traefik.http.routers.vw-ui-http.middlewares=redirect-https
      - traefik.http.routers.vw-ui-http.service=vw-ui

      - traefik.http.services.vw-websocket.loadbalancer.server.port=3012
      - traefik.http.routers.vw-websocket-https.rule=Host(`bpass.example.com`) && Path(`/notifications/hub`)
      - traefik.http.routers.vw-websocket-https.entrypoints=websecure
      - traefik.http.routers.vw-websocket-https.tls=true
      - traefik.http.routers.vw-websocket-https.service=vw-websocket
      - traefik.http.routers.vw-websocket-http.rule=Host(`bpass.example.com`) && Path(`/notifications/hub`)
      - traefik.http.routers.vw-websocket-http.entrypoints=web
      - traefik.http.routers.vw-websocket-http.middlewares=redirect-https
      - traefik.http.routers.vw-websocket-http.service=vw-websocket
     
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.1/16
     
```
