### DISCUSSION TITLE
Upgrade about 1.29.0

### DISCUSSION THREAD

**Discussion by mobeicanyue** [dani-garcia/vaultwarden#3672] [Q&A]
this is my vaultwarden docker compose file after upgrade
Is it correctly?
```
version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    ports:
      - '666:80'    
    volumes:
      - ./vw-data:/data
    environment:
      DOMAIN: https://aaa.site
      WEB_VAULT_ENABLED: "true"
      SIGNUPS_ALLOWED: false
```

and the following is my nginx reverse proxy configuration, how to edit it 
Do I just need to comment out this piece of code?
![image](https://github.com/dani-garcia/vaultwarden/assets/81098819/7e12328a-c422-4b9d-87b9-2124a56ef934)

If the following configuration has other redundant, unwanted lines of code, please point out
```
#PROXY-START/
location ^~ /
{
    proxy_pass http://127.0.0.1:666;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    location ^~ /notifications/hub {
      proxy_pass http://127.0.0.1:3012;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Forwarded $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /notifications/hub/negotiate {
      proxy_pass http://127.0.0.1:666;
    }
    
    
    proxy_http_version 1.1;
    # proxy_hide_header Upgrade;

    add_header X-Cache $upstream_cache_status;
		#Set Nginx Cache

    if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" )
    {
        expires 1m;
    }
    proxy_ignore_headers Set-Cookie Cache-Control expires;
    proxy_cache cache_one;
    proxy_cache_key $host$uri$is_args$args;
    proxy_cache_valid 200 304 301 302 3m;
}
#PROXY-END/
```
