### DISCUSSION TITLE
Endpoints for Android App to bypass Authelia

### DISCUSSION THREAD

**Discussion by mattheys** [dani-garcia/vaultwarden#3970] [Q&A]
Hi, I like to secure all my selfhosted apps as much as possible but understand that sometimes an FBA login doesn't work well with native apps.

In order to expose the least amount possible is it just /api, /notifications and /identity that the Android app requires to access?  Or are there any more that I haven't noticed yet?  Can I limit it to specific Verbs or is there a Authelia Query pattern I can use?

Thanks in advance.

My config looks similar to this.
```
access_control:
  default_policy: deny
  rules:

    - domain: 'vaultwarden.domain.com'
      policy: bypass
      resources:
        - '^/api([/?].*)?$'
        - '^/notifications([/?].*)?$'
        - '^/identity([/?].*)?$'

    - domain: '*.domain.com'
      policy: two_factor
      subject:
        - 'group:admins'
```
