### DISCUSSION TITLE
Issue when trying to build image

### DISCUSSION THREAD

**Discussion by AlexShku** [dani-garcia/vaultwarden#4020] [Q&A] [answered]
Hello! 
I receive an error when trying to build image: 

`Step 3/38 : FROM --platform=$BUILDPLATFORM docker.io/library/rust:1.73.0-slim-bookworm as build
failed to parse platform : "" is an invalid component of "": platform specifier component must match "^[A-Za-z0-9_-]+$": invalid argument`

Working with gitlab-ci. 
```
stages: 
 - build_and_push_image

build_deploy:
  tags: 
    - docker
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  stage: build_and_push_image
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build --pull -t "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vault-test:latest" .
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vault-test:latest"
```
```
$ aws --version
aws-cli/2.13.31 Python/3.11.6 Linux/5.15.0-1028-aws docker/x86_64.amzn.2 prompt/off
$ docker --version
Docker version 20.10.25, build b82b9f3
```

Please help to find solution.
