### DISCUSSION TITLE
Is anybody using Cloudflare Tunnel to access Vaultwarden running in a Docker container?

### DISCUSSION THREAD

**Discussion by queen4me** [dani-garcia/vaultwarden#4073] [Q&A]
I'd like to use Cloudflare Tunnel instead of portforwarding on my router because this seems more secure.
In the Cloudflare Docs is no information on howto connect to a docker container (in my example with Vaultwarden) using Cloudflare Tunnels.

If anybody has a link containing some information how to use Cloudflare Tunnels to securely connect to a Docker container in my home network this would help me a lot.

Thanks in advance for any hints.

**Comment by JackFZG** [comment]
I think you can refer to the content in this link(https://sspai.com/post/79278), but it is in Chinese.

**Comment by gigaion** [comment]
@queen4me 
First make sure the subdomain doesn't exist in your cloudflare account. Cloudflare will add it, during the process below:

1. Start by creating a Tunnel within Zero Trust on Cloudflare.
2. When it asks you to install Tunnel, you can do something similar to below:

```
vaultwarden-cf-tunnel1:
  container_name: vaultwarden-cf-tunnel1
  image: cloudflare/cloudflared:latest
  dns:
    - "8.8.8.8"
    - "1.1.1.1"
  command:
    - tunnel
    - --no-autoupdate
    - run
    - --token
    - example_token_here
  deploy:
    restart_policy:
      condition: unless-stopped
      delay: 5s
```

Then add modify your cloudflare tunnel with a Public Hostname:
![image](https://github.com/dani-garcia/vaultwarden/assets/36256725/350471fe-b1a4-4567-9b2a-e45ec41990f5)

The vaultwarden URL specified above, is based on how this docker vaultwarden is configured:
```
  vaultwarden:
    image: "vaultwarden/server:1.30.0"
    container_name: "vaultwarden"
    hostname: "vaultwarden"
```
