### DISCUSSION TITLE
Running Vaultwarden in Kubernetes, problem with sqlite3 database is locked

### DISCUSSION THREAD

**Discussion by ArtursTrubacs** [dani-garcia/vaultwarden#4186] [Q&A]
I want run and test vaultwarden/server:1.30.1 on my k8s cluster from private Gitlab reg. When i run my Vaultwarden I receive error message database is locked. Where can bee fault? Vaultwarden data is stored on Nfs server. Accesses from k8s cluster to nfs server is granted.
Logs from my Vaultwarden pod.

kubeclt logs pod id [vaultwarden-765ddb6b67-4wjtw]

[2023-12-18 11:47:00.299][panic][ERROR] thread ‘main’ panicked at ‘Error running migrations: DatabaseError(Unknown, “database is locked”)’: src/db/mod.rs:452
0: vaultwarden::init_logging::{{closure}}
1: std::panicking::rust_panic_with_hook
2: std::panicking::begin_panic_handler::{{closure}}
3: std::sys_common::backtrace::__rust_end_short_backtrace
4: rust_begin_unwind
5: core::panicking::panic_fmt
6: core::result::unwrap_failed
7: vaultwarden::db::sqlite_migrations::run_migrations
8: vaultwarden::db::DbPool::from_config
9: vaultwarden::main::{{closure}}
10: vaultwarden::main
11: std::sys_common::backtrace::__rust_begin_short_backtrace
12: std::rt::lang_start::{{closure}}
13: std::rt::lang_start_internal
14: main
15:
16: __libc_start_main
17: _start

My Vaultwarden deployment, YAML file
```
#bitwarden-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitwarden
  template:
    metadata:
      labels:
        app: bitwarden
    spec:
      containers:
      - name: bitwarden
        image: gitlabtestbitwarden-server:2023.12.0
        ports:
        - containerPort: 80
        env:
        - name: ADMIN_TOKEN
          value: "testtoken"
        volumeMounts:
        - name: bitwarden-data
          mountPath: /data
      imagePullSecrets:
      - name: gitlab-access
      volumes:
      - name: bitwarden-data
        persistentVolumeClaim:
          claimName: bitwarden-pvcs
```

My PV:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden-pvs
spec:
  accessModes:
    - ReadWriteOnce  
  capacity:
    storage: 5Gi
  nfs:
    path: /Corrected path
    server: nfs ip

```

My pvc

```

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-pvcs
  namespace: bitwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

```
