### DISCUSSION TITLE
Config file config.json missing despite having ADMIN_TOKEN specified

### DISCUSSION THREAD

**Discussion by danieldotkim** [dani-garcia/vaultwarden#4214] [Q&A] [answered]
I am running VaultWarden using the [docker-compose method with Caddy](https://github.com/dani-garcia/vaultwarden/wiki/Using-Docker-Compose).

I am able to access the admin portal by going to domain.com/admin and putting in the admin token I specified but there is no config.json file in my data folder.

Here is my docker-compose.yml (just the top part w/o Caddy)
```
version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "https://domain.com"
      ADMIN_TOKEN: "admin-token-placeholder"
      SMTP_HOST: "mail.smtp2go.com"
      SMTP_FROM: "noreply@domain.com"
      SMTP_PORT: 2525
      SMTP_SECURITY: "starttls"
      SMTP_USERNAME: "noreply@domain.com"
      SMTP_PASSWORD: "password-placeholder"
    volumes:
      - ./vw-data:/data
```

These are the files/folders in the vw-data folder. Am I looking at a wrong place? Any help would be greatly appreciated.

```
ls vw-data/
attachments  db.sqlite3  db.sqlite3-shm  db.sqlite3-wal  icon_cache  rsa_key.pem  rsa_key.pub.pem  sends  tmp
```
