### DISCUSSION TITLE
ERROR on Mobile Client push notification with env variable with docker compose secrets

### DISCUSSION THREAD

**Discussion by Barnoux** [dani-garcia/vaultwarden#4360] [Q&A] [answered]
### Deployment environment

* vaultwarden version: 1.30.3

* Install method: docker compose

* Clients used:  iOS, webvault and desktop

* Reverse proxy and version:  Caddy 2.7.6

* MySQL/MariaDB or PostgreSQL version:  SQLite

* Other relevant details:
```
services:
    vaultwarden:
      image: vaultwarden/server:latest
      container_name: vaultwarden
      user: 24784:24784
      environment:
        # env definition => https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
        PUSH_ENABLED: "true"
        PUSH_INSTALLATION_KEY: /run/secrets/push-key
        PUSH_INSTALLATION_ID: /run/secrets/push-id
        PUSH_RELAY_URI: "https://push.bitwarden.eu"
        PUSH_IDENTITY_URI: "https://identity.bitwarden.eu"

        SIGNUPS_ALLOWED: "false"

        ADMIN_TOKEN_FILE: /run/secrets/admin-token

        DOMAIN: "https://vaultwarden.one4all.icu"
        ROCKET_PORT: "60278"

        SMTP_FROM: "vaultwarden@one4all.icu"
        SMTP_HOST: "smtp.gmail.com"
        SMTP_PORT: "587"
        SMTP_SECURITY: "starttls"
        SMTP_USERNAME: "bbarnoux@gmail.com"
        SMTP_PASSWORD_FILE: /run/secrets/smtp-password

        LOG_FILE: "/var/log/vaultwarden/vaultwarden.log" 
        LOG_LEVEL: "warn"
        EXTENDED_LOGGING: "true"
        IP_HEADER: "X-Forwarded-For"

        TZ: "Europe/Paris"
      networks:
          - reverse-proxy
      volumes:
        - vaultwarden-data:/data
        - /var/log/vaultwarden:/var/log/vaultwarden
      secrets:
          - source: admin-token
          - source: smtp-password
          - source: push-id
          - source: push-key
          - 
secrets:
  admin-token:
     file: ../secrets/admin-token.txt
  smtp-password:
     file: ../secrets/smtp-password.txt
  push-id:
     file: ../secrets/push-id.txt
  push-key:
     file: ../secrets/push-key.txt

volumes:
  vaultwarden-data:
    external: true
    name: one4all-vaultwarden-data
```

### Expected behaviour

renaming a folder in the web vault should change after a few seconds in the mobile app.

### Actual behaviour

i'm having the path of the secrets variables instead of having the actual push-id and push-key. i don't have this behavior for admin_token and smtp_password.

### Troubleshooting data

![Capture d’écran du 2024-02-17 15-11-40](https://github.com/dani-garcia/vaultwarden/assets/47791676/7c776613-b162-4daa-a312-33e330753925)

```
[2024-02-17 15:00:12.907][vaultwarden::api::push][ERROR] Unexpected push token received from bitwarden server: error decoding response body: missing field `access_token` at line 1 column 26
```

**Comment by BlackDex** [comment, marked as answer]
You need to append the env variables with `_FILE`, same is you did for the smtp password.

**Comment by ilteoood** [comment]
@BlackDex I have a similar problem. Can you give me an hint?

This is my docker-compose:
```
version: '2'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - /media/vaultwarden:/data/
    ports:
      - 9999:80
    dns: 1.1.1.1
    labels:
      - "traefik.http.routers.pwd.rule=Host(`my-domain`)"
      - "traefik.http.routers.pwd.entrypoints=websecure"
      - "traefik.http.routers.pwd.tls=true"
      - "traefik.http.routers.pwd.tls.certresolver=letsresolver"
      - "traefik.http.services.pwd.loadbalancer.server.port=80"
    environment:
      PUSH_ENABLED: true
      PUSH_INSTALLATION_ID: MY_ID
      PUSH_INSTALLATION_KEY: MY_KEY
      PUSH_RELAY_URI: https://push.bitwarden.eu
      PUSH_IDENTITY_URI: https://identity.bitwarden.eu
      DOMAIN: https://my-domain
    networks:
      - traefik
      
networks:
  traefik:
    external:
      name: traefik_default
```

And this is the error I receive:
```
[2024-02-18 11:55:55.591][vaultwarden::api::push][ERROR] An error occurred while sending a send update to the push relay: error sending request for url (https://push.bitwarden.eu/push/send): error trying to connect: tcp connect error: Cannot assign requested address (os error 99)
```
