### DISCUSSION TITLE
Windows 11 Desktop App FIDO2 WebAuthn Stuck on "Loading"

### DISCUSSION THREAD

**Discussion by qymab** [dani-garcia/vaultwarden#4433] [Q&A] [answered]
I have a similar issue to the one described in [this discussion](https://github.com/dani-garcia/vaultwarden/discussions/2111). I have removed all headers and confirmed that the app from the Microsoft Store and the direct download have the same [problems](https://github.com/dani-garcia/vaultwarden/discussions/3708). I'm using Authelia and Traefik.

My findings so far:

If I change the middlewares from ```chain-authelia``` to ```chain-no-auth```, which has this chain:

```chain-no-auth.yml```:
```yaml
http:
  middlewares:
    chain-no-auth:
      chain:
        middlewares:
          - middlewares-traefik-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-compress
```

```chain-authelia.yml```:
```yaml
http:
  middlewares:
    chain-authelia:
      chain:
        middlewares:
          - middlewares-traefik-bouncer
          - middlewares-rate-limit
          - middlewares-secure-headers
          - middlewares-authelia
          - middlewares-compress
```

The only difference is the ```middlewares-authelia```. With ```chain-no-auth```, WebAuthn works fine. Therefore, I think the fault isn't in Traefik.

This is the ```middlewares-authelia.yml```:
```yaml
http:
  middlewares:
    middlewares-authelia:
      forwardAuth:
        address: http://authelia:9091/api/verify?rd=https://auth.domain.com
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
```

And this is the Authelia configuration:
```yaml
default_redirection_url: https://auth.domain.com

server:
  host: 0.0.0.0
  port: 9091

totp:
  issuer: authelia.com
  period: 30
  skew: 1

access_control:
  default_policy: deny
  rules:
    - domain: 'auth.domain.com'
      policy: bypass
    - domain: 'traefik.domain.com'
      policy: two_factor
      subject:
        - 'group:admins'
    - domain: 'traefik.domain.com'
      policy: deny
    - domain: 'vaultwarden.domain.com'
      policy: two_factor
      resources:
        - '^/admin([/?].*)?$'
      subject:
        - 'group:admins'
    - domain: 'vaultwarden.domain.com'
      resources:
        - '^/admin([/?].*)?$'
      policy: deny
    - domain: 'vaultwarden.domain.com'
      policy: bypass
      resources:
        - '^/api([/?].*)?$'
        - '^/notifications([/?].*)?$'
        - '^/identity([/?].*)?$'
    - domain: '*.domain.com'
      policy: two_factor
    - domain: 'domain.com'
      policy: two_factor
```

Any pointers on what I should check next?

**Comment by BlackDex** [comment]
The secure headers could cause issues.
Also make sure the domain is configured correctly. Check the `/admin/diagnose` page for any other possible issues.

**Reply by qymab** [reply]
I have tried testing with or without secure headers. Still, WebAuthn fails.

this my relevance ```middlewares-secure-headers.yml```

```yaml
http:
  middlewares:
    middlewares-secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - X-Forwarded-Host
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "same-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          server: ""
```

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.30.5
* Web-vault version: v2024.1.2b
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Forwarded-For)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: PostgreSQL
* Database version: PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** 


```json
{
  "_duo_akey": null,
  "_enable_duo": true,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "**********://******************************************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://******************",
  "domain_origin": "*****://******************",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": false,
  "ip_header": "X-Forwarded-For",
  "job_poll_interval_ms": 30000,
  "log_file": "/data/vaultwarden.log",
  "log_level": "info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "push_enabled": true,
  "push_identity_uri": "https://identity.bitwarden.com",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": true,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "*********************",
  "smtp_from_name": "redacted",
  "smtp_host": "***************************************",
  "smtp_password": "***",
  "smtp_port": redacted,
  "smtp_security": "redacted",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": "********************",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": false,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>
