### DISCUSSION TITLE
No attachments in Web UI

### DISCUSSION THREAD

**Discussion by slayer** [dani-garcia/vaultwarden#4453] [Q&A] [answered]
Hi all

Maybe stupid question, but I have no "attachments" in web UI.

<img width="807" alt="image" src="https://github.com/dani-garcia/vaultwarden/assets/57521/1a1f0fd7-6880-49f7-9edd-3199fbdb7a9d">

I use docker-compose setup 

```yaml
  warden:
    image: vaultwarden/server:latest-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8180:80"
    volumes:
      - ./data/vault:/data/
```

I have directory `data/vault/attachments` and it's blank.

What is wrong with my setup?
