### DISCUSSION TITLE
Some variables from .env file being ignored i.e. ROCKET_PORT

### DISCUSSION THREAD

**Discussion by RT-Tap** [dani-garcia/vaultwarden#4497] [Ideas]
### Subject of the issue

ROCKET_PORT inside .env file is ignored 
possibly others - [i know there was an announcement about getting rid of websockets](https://vaultwarden.discourse.group/t/note-breaking-change-in-upcoming-v1-31-0-stable-version/3051) but I did notice that the default variable mentioned in the `.env.template` file `ENABLE_WEBSOCKET=true` does not work but `WEBSOCKET_ENABLE=true` does work.  Because it's depreciated it shouldnt matter but I figured I would mention it as well.
Others that I have changed (in the env file) and can confirm worked fine:
- DATABASE_URL
- PUSH_*
- DOMAIN
- SIGNUPS_VERIFY
- EXPERIMENTAL_CLIENT_FEATURE_FLAGS
- LOG_FILE
- ADMIN_TOKEN
- YUBICO_*
- AUTHENTICATOR_DISBALE_TIME_DRIFT
- SMTP_*
### Deployment environment
docker compose in [namespace isolated docker](https://docs.docker.com/engine/security/userns-remap/) hence needing to use a non privileged port 

* vaultwarden version:
docker hub image library:latest == 1.30.5

* Install method:
docker compose

* Clients used: 
not applicable
* Reverse proxy and version: 
not applicable
* MySQL/MariaDB or PostgreSQL version: 
not applicable
* Other relevant details:

### Steps to reproduce

docker-compose.yml
```
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwardentest
    user: "4400:4400"
    security_opt:
      - no-new-privileges:true
    volumes:
      - "./logs/vaultwarden/:/logs/"
      - "./vaultwardendata/:/data/"
    restart: always
    secrets:
      - vaultwardenconfig
    environment:
      - ENV_FILE=/run/secrets/vaultwardenconfig
      #- ROCKET_PORT=4084   # only works when set here
    hostname: vaultwarden

secrets:
  vaultwardenconfig:
    file: ./envfile
```
.envfile
```
ROCKET_PORT=4084
```
### Expected behaviour

Rocket server start on port 4084 when using `ROCKET_PORT=4084` in env file
### Actual behaviour

Rocket server still starts on port 80 unless environment variable explicitly set through docker-compose
### Troubleshooting data

`docker logs vaultwardentest`
When set in envfile
```
[2024-04-12 01:38:07.039][start][INFO] Rocket has launched from http://0.0.0.0:80
```
when set in docker-compose environment directive 
```
[2024-04-12 01:44:20.367][start][INFO] Rocket has launched from http://0.0.0.0:4084
```
