### DISCUSSION TITLE
Vaultwarden + Caddy + fail2ban bans but does not block

### DISCUSSION THREAD

**Discussion by maximilianwank** [dani-garcia/vaultwarden#4576] [Q&A] [answered]
I want to run Vaultwarden behind a Caddy reverse proxy and use fail2ban to reduce the risk of getting brute-forced.

### Setup
* Docker version 25.0.3, build 4debf41
* Docker Compose version v2.27.0
* Fail2Ban v1.1.1.dev1

### /srv/caddy/Caddyfile
```
{$DOMAIN}:443 {
  log {
    output file {$LOG_FILE} {
      roll_size 10MB
      roll_keep 10
    }
  }

  tls {$EMAIL}
  reverse_proxy /notifications/hub vaultwarden:3012
  reverse_proxy vaultwarden:80 {
    header_up X-Real-IP {remote_host}
  }
}
```

### docker-compose.yaml
```
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/vaultwarden:/data
    environment:
      DOMAIN: "https://ec2-54-93-194-58.eu-central-1.compute.amazonaws.com"
      LOG_FILE: "/data/vaultwarden.log"

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /srv/caddy/config:/config
      - /srv/caddy/data:/data
      - /srv/caddy/logs:/logs
    environment:
      DOMAIN: "https://ec2-54-93-194-58.eu-central-1.compute.amazonaws.com"
      EMAIL: "myvalidemail@example.com"
      LOG_FILE: /srv/caddy/logs/access.log
```

### /etc/fail2ban/filter.d/vaultwarden.local
```
[INCLUDES]
before = common.conf

[Definition]
failregex = ^.*Username or password is incorrect\. Try again\. IP: <ADDR>\. Username:.*$
ignoreregex =
```

### /etc/fail2ban/filter.d/vaultwarden.local
```
[vaultwarden]
enabled = true
port = 80,443,8081
filter = vaultwarden
banaction = %(banaction_allports)s
logpath = /srv/vaultwarden/vaultwarden.log
maxretry = 2
bantime = 10
findtime = 14400
chain = FORWARD
```

### Problem description
As said in the title: fail2ban bans [my public IP](https://www.whatismyip.com/). However, I can still send requests to vaultwarden, but my ssh connection drops.

### What I've tried
Change OS (Ubuntu 24.04, Amazon Linux 2023) and change all changes I could find (`FORWARD`, `DOCKER`, `DOCKER-USER`, `INPUT`, ...).

Any help is highly appreciated...
