### DISCUSSION TITLE
Unable to use Kubernetes secret mounted as rsa_key.pem

### DISCUSSION THREAD

**Discussion by gmemstr** [dani-garcia/vaultwarden#4644] [Q&A]
Been scratching my head over this one for a while. I want to run multiple instances of Vaultwarden in my cluster so that my node upgrades are a bit more seamless. The main sticking point is Vaultwarden's `rsa_key.pem` key, used for signing JWTs. This is created on startup, and *should* read an existing one

https://github.com/dani-garcia/vaultwarden/blob/9dcc738f856d818b261507376290c544bf712d47/src/auth.rs#L33-L66

I've found that when using a Kubernetes mounted secret with a private PEM, it instead just errors with `[vaultwarden][ERROR] Error creating keys, exiting...`. I'm unable to get any more logging out of it, annoyingly, regardless of log level set in environment variables.

I've pulled the relevant code out and made a minimal Rust project to try and replicate it, but I'm not able to get the same issue locally. 

<details><summary>Minimal Rust project</summary>

```rust
use openssl::rsa::Rsa;
use std::fs::File;
use std::io::Read;
use jsonwebtoken::{errors::ErrorKind, Algorithm, DecodingKey, EncodingKey, Header};

fn main() {
    let mut priv_key_buffer = Vec::with_capacity(2048);
    let mut priv_key_file =
        File::options().create(true).truncate(false).read(true).write(true).open("./foo.txt").unwrap();
    let bytes_read = priv_key_file.read_to_end(&mut priv_key_buffer).unwrap();

    let priv_key = Rsa::private_key_from_pem(&priv_key_buffer[..bytes_read]).unwrap();

    let pub_key_buffer = priv_key.public_key_to_pem().unwrap();

    let _enc = EncodingKey::from_rsa_pem(&priv_key_buffer).unwrap();
    let _dec: DecodingKey = DecodingKey::from_rsa_pem(&pub_key_buffer).unwrap();
    println!("ok");
}
```

```toml
[package]
name = "tttt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "9.3.0"
openssl = "0.10.64"
```
</details>

The PEM being used is pulled directly from the container, so I don't think it's a formatting issue - indeed, I used it with the minimal reproduction code as well to no avail. So I'm a bit lost at this point.

<details><summary>Kubernetes Manifest</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      volumes:
        - name: data
          emptyDir: {}
        - name: rsa-keys
          secret:
            secretName: vaultwarden-rsa
            defaultMode: 0644
            items:
            - key: RSA_KEY.PEM
              path: rsa_key.pem
      containers:
        - name: vaultwarden
          image: docker.io/vaultwarden/server:testing
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          envFrom:
            - secretRef:
                name: vaultwarden
            - configMapRef:
                name: vaultwarden-env
          env:
            - name: LOG_LEVEL
              value: debug
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: data
              mountPath: /data
            - name: rsa-keys
              mountPath: /data
              readOnly: true
```

</details>

**Comment by BlackDex** [comment]
How do you generate the pem?
How do you load/make the file available to the container?

Technically loading it via a configmap should work just fine, you just need to make sure it has the correct rights to access the file.

**Reply by gmemstr** [reply]
I tried various PEMS, from grabbing the one Vaultwarden itself wrote to using openssl locally. No dice - I meant to include the manifest YAML I'm using in the post, which I've now added. Permission is set to 0644.

**Reply by BlackDex** [reply]
If the file is at the right location, it shouldn't create a new one, and just read the existing file.

**Reply by gmemstr** [reply]
Slightly patched `main.rs` and got the following:

```
[2024-06-15 19:54:38.323][vaultwarden][ERROR] {"ErrorModel":{"Message":"Io","Object":"error"},"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null,"Message":"Io","Object":"error","ValidationErrors":{"":["Io"]},"error":"","error_description":""}       
```

**Reply by BlackDex** [reply]
Just supplying the file via ConfigMap and a volumeMounts should be enough. Like all files in any container.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap

**Reply by gmemstr** [reply]
It should be, and that is what I'm doing, but it's not able to be read by Vaultwarden for some reason. I'm not convinced it's a Vaultwarden issue specifically but was hopeful someone else may have encountered this.

**Reply by BlackDex** [reply]
If you disable the health check and change the entrypoint to say bash or sh, and login into the container, can you check the file contents, location and rights?

**Reply by gmemstr** [reply]
They all check out, annoyingly. The contents of the file are as expected (this is with the file mounted with a subPath, but the result is nevertheless the same).

![image](https://github.com/dani-garcia/vaultwarden/assets/1878840/4a74e6c3-5892-48dc-992d-e9cd5f351bb2)

**Reply by rjclark** [reply]
I'm hitting the same problem, after updating from `1.30.5` to `1.31.0`. ConfigMap mounted in the container, 0644 permissions, files are readable, contents are correct.

Switching the container back to `1.30.5`  cleared the error and allow the startup to continue.

I've not been able to find anything in the data directory or config map that might explain this. I'm currently checking to see if somehow using ephemeral storage (`I_REALLY_WANT_VOLATILE_STORAGE`) might be contributing to this.

*edit* I also tried _not_ mounting the PEM file and letting Vaultwarden generate the file itself. :heavy_check_mark:  That worked. Then I took that file and mounted it via a ConfigMap :heavy_multiplication_x:  that failed. Puzzling.

**Reply by BlackDex** [reply]
@rjclark could you share your app/deployment K8s config? 
And which version of K8s are you running?

**Reply by BlackDex** [reply]
And @gmemstr you too maybe?

**Reply by cakallie** [reply]
I'm hitting the same Problem, after updating from `1.30.5` to `1.31.0` too. I'm also using a secret for the token.
My stack is a `k3s` with api version ´v1.30.2+k3s1´ and sealedSecrets Controller. I'm deploy with kustomize to the cluster.


<details><summary>deployment.yaml</summary>
<p>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      serviceAccountName: vaultwarden
      containers:
      - name: vaultwarden
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1201
          runAsUser: 1201
        image: vaultwarden/server:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: vaultwarden
        - secretRef:
            name: vaultwarden
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 3012
          name: websocket
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: /data
          name: data
      securityContext:
        fsGroup: 1201
        fsGroupChangePolicy: Always
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: vaultwarden
```

</p>
</details>
<details><summary>secret.yaml</summary>
<p>

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN:  <REDACTED>
    DATABASE_URL:  <REDACTED>
    SMTP_PASSWORD:  <REDACTED>
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: vaultwarden
    type: Opaque
``` 

</p>
</details> 

the Log contains only one line: `vaultwarden][ERROR] Error creating keys, exiting...`

**Reply by BlackDex** [reply]
Error creating keys might indicate that the folder isn't writeable maybe.
Ill see if i can do some testing.

**Reply by gmemstr** [reply]
This is my own manifest https://git.gmem.ca/arch/infra/src/branch/trunk/kubernetes/vaultwarden/deployment.yaml

**Reply by cakallie** [reply]
ah ok, that is a good hint for me 😄 . I have changed the owner of a rsa file in my pvc. For now the container is up and running with the version `1.31.0`.
Maybe you can hint in the log which file is the problematic file?

Thx

**Reply by rjclark** [reply]
@BlackDex  

I'm running k8s 1.29 (through [Linode](https://www.linode.com/products/kubernetes/) in case that might be different)
This is what my deployment looks like the following. I'm currently experimenting if loading from a secret or configmap makes a difference but I've not see any so far. I'm not looking to see if file ownership or permission might be the root cause.

```yaml
---
#
# Stateful set used by vaultwarden containers
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  serviceName: "vaultwarden"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:

      #
      # Storage
      #
      volumes:

        - name: vaultwarden-config
          configMap:
            name: vaultwarden
        - name: data
          emptyDir: {}

      #
      # Containers
      #
      containers:

        - name: vaultwarden
          image: vaultwarden/server:1.30.5
          # image: vaultwarden/server:1.31.0@sha256:4e28425bad4bd13568e1779f682ff7e441eca2ecd079bd77cfcba6e4eaf1b999
          # command: [ "/bin/sh", "-c", "touch /data/x ; ls -l data" ]
          imagePullPolicy: Always

          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"

          env:
            - name: TZ
              value: "America/Toronto"
            - name: I_REALLY_WANT_VOLATILE_STORAGE
              value: "true"

          ports:
            - containerPort: 80
              protocol: TCP

          volumeMounts:
            - name: data
              mountPath: /data

            # Mount configmap files individually so that I can keep the directory read/write
            - name: vaultwarden-config
              mountPath: /data/config.json
              subPath: config.json
              readOnly: true
            - name: vaultwarden-config
              mountPath: /data/rsa_key.pem
              subPath: rsa_key.pem
            - name: vaultwarden-config
              mountPath: /data/rsa_key.pub.pem
              subPath: rsa_key.pub.pem

```

**Reply by rjclark** [reply]
Hmmm. My knowledge of Rust is, well, rusty. However, I did find one key point

1. If I mount the `/data/rsa_key.pem` from a ConfigMap or Secret (and this make it implicitly *read-only*, startup of `1.31.0` fails
2. If I instead _copy_ the file to `/data/rsa_key.pem` using a custom  `/etc/vaultwarden.sh`, startup of `1.31.0` is successful.

I can only assume that the code is expecting the file to be writable, even if it already exists and can be used as-is. I don't know Rust well enough to review the code in question though.

**Reply by BlackDex** [reply]
This is helpful, i might be able to reproduce without running K(3|8)s.

**Reply by gmemstr** [reply]
@rjclark Good call on the file copy, my setup currently has an initContainer that copies the file over. But it would be much more convienient to bet able to mount it directly

**Comment by BlackDex** [comment]
Should be fixed when using the `testing` build (done in a about an hour from now)

**Reply by gmemstr** [reply]
Can confirm it works with the following manifest:

<details><summary>Vaultwarden Kubernetes deployment</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      volumes:
        - name: data-dir
          emptyDir: {}
        - name: rsa-key
          secret:
            secretName: vaultwarden-keys
      containers:
        - name: vaultwarden
          image: vaultwarden/server:testing
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
            requests:
              memory: "32Mi"
          envFrom:
            - secretRef:
                name: vaultwarden
            - secretRef:
                name: postgres-vaultwarden
            - configMapRef:
                name: vaultwarden
          env:
            - name: LOG_LEVEL
              value: debug
            - name: ROCKET_ADDRESS
              value: "::"
            - name: RSA_KEY_FILENAME
              value: /keys/rsa_key
          ports:
            - containerPort: 80
              name: web
          livenessProbe:
            httpGet:
              path: /alive
              port: 80
            failureThreshold: 1
            initialDelaySeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /alive
              port: 80
            failureThreshold: 1
            initialDelaySeconds: 2
            periodSeconds: 10
          volumeMounts:
            - name: rsa-key
              mountPath: /keys
```
</details>
