### DISCUSSION TITLE
database postgres ssl connection error on alpine image (works fine on debian image)

### DISCUSSION THREAD

**Discussion by bonjour-py** [dani-garcia/vaultwarden#4808] [Q&A] [answered]
### Subject of the issue

ssl connection to database posgres error on alpine image (but works fine on debian image) 

### Deployment environment

* vaultwarden version:
Version 1.31.0

* Install method:
Docker image
* Clients used: 
--
* Reverse proxy and version: 
--
* MySQL/MariaDB or PostgreSQL version: 
PostgreSQL 16.3 on x86_64-pc-linux-musl in container behind taefik.
taefik manages postgresql ssl cert 
* Other relevant details:

### Steps to reproduce

use postgresql with ssl

### Actual behaviour

it logs 
```
[2024-07-30 10:16:53.507][vaultwarden::util][WARN] Can't connect to database, retrying: DieselCon.
[CAUSE] BadConnection(
    "SSL SYSCALL error: No error information\nexpected authentication request from server, but received H\n",
)
```

### Troubleshooting data

debian image works good

**Comment by BlackDex** [comment]
It works just fine for me.

I use something like this for testing: `postgresql://vw:vw1234@127.0.0.1:5432/vw?sslmode=require`
And I tested this using PostgreSQL v15 and v16 using both `testing` and `latest` container tags.

Check all the URL parameters you can use for PostgreSQL here: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-PARAMKEYWORDS

**Reply by BlackDex** [reply]
Also, you mention it is behind a traefik load-balancer, i would start checking there if it that configuration is valid and working.

**Reply by bonjour-py** [reply]
`alpine` container tag has this issue, while Debian is available normally. 
when use `sslmode=require` , log just shows `SSL SYSCALL error: No error information` . so `expected authentication request from server, but received H` is a good normal behaviour that use no-ssl connect ssl-only postgresql.

seems here is something wrong about  ssl lib of alpine.

**Reply by BlackDex** [reply]
I tested it with the alpine container, both Vaultwarden and PostgreSQL.

**Reply by BlackDex** [reply]
I used the following commands:
```bash
docker run --rm -it \
  -e DISABLE_ADMIN_TOKEN=true \
  -e I_REALLY_WANT_VOLATILE_STORAGE=true \
  -e LOG_LEVEL=debug \
  -e ROCKET_PORT=8080 \
  -e DATABASE_URL="postgresql://vw:vw1234@127.0.0.1:5432/vw?sslmode=require" \
  --network=host \
  vaultwarden/server:latest-alpine
```

and

```bash
docker run --rm -it \
  -e DISABLE_ADMIN_TOKEN=true \
  -e I_REALLY_WANT_VOLATILE_STORAGE=true \
  -e LOG_LEVEL=debug \
  -e ROCKET_PORT=8080 \
  -e DATABASE_URL="postgresql://vw:vw1234@127.0.0.1:5432/vw?sslmode=require" \
  --network=host \
  vaultwarden/server:testing-alpine
```

And the PostgreSQL i used was done via a docker-compose:
```yaml
services:
  pg:
    image: postgres:16-alpine3.20
    network_mode: host
    restart: no
    shm_size: 128mb
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
      - ./postgres/server.crt:/var/lib/postgresql/server.crt:ro
      - ./postgres/server.key:/var/lib/postgresql/server.key:ro
    environment:
      - POSTGRES_DB=vw
      - POSTGRES_USER=vw
      - POSTGRES_PASSWORD=vw1234
    command: -l -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
```

**Reply by bonjour-py** [reply]
I GOT IT !!
there is some difference between alpine and debian.
and the core was that I have a `HostSNI` select rule. 

The reproducing steps need to run a traefik. I will leave here two public database (a good and a bad) for you to test.
```
  routers:
    database: 
      entryPoints: database
      tls:
        certResolver: default
      rule: HostSNI(`database.bonjour.zone`) || HostSNIRegexp(`^.*$`)
      service: database
    database2: 
      entryPoints: database2
      tls:
        certResolver: default
      rule: HostSNI(`database.bonjour.zone`)
      service: database
```
database accept all HostSNI, it works fine .
`postgresql://vw:vw1234@database.bonjour.zone:5432/vw?sslmode=require`

database2 accept just HostSNI `database.bonjour.zone`,  cannot connected by alpine.  
`postgresql://vw:vw1234@database.bonjour.zone:39999/vw?sslmode=require`
