### DISCUSSION TITLE
Socket hang up

### DISCUSSION THREAD

**Discussion by DaveSH12** [dani-garcia/vaultwarden#4825] [Q&A]
Hey Community,
I have a big problem. We want to autoconfirm new Users and I tried to connect via BW CLI from a Debian Server.
Login successfull and getting organization ID and memer ID, too. 
But trying confirm Member is getting an error:

`request to https://lbavita004.fhhnet.stadt.hamburg.de/api/users/2eecf1a6-ff1e-43a6-b924-e46335495b49/public-key fai                                           led, reason: socket hang up`

I tried to set http connection keep alive, no_proxy for my Host.
Vaultwarden is self hosted and it's installed at the same Server.

I hope somebody her can help me, because I'm working on this issue since one week and I can not solve it.

![hc_164](https://github.com/user-attachments/assets/b0475407-b73a-4ca9-8593-96711dd48469)

Thank you very much,
Kind regards,
David

**Comment by BlackDex** [comment]
It could be multiple items of course. All steps in between the CLI and the server can cause an issue of course.
Reverse Proxy, Switches, even the network card or drivers of the host it self. Or or system tweakable settings.

Try to set `export BITWARDENCLI_DEBUG=true` before you start the CLI and see if that provides more information.
Also check the reverse proxy logs or try to increase the log-level there to get more details.

**Reply by BlackDex** [reply]
Also, make sure you are using at least HTTP1.1 and not something lower.

**Comment by DaveSH12** [comment]
Hi BlackDex, 
thanks for your fast reply.
I tried configuring nginx but it's still not working. Access to Web Interface of Vaultwarden is working find. Syncing Users with AD via BWDC CLI is working, too. 

Maybe there is an issue in our docker-compose file or in our nginx conf???

```yaml
version: '3'

networks:
 main:
    ipam:
      config:
       - subnet: 172.25.0.0/24

services:
  vaultwarden:
 restart: always
    container_name: vaultwarden
    image: vaultwarden/server:latest
    ports:
      - 443:80
    volumes:
      - /data/vaultwarden:/data/
      - /homes/MGMT/jant/vaultwarden/etc/vaultwarden.d:/etc/vaultwarden.d
      - /homes/MGMT/jant/testserver.pem:/ssl/cert.pem:ro
      - /homes/MGMT/jant/chain.pem:/ssl/chain.pem:ro
      - /homes/MGMT/jant/privkey.pem:/ssl/key.pem:ro
      - /var/log/vaultwarden.log:/var/log/vaultwarden.log

    environment:
      - ROCKET_TLS={certs="/ssl/cert.pem",key="/ssl/key.pem",chain="/ssl/chain.pem"}
      - ROCKET_TIMEOUT=60
      - SMTP_HOST=smtp.mgmt.XXX.org
      - SMTP_FROM=vaultwarden@testserver.de
      - SMTP_FROM_NAME=Testserver Vaultwarden
      - SMTP_SECURITY=off
      - SMTP_PORT=25
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=https://testserver.testde
      - INVITATION_ORG_NAME=Test
      - INVITATIONS_ALLOWED=true
      - ADMIN_TOKEN=111111111111111111111
      - SIGNUPS_ALLOWED=false
      - EMERGENCY_ACCESS_ALLOWED=false
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - ORG_GROUPS_ENABLED=true
      - ORG_EVENTS_ENABLED=true
      - ORG_CREATION_USERS=testserver@test.de
      - EXTENDED_LOGGING=true
      - LOG_TIMESTAMP_FORMAT="%d.%m.%Y %H:%M:%S.%3f"
      - LOG_LEVEL=debug
      #- USE_SYSLOG=true
      - LOG_FILE=/var/log/vaultwarden.log
      #- LOG_LEVEL=info
      - PASSWORD_HINTS_ALLOWED=false
      - USER_ATTACHMENT_LIMIT=50000
      - USER_SEND_LIMIT=50000
      - TRASH_AUTO_DELETE_DAYS=90
      - INVITATION_EXPIRATION_HOURS=240
      - EMAIL_CHANGE_ALLOWED=false
      - TEMPLATES_FOLDER=data/templates
      - RELOAD_TEMPLATES=true
      - EXPERIMENTAL_CLIENT_FEATURE_FLAGS=autofill-overlay,autofill-v2
      - TZ=Europe/Berlin

    networks:
      main:
        ipv4_address: 172.25.0.6
```

nginx config, not a Docker Container:

```nginx
user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;

	##
	# Gzip Settings
	##

	gzip on;

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

# The `upstream` directives ensure that you have a http/1.1 connection
# This enables the keepalive option and better performance
#
# Define the server IP and ports here.
upstream vaultwarden-default {
  zone vaultwarden-default 64k;
  server testserver.test.de:443;
  keepalive 2;
}

# Needed to support websocket connections
# See: https://nginx.org/en/docs/http/websocket.html
# Instead of "close" as stated in the above link we send an empty value.
# Else all keepalive connections will not work.
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      "";
}

# Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name testserver.test.de;

    if ($host = testserver.test.de) {
        return 301 https://$host$request_uri;
    }
    return 404;
}

server {
    # For older versions of nginx appened http2 to the listen line after ssl and remove `http2 on`
    listen 443 ssl http2;
    listen [::]:443 ssl;
    #http2 on;
    server_name testserver.test.de;

    # Specify SSL Config when needed
    ssl_certificate /homes/jant/testserver.pem;
    ssl_certificate_key /homes/jant/privkey.pem;
    ssl_trusted_certificate /homes/jant/chain.pem;

    client_max_body_size 525M;

    location / {
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_pass http://vaultwarden-default;
    }
```

I tried login BW with debug, but it wasn't helpful.
It is nessecary to use a reverse proxy, when vaultwarden and all scripts are running on the same Debian Server?
Sorry, I'm not a linux pro :-(

Thanks,
David

**Reply by BlackDex** [reply]
The first thing i notice is that you configured Vaultwarden to use certificates, which then implicate it should be HTTPS.
In your nginx config you configured the `proxy_pass` to be `http://` this could very well cause issues.

Either only offload the SSL on the nginx side and proxy internally via http, so, remove the `ROCKET_TLS` setting.
Or
Depending on if the certificate you use on the Vaultwarden side is a fully valid certificate or a self-signed one, you can update the `proxy_pass` to this.

```nginx
# Valid cert trusted by browsers and nginx
proxy_pass https://vaultwarden-default;
proxy_ssl_verify on;

# OR
# Self-Signed cert, not trusted by browsers or nginx by default
proxy_pass https://vaultwarden-default;
proxy_ssl_verify off;
```

**Reply by DaveSH12** [reply]
Thanks again,
when removing ROCKET_TLS Setting the Website is not working anymore:

> ERR_SSL_PROTOCOL_ERROR

I tried your second idea and Website is working, but issue is not solved:
Vaultwarden Log when trying to Confirm User via CLI:

>["08.08.2024 16:47:54.558"][response][INFO] (login) POST /identity/connect/token => 200 OK
["08.08.2024 16:47:54.559"][rustls::common_state][DEBUG] Sending warning alert CloseNotify
["08.08.2024 16:47:54.564"][rustls::server::hs][DEBUG] decided upon suite TLS13_AES_256_GCM_SHA384
["08.08.2024 16:47:54.565"][request][INFO] GET /api/sync?excludeDomains=true
["08.08.2024 16:47:54.606"][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
["08.08.2024 16:47:54.608"][rustls::common_state][DEBUG] Sending warning alert CloseNotify
["08.08.2024 16:47:56.417"][rustls::server::hs][DEBUG] decided upon suite TLS13_AES_256_GCM_SHA384
["08.08.2024 16:47:56.423"][request][INFO] POST /api/accounts/verify-password
["08.08.2024 16:47:56.669"][response][INFO] (verify_password) POST /api/accounts/verify-password => 200 OK
["08.08.2024 16:47:56.669"][rustls::common_state][DEBUG] Sending warning alert CloseNotify
["08.08.2024 16:48:01.289"][rustls::server::hs][DEBUG] decided upon suite TLS13_AES_256_GCM_SHA384
["08.08.2024 16:48:01.296"][request][INFO] GET /api/organizations/ea4ec164-d604-4e28-81c7-9758cbca5ff6/users?
["08.08.2024 16:48:01.298"][response][INFO] (get_org_users) GET /api/organizations/<org_id>/users?<data..> => 200 OK
["08.08.2024 16:48:01.301"][rustls::common_state][DEBUG] Sending warning alert CloseNotify
["08.08.2024 16:48:03.540"][rustls::server::hs][DEBUG] decided upon suite TLS13_AES_256_GCM_SHA384
["08.08.2024 16:48:03.546"][request][INFO] GET /api/organizations/ea4ec164-d604-4e28-81c7-9758cbca5ff6/users/914486ab-d7b0-4680-b95f-8005058747a1?
["08.08.2024 16:48:03.548"][response][INFO] (get_user) GET /api/organizations/<org_id>/users/<org_user_id>?<data..> => 200 OK
["08.08.2024 16:48:03.548"][rustls::common_state][DEBUG] Sending warning alert CloseNotify

NGINX Access Log is empty, but in error log in found this: 
>2024/08/08 16:37:43 [emerg] 597636#597636: bind() to 0.0.0.0:443 failed (98: Address already in use)
2024/08/08 16:37:43 [emerg] 597636#597636: still could not bind()

lsof told me this:
>COMMAND      PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
docker-pr 714073 root    4u  IPv4 2652141      0t0  TCP *:https (LISTEN)

I changed my docker-compose configfile to:
ports:
- 8080:80

and I removed ROCKET_TLS.

After restarting Docker and NGINX the Website is not reachable.

Why nginx is not listening and not forwarding the requests to Vaultwarden anymore?

How can I solve this problem? It seems that at the moment my nginx is not working.

Kind regards,
David

**Reply by BlackDex** [reply]
Well, if  you remove `ROCKET_TLS` then you also need to update your port number in the nginx config.
Or better yet, remove it if the port number is 80, else add the port number you configured for the Vaultwarden pod of course.

So, verify on which port the Vaultwarden container/pod is reachable, `docker ps` should show this.
But looking at your code you configured to have port 443 to be mapped to port 80.
Default, Vaultwarden runs on port 8080, so, if you keep the default, and configure the `docker-compose.yaml` like this.
```yaml
    image: vaultwarden/server:latest
    ports:
      - 8080:8080
    volumes:
```

Then the nginx config should be this
```nginx
upstream vaultwarden-default {
  zone vaultwarden-default 64k;
  server testserver.test.de:8080;
  keepalive 2;
}
```

But i do not know your infrastructure and how they are all connected and firewall stuff etc...
Just make sure your nginx host can connect to the Vaultwarden host on the correct port.
