### DISCUSSION TITLE
Running in Docker as non-root user

### DISCUSSION THREAD

**Discussion by rickyelopez** [dani-garcia/vaultwarden#4893] [Show and tell]
Just an FYI in case anybody else is looking for how to run Vaultwarden in docker/docker-compose as a user other than root.

The only thing preventing this container from running as non-root out-of-the-box is that Rocket is running on port 80 inside the container, which is a priviledged port. I was able to easily modify this behavior by setting the `ROCKET_PORT` environment variable to a port greater than `1024` (I chose 8080).

In docker-compose:
```yaml
environment:
  <other environment variables>
  ROCKET_PORT: 8080 # some port greater than 1024
```

Maybe this should be exposed as a vaultwarden environment variable instead of having to muck around with Rocket? Either way, seems like this might be worth adding to the documentation.

Loving this project, it's been working wonderfully for me!
