### DISCUSSION TITLE
ROCKET_TLS + traefik TLS

### DISCUSSION THREAD

**Discussion by DaCHack** [dani-garcia/vaultwarden#5128] [Q&A]
I am trying to keep the embedded encryption of the Rocket server of Vaultwarden while adding traefik as a reverse proxy to reduce the number of open ports and avoid needing to use the port on all clients. traefik creates an own entrypoint with a certificate on the same domain though. My assumption was that vaultwarden does not see anything what is happening between traefik and the client and only considers traefik a client working with its certificate.

But when trying to access Vaultwarden through traefik I receive the following error in the Vaultwarden logs and I receive a server error in the browser:
`[rocket_http::tls::listener][WARN] tls handshake with X.X.X.X:59756 failed: received fatal alert: BadCertificate`

Any idea what I am doing wrong in the configuration?

vaultwarden compose:
```
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: "vaultwarden"
    restart: unless-stopped
    environment:
      ROCKET_TLS: '{certs="/ssl/XXXXXX.pem",key="/ssl/XXXXX.key"}'
      ADMIN_TOKEN: 'XXXXXXX'
    volumes:
      - /opt/appdata/acme-lego-cron/certificates:/ssl/
      - /opt/appdata/vaultwarden:/data/
    ports:
      - 8001:80/tcp
    healthcheck:
      disable: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`test.test.com`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls=true"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.http.services.vaultwarden.loadbalancer.server.scheme=https"
```
