### DISCUSSION TITLE
Admin Page not accessible despite ADMIN_TOKEN

### DISCUSSION THREAD

**Discussion by BlackJoker90** [dani-garcia/vaultwarden#5205] [Q&A]
I am unable to access the admin page of Vaultwarden, even though I have configured the ADMIN_TOKEN in my Docker Compose file. Below is the relevant configuration for reference:

```
services:
  db:
    image: postgres:16
    container_name: Vaultwarden-DB
    hostname: vaultwarden-db
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "vaultwarden", "-U", "vaultwardenuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/vaultwarden/db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: vaultwarden
      POSTGRES_USER: vaultwardenuser
      POSTGRES_PASSWORD: xxx
    restart: on-failure:5

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: Vaultwarden
    hostname: vaultwarden
    mem_limit: 512m
    mem_reservation: 256m
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    ports:
      - 4080:4020
    volumes:
      - /volume1/docker/vaultwarden/data:/data:rw
    environment:
      ROCKET_PORT: 4020
      DATABASE_URL: postgresql://vaultwardenuser:vaultwardenpass@vaultwarden-db:5432/vaultwarden
      ADMIN_TOKEN: xxx
      DISABLE_ADMIN_TOKEN: false
      DOMAIN: https://vaultwarden.xxx
      SMTP_HOST: xxx
      SMTP_FROM: xxx
      SMTP_PORT: 587
      SMTP_SECURITY: starttls
      SMTP_USERNAME: xxx
      SMTP_PASSWORD: xxx
    restart: on-failure:5
    depends_on:
      db:
        condition: service_started
```
