### DISCUSSION TITLE
Docker Compose / Nginx Proxy Manager 504 Gateway Time-out

### DISCUSSION THREAD

**Discussion by therealsatera** [dani-garcia/vaultwarden#5277] [Q&A]
Hello everyone,

as many people before, i can't access vaultwarden via internet and reverse proxy. I googles this so many times so figure out my problem.

So i decided today to search for help here. My router is exposed to the internet via dyndns and open Ports 80 and 443.
i have one ubuntu server running with docker and some services statet over docker-compose. I will call it docker-host

Port 80 and 443 redirects to this docker-host. I started vaultwarden with compose and the following compose file:

```
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: https://my.dyn.dns 
      SIGNUPS_ALLOWED: "true" 
    volumes:
      - ./vw-data:/data
    ports:
      - 11001:80 
networks: {}
```

my nginx proxy manager (npm) runs with following:

```
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80 
      - 443:443
      - 81:81 

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
networks: {}
```

i created an proxy host for my vaultwarden like:
- Domain Names: vw.my.dyn.dns
- Scheme: http
- Forwarded IP: ip of my docker-host
- Forwarded Ports: 11001
- Block Common Exploits is enabled
- Websocket Support is enabled
- Standard Access List

I created no custom locations (tried it before with google, but did not helped)
Got an SSL via Lets Encrpyt for my vw.my.dyn.dns domain with:
- Force SSL
- HTTP/2 Support
- HSTS Enabled

Nothing at Advanced (also tried some here with google)

I get an 504 Gateway Time-out (openresty)
Tried also with the IP from docker inspect vaultwarden
Tried both ip with http and https

connected directly via docker-host-ip:11001 works

The installation guide only referse to caddy or traefik or other solutions. But i want to use npm
Any suggestions? 

best regards

![image](https://github.com/user-attachments/assets/47b0b6a5-5129-423b-b242-e3a381108b35)
![image](https://github.com/user-attachments/assets/03dec828-802b-4698-826d-b827a456f19a)

**Comment by therealsatera** [comment]
Got the answere with ChatGPT :) 

**Created a Network**
`docker network create my-bridge-network
`

**changed my vaultwarden like this (with network parts)**
```
version: '3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - WEBSOCKET_ENABLED=true
    volumes:
      - ./vw-data:/data
    ports:
      - 8080:80
    networks:
      - my-bridge-network
    restart: unless-stopped
networks:
  my-bridge-network:
    external: true
```

**and change my nginx like this (networkparts)**

```
version: '3'
services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - my-bridge-network
networks:
  my-bridge-network:
    external: true
```
