### DISCUSSION TITLE
How to enable admin token with vaultwarden hash?

### DISCUSSION THREAD

**Discussion by mobeicanyue** [dani-garcia/vaultwarden#5407] [Q&A] [answered]
I using this command to generate hash
```
echo -n "MySecretPassword" | argon2 "$(openssl rand -base64 32)" -e -id -k 65540 -t 3 -p 4'
```

and use single quotes in .env file
`VAULTWARDEN_ADMIN_TOKEN='$argon2id$v=19$m=65540,t=3,p=4$MmeK.....'`

But when I try to login admin page, The password ```MySecretPassword``` isn't work.

**Comment by stefan0xC** [comment]
> `VAULTWARDEN_ADMIN_TOKEN`

The configuration option is just called `ADMIN_TOKEN`. Cf. 
https://github.com/dani-garcia/vaultwarden/blob/29f2b433f01851ef007e893b6e4f7500b4f987de/.env.template#L391

**Reply by mobeicanyue** [reply]
> > `VAULTWARDEN_ADMIN_TOKEN`
> 
> The configuration option is just called `ADMIN_TOKEN`. Cf.
> 
> https://github.com/dani-garcia/vaultwarden/blob/29f2b433f01851ef007e893b6e4f7500b4f987de/.env.template#L391

yes, that's it, I refer it in docker-compose.yml

```
services:
  vaultwarden:
    image: ghcr.io/dani-garcia/vaultwarden
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - /path/to/vaultwarden/data/:/data/
    environment:
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
```
and rebuild the image, but not working.

when the `.env` token content is
```
VAULTWARDEN_ADMIN_TOKEN=MySecretPassword
```
enter the password in admin page is working.
But this is not
```
VAULTWARDEN_ADMIN_TOKEN='$argon2id$v=19$m=65540,t=3,p=4$MmeK.....'
```
