### DISCUSSION TITLE
Can't get any SSL certificate

### DISCUSSION THREAD

**Discussion by VaultSchulze** [dani-garcia/vaultwarden#5418] [General]
Hi there,

could you please help me? I am not able to get a Let's Encrypt Certificate for my instance of Vaultwarden. But let's start at the beginning.

I am running Ubuntu 24.04.1 LTS for  Vaultwarden with docker, compose & caddy.
I want to access Vaultwarden only internally in my network. I am owner of a domain like contoso.de. Vaultwarden would be accessible by vw.contoso.de.
In the past I had used a self-signed certificate, but I learned that using it is problematic. So by connecting vw.contoso.de website is unsecure and there is no access for iPhone App or Bitwarden PC Software. So i want to integrate auto-renew Let's Encrypt certificate for subdomain.

Here are some details of my config:
DOCKER COMPOSE
```
services:
  vaultwarden:
    image: vaultwarden/server:1.32.5
    container_name: vaultwarden
    labels: #added
      caddy: vw.contoso.de
      caddy.reverse_proxy: "{{upstreams}}"
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'false'
      INVITATIONS_ALLOWED: 'false'
      SHOW_PASSWORD_HINT: 'false'
      DOMAIN: 'https://vw.contoso.de'
      SMTP_HOST: 'My.Mailserver.com'
      SMTP_FROM: 'vaultwarden@Mailserver.com'
      SMTP_PORT: '587'
      SMTP_SECURITY: 'starttls'
      SMTP_USERNAME: 'Mailuser'
      SMTP_PASSWORD: 'MailPW'
      SMTP_DEBUG: 'false'
      TZ: 'Europe/Berlin'
      LOG_FILE: '/data/vaultwarden.log'
      ADMIN_TOKEN: 'crazyToken'
      PUSH_RELAY_URI: ''
      PUSH_IDENTITY_URI: ''
      SENDS_ALLOWED: 'true'
      EMERGENCY_ACCESS_ALLOWED: 'true'
      INVITATION_ORG_NAME: 'Vaultwarden'
      IP_HEADER: 'X-Real-IP'
      LOG_TIMESTAMP_FORMAT: '%Y-%m-%d %H:%M:%S.%3f'
      ADMIN_SESSION_LIFETIME: '20'
      INCREASE_NOTE_SIZE_LIMIT: 'false'
      _ENABLE_SMTP: 'true'
      USE_SENDMAIL: 'false'
      ENABLE_EMAIL_2FA: 'False'
      EMAIL_TOKEN_SIZE: '6'
      EMAIL_EXPIRATION_TIME: '600'
      EMAIL_ATTEMPTS_LIMIT: '3'
      EMAIL_CHANGE_ALLOWED: 'false'
    volumes:
      - /container_mnt/vaultwarden/vw-data:/data
    networks:
      - vaultwarden-net

  caddy:
    image: caddy:2.8.4
    container_name: caddy
    restart: unless-stopped
    volumes:
      - /container_mnt/vaultwarden/caddy_data:/data
      - /container_mnt/vaultwarden/caddy_config:/config
      - /container_mnt/vaultwarden/Caddyfile:/etc/caddy/Caddyfile
      - /container_mnt/vaultwarden/certificates:/etc/caddy/certificates # SSL certificate and key
    ports:
      - 80:80
      - 443:443
    networks:
      - vaultwarden-net
    environment:
      DOMAIN: 'https://vw.contoso.de'
      EMAIL: 'vaultwarden@Mailserver.com'
      LOG_FILE: '/caddy_data/caddy.log'
      CADDY_INGRESS_NETWORKS: "vaultwarden-net"

networks:
  vaultwarden-net:
    driver: bridge

volumes:
  vaultwarden_data: {}
  caddy_data: {} 
```

CADDYFILE
```
vw.contoso.com {
  encode gzip
  reverse_proxy vaultwarden:80 {
      header_up X-Real-IP {remote}
      header_up X-Forwarded-For {remote}
      header_up X-Forwarded-Proto {scheme}
  }
  header {
      Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
  }
  tls /etc/caddy/certificates/fullchain.pem /etc/caddy/certificates/privkey.pem
}
```

I've already changed port of Caddyfile to 3012. This one has access via UFW. Any idea for updating certificate?
