### DISCUSSION TITLE
Customizable Text Field on Login Page

### DISCUSSION THREAD

**Discussion by alexf-dot** [dani-garcia/vaultwarden#5436] [Ideas]
I just thought this could be a great idea to clearly provide, for example, an imprint or a way to contact the admin.

**Comment by BlackDex** [comment]
This currently is not possible in an easy way.
I know this is a thing in Germany where they kinda mandate this for public servers.
While I do not think that is the case for self-hosted Vaultwarden even if they are publicly reachable since those visitors have no place in visiting that site if they do not know the admin of course.

It might be possible in some way, but i have to figure out if that is possible in a sensible way.

**Reply by stefan0xC** [reply]
Adding text should be possible with custom CSS but I'm not sure if you could add clickable links that way. E.g.
```css
/* data/templates/scss/user.vaultwarden.scss.hbs */
footer div.small::before {
  content: "This is an example disclaimer.";
  display: block;
}
```

![image](https://github.com/user-attachments/assets/ef50fb05-2791-4dbd-95df-df9ad3bd13b6)
