### DISCUSSION TITLE
logo isn't changeable anymore

### DISCUSSION THREAD

**Discussion by celevra** [dani-garcia/vaultwarden#5454] [Q&A]
### Vaultwarden Support String

Hi,

in the new 2025.1.1 Webinterface the Logo is directly in the source code as svg and with that we can't change it anymore.
before that change, it was easy as:

```
      -v /docker/vaultwarden/icon-white.png:/web-vault/images/icon-white.png \
      -v /docker/vaultwarden/icon-white.png:/web-vault/images/icon-dark.png \
      -v /docker/vaultwarden/logo-dark@2x.png:/web-vault/images/logo-dark@2x.png \
      -v /docker/vaultwarden/logo-dark@2x.png:/web-vault/images/logo-white@2x.png \
```

please implement a setting to change the logo or go back to files.
Logos have something todo with trust. We want to see that we are on the right server, with help of our logos.
It has nothing todo with licenses and copyright texts in the footer.

regards

### Vaultwarden Build Version

1.33.0

### Deployment method

Official Container Image

### Reverse Proxy

nginx

### Host/Server Operating System

Linux

### Operating System Version

ubuntu

### Clients

Web Vault

### Steps To Reproduce

4. Click on '...'
5. Etc '...'

### Expected Result

Logos should be changeable

### Actual Result

logos not changeble because they are hardcoded

### Logs

```text

```

**Comment by stefan0xC** [comment]
Well, that has been changed upstream, so this is not something we can easily revert ourselves.
If it's that important for you, you can still build the web-vault yourself to change the logo.

Or alternatively you can also write a script that replaces the SVGs when Vaultwardens starts. (This might be a bit tricky but should be possible, I think.)

**Comment by BlackDex** [comment]
Checkout https://github.com/dani-garcia/vaultwarden/wiki/Customize-Vaultwarden-CSS

It might need some changes though for the latest web-vault, but i think the icon change should work.

**Comment by stefan0xC** [comment]
> Checkout https://github.com/dani-garcia/vaultwarden/wiki/Customize-Vaultwarden-CSS
> 
> It might need some changes though for the latest web-vault, but i think the icon change should work.

Changing `app-login img.logo` to `app-root img.new-logo-themed` changes the PNG logo, but that's only visible for a split second until it gets replaced by the embedded SVG. <del>So that's not working anymore.</del>

update: Oh, but the ones below seem to work, but crudely (by not embedding the SVG the fill colors won't be dependent on the theme...)

update 2: I've updated the selectors and made it so that only the top left logos are changed.

**Reply by BlackDex** [reply]
And what happens if you also set `content: "" !important;` on the `bit-icon > svg`?

**Reply by stefan0xC** [reply]
Nothing? I mean you can't hide or override existing HTML or embedded SVG content that way as far as I know. (And for the logos in the top left we'd already set `display: none` so there won't be any content to be displayed either.)

**Reply by BlackDex** [reply]
Well, display none doesn't change the content though.
I have not checked my self at all though.

**Reply by stefan0xC** [reply]
If `display: none` is set, the content won't be rendered at all. Replacing the logos like you have suggested works though:
![image](https://github.com/user-attachments/assets/a419edf2-5aea-461d-9638-67b2178398df)
(Set to `/images/download_google_playstore.svg` in lieu of not having other images on the server):

**Reply by CSpencerLTD** [reply]
@stefan0xC if I have created an images folder in /vw-data/templates/scss/

should this work?

auth-anon-layout > main > a > bit-icon::before {
  display: block;
  content: "" !important;
  width: 175px !important;
  height: 36px !important;
  background-image: url(/images/google-play-badge-logo.svg) !important;
  background-repeat: no-repeat !important;
  background-size: contain;
}

**Reply by BlackDex** [reply]
No, you either should load those images via the web-vault images folder, or create a custom ingress for your images in your reverse proxy like `custom_images` and point to that a special directory where your reverse proxy can load those.

You should even be able to load volume/mount folder inside the images folder of the web-vault via docker and then use something like `/images/custom/my-logo.png` for example.

**Reply by CSpencerLTD** [reply]
@BlackDex  that worked however, the main vaultwarden logo is still visible
[Is]([url](![Screenshot 2025-01-28 132143](https://github.com/user-attachments/assets/42d1681a-4bf5-4779-8e4a-1f448333a5c8))) there a way to replace this with the logo on the top left?

**Reply by ecesarini** [reply]
If  it could be useful, I've been able to custom my instance using these selectors:
```css
/* LOGIN PAGE */
/* Use a custom top left logo on login and locked screen page */
auth-anon-layout > main > a > bit-icon > svg {
  display: none !important;
}
auth-anon-layout > main > a bit-icon::before {
  display: block;
  content: "" !important;
  width: 175px !important;
  height: 36px !important;
  background-image: url(../images/my_logo.svg) !important;
  background-repeat: no-repeat !important;
  background-size: contain;
}

/* Use a custom login logo on login and locked screen page */
auth-anon-layout > main > div bit-icon > svg {
  display: none !important;
}

auth-anon-layout > main > div bit-icon::before {
  display: block;
  content: "" !important;
  width: 100% !important;
  height: 4.5em !important;
  background-image: url(../images/login_logo.png) !important;
  background-repeat: no-repeat !important;
  background-size: contain;
}


/* DASHBOARD */
/* Change vw dashboard logo */
#bit-side-nav > bit-nav-logo svg {
  display: none !important;
}
#bit-side-nav > bit-nav-logo::before {
  display: block;
  content: "" !important;
  width: 100% !important;
  height: 5.5em !important;
  background-image: url(../images/my_logo.png) !important;
  background-repeat: no-repeat !important;
  background-size: contain;
  margin: 5% 0 0 10% !important;
}
```
I'll take advantage of this topic to ask a question:
Is there a simple way to hook the background color of password-manager gui? I tried some selectors but it partially works. It doesn't seem trivial to change color style homogeneously with few rules.

**Reply by Sir-IT-Papi** [reply]
@ecesarini any advice on how I can get this going. I'm a total newbie and don't know where to start to make an hbs file

edit: I just found out where to find the file now to edit it.

just mounted the image to the container and changed the images/"My imagename".png in the hbs file but nothing

**Reply by smile2008** [reply]
please read this:
https://github.com/dani-garcia/vaultwarden/wiki/Customize-Vaultwarden-CSS

**Reply by CSpencerLTD** [reply]
@smile2008 I still don't get how to change the main logo on the login page :( I've replaced the other logo's but cannot figure out how to change that one.

**Reply by nixielectra** [reply]
Hey @CSpencerLTD, I'm able to change the main logo by following @BlackDex and @ecesarini advice up there.

1 - mount the svg
`- ./images/:/web-vault/images/custom/`

2 - hbs file
```
auth-anon-layout > main > div bit-icon > svg {
  display: none !important;
}

auth-anon-layout > main > div bit-icon::before {
  display: block;
  content: "" !important;
  width: 128px !important;
  height: 128px !important;
  background-image: url(../images/custom/logo.svg) !important;
  background-repeat: no-repeat !important;
  background-size: contain;
}
```

result
![image](https://github.com/user-attachments/assets/ee7e9f96-0de8-43e5-b27f-85265bd2422c)

**Comment by celevra** [comment]
thx @all

worked for me this way:

```
/* top left login screen */
auth-anon-layout > main bit-icon > svg {
  display: none !important;
}

auth-anon-layout > main bit-icon::before {
  display: block;
  content: "" !important;
  width: 50px !important;
  height: 50px !important;
  background-image: url(../images/logo.png) !important;
  background-repeat: no-repeat !important;
  background-size: contain;
}

/* top left */
bit-nav-logo > div bit-icon > svg {
  display: none !important;
}

bit-nav-logo > div bit-icon::before {
  display: block;
  content: "" !important;
  width: 50px !important;
  height: 50px !important;
  background-image: url(../images/logo.png) !important;
  background-repeat: no-repeat !important;
  background-size: contain;
}

/* loading */
app-root img.new-logo-themed {
  width: 50px !important;
  height: 50px !important;
  content: url(../images/logo.png) !important;
}

/* login form */
auth-anon-layout > main > div > div bit-icon > svg {
  display: none !important;
}

auth-anon-layout > main > div > div bit-icon::before {
  display: block;
  content: "" !important;
  width: 128px !important;
  height: 128px !important;
  background-image: url(../images/logo.png) !important;
  background-repeat: no-repeat !important;
  background-size: contain;
}
```

**Reply by CSpencerLTD** [reply]
I've tried the above

But the logo now isn't central

![image](https://github.com/user-attachments/assets/e2931ff1-57cb-47d8-8e7e-7e8d857f3d17)


Is this because its rectangular?

How can I make it central?

**Reply by stefan0xC** [reply]
The `max-width` of the `bit-icon`'s parent `div` is set to `8rem`, so you could either keep the width to `128px` or set `margin-left` to something like `-4rem` to offset the image.

**Reply by CSpencerLTD** [reply]
@stefan0xC 

Below is my hbs file, please can you help me with correcting/setting the max-width? 😄 

/* Hide `Duo` 2FA (Fifth item of the list) */
app-two-factor-setup ul.list-group.list-group-2fa li.list-group-item:nth-child(5) {
  @extend %vw-hide;
}

/* top left */
auth-anon-layout > main bit-icon > svg {
display: none !important;
}

auth-anon-layout > main bit-icon::before {
display: block;
content: "" !important;
width: 50px !important;
height: 50px !important;
background-image: url(/images/custom/logo-colour-size.png) !important;
background-repeat: no-repeat !important;
background-size: contain;
}


/* loading */
app-root img.new-logo-themed {
width: 50px !important;
height: 50px !important;
content: url(/images/custom/logo-colour-size.png) !important;
}

/* login form */
auth-anon-layout > main > div > div bit-icon > svg {
display: none !important;
}

auth-anon-layout > main > div > div bit-icon::before {
display: block;
content: "" !important;
width: 300px !important;
height: 200px !important;
background-image: url(/images/custom/logo-colour-size.png) !important;
background-repeat: no-repeat !important;
background-size: contain;
}

**Reply by stefan0xC** [reply]
Just add
```CSS
auth-anon-layout > main > div > div.tw-max-w-28  {
    max-width: 300px !important;
}
```
