### DISCUSSION TITLE
New docker deploy on debian 12 hangs at start

### DISCUSSION THREAD

**Discussion by maxdd** [dani-garcia/vaultwarden#5549] [Q&A]
### Vaultwarden Support String

Hello,
i'm not the owner of the post on the forum [here](https://vaultwarden.discourse.group/t/vaultwarden-web-site-keeps-loading/4366) but i'm facing the exact same issue.
I had to roll back (actually not even a roll since it was fresh install) to 1.32.7 on my new debian 12 unit (booted yesterday first time)
I also have a debian 12 which is much older and started on vw 2023 and using watchtower it has updated by itself till sha256:24aa90c2424f2f6b10862ba84dc9141d09c1df2b7025f111c9b2bbc4c078894b which is the server:latest image.

I've also tried on stock port 80.
Nothing else is running on the machine

### Vaultwarden Build Version

1.33.1

### Deployment method

Official Container Image

### Custom deployment method

```
version: '3.5'
services:
  app:
    image: 'vaultwarden/server:latest'
    restart: unless-stopped
    ports:
      - '8062:80'
    volumes:
      - ./vw-data:/data:rw
    environment:
      - SIGNUPS_ALLOWED="false"
      #- LOG_FILE=/data/vaultwarden.log
      #- WEBSOCKET_ENABLED=true
```

### Reverse Proxy

none

### Host/Server Operating System

Linux

### Operating System Version

debian 12

### Clients

Browser Extension, Web Vault

### Steps To Reproduce

1. docker-compose up -d
2. browse ip:8062

### Expected Result

Web vault should load

### Actual Result

Web vault is stuck in a sort of loading state

### Logs

```
[2025-02-06 07:39:58.954][vaultwarden::auth][INFO] Private key 'data/rsa_key.pem' created correctly
[2025-02-06 07:39:59.010][start][INFO] Rocket has launched from http://0.0.0.0:80
```

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/c2509a69-e7eb-4630-9d56-741f2864c504)
