### DISCUSSION TITLE
Plugin and desktop icons aren't loading

### DISCUSSION THREAD

**Discussion by se7entynine** [dani-garcia/vaultwarden#5750] [Q&A] [answered]
### Your environment (Generated via diagnostics page)

* Vaultwarden version: v1.33.2
* Web-vault version: v2025.1.1
* OS/Arch: linux/x86_64
* Running within a container: true (Base: Debian)
* Database type: SQLite
* Database version: 3.48.0
* Environment settings overridden!: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: n/a
* Domain Configuration Check: true
* HTTPS Check: true
* Websocket Check: true
* HTTP Response Checks: false

### Config & Details (Generated via diagnostics page)

<details><summary>Show Config & Details</summary>

**Environment settings which are overridden:** SIGNUPS_ALLOWED, ADMIN_TOKEN

**Failed HTTP Checks:**

```yaml
2FA Connector calls:
Header: 'content-security-policy' is present while it should not
```

**Config:**

```json
{
  "_duo_akey": null,
  "_enable_duo": true,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_max_note_size": 10000,
  "_smtp_img_src": "***:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_connect_src": "",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://********************",
  "domain_origin": "*****://********************",
  "domain_path": "",
  "domain_set": true,
  "duo_context_purge_schedule": "30 * * * * *",
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "duo_use_iframe": false,
  "email_2fa_auto_fallback": false,
  "email_2fa_enforce_on_verified_invite": false,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "enable_websocket": true,
  "enforce_single_org_with_reset_pw_policy": false,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "experimental_client_feature_flags": "fido2-vault-credentials",
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "http_request_block_non_global_ips": true,
  "http_request_block_regex": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 20,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "increase_note_size_limit": false,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f%z",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "push_enabled": true,
  "push_identity_uri": "https://identity.bitwarden.eu",
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://api.bitwarden.eu",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": true,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "*********************",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": "***********",
  "smtp_password": "***",
  "smtp_port": 587,
  "smtp_security": "starttls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": "*********************",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "user_send_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```

</details>

### Vaultwarden Build Version

1.33.2

### Deployment method

Official Container Image

### Reverse Proxy

traefik 3.3.5

### Host/Server Operating System

Linux

### Operating System Version

Ubuntu 24.04.26

### Clients

Desktop, Browser Extension

### Client Version

Firefox 137.0, Desktop 2025.2.1

### Steps To Reproduce

1. Go to any vault entry on the browser plugin or desktop app
2. No website icon is visible 

### Expected Result

Expected result is similar to the web version:

![Image](https://github.com/user-attachments/assets/b7cb7f12-eec0-46b0-a361-e7f1e24ecda0)

Or the mobile version which is also showing icons properly. 

### Actual Result

Browser plugin: 

![Image](https://github.com/user-attachments/assets/acd5c931-f0fb-4f77-8366-36d09a9cf63a)
Desktop app:

![Image](https://github.com/user-attachments/assets/79be0bdc-08ed-4d71-b08f-9146b862aa90)

Browser plugin and desktop app are not showing any public website icons properly. 

### Logs

```text
Mostly this while loading browser or desktop app:

[request][INFO] GET /notifications/hub?access_token=eyJ0eXAiOiJKV1QiL
[vaultwarden::api::notifications][INFO] Accepting Rocket WS connection from 95.90.71.30
[response][INFO] (websockets_hub) GET /notifications/hub?<data..> => 200 OK
[request][INFO] GET /api/accounts/revision-date
[response][INFO] (revision_date) GET /api/accounts/revision-date => 200 OK
[request][INFO] GET /icons/account.rms.teltonika-networks.com/icon.png
[response][INFO] (icon_internal) GET /icons/<domain>/icon.png => 200 OK
[request][INFO] GET /icons/account.deezer.com/icon.png
[response][INFO] (icon_internal) GET /icons/<domain>/icon.png => 200 OK

Rarely this:
[vaultwarden::api::icons][WARN] Unable to download icon: Req.
[CAUSE] reqwest::Error {
    kind: Request,
    url: "https://login.REDACTED.com/favicon.ico",
    source: hyper_util::client::legacy::Error(
        Connect,
        Ssl(
            Error {
                code: ErrorCode(
                    5,
                ),
                cause: None,
            },
            X509VerifyResult {
                code: 0,
                error: "ok",
            },
        ),
    ),
}
```

### Additional Context

Traefik:
The error message regarding the content security policy didn't fix anything. The problem persists with an disable CSP header.
Header middleware:
```
    vaultwarden-header-mdw:
      headers:
        accessControlAllowMethods: ["GET", "OPTIONS", "PUT"]
        accessControlMaxAge: 100
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true 
        browserXssFilter: false 
        referrerPolicy: "same-origin" 
        contentsecuritypolicy: "default-src 'none'; font-src 'self'; manifest-src 'self'; form-action 'self'; object-src 'self' blob:; script-src 'self' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; child-src 'self' https://*.duosecurity.com https://*.duofederal.com; frame-src 'self' https://*.duosecurity.com https://*.duofederal.com; frame-ancestors 'self' chrome-extension://nngceckbapebfimnlniiiahkandclblb chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh moz-extension://*; img-src 'self' data: https://haveibeenpwned.com; connect-src 'self' https://api.pwnedpasswords.com https://api.2fa.directory https://app.simplelogin.io/api/ https://app.addy.io/api/ https://api.fastmail.com/ https://api.forwardemail.net; base-uri 'self'"
        permissionsPolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';" 
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,noindex,nofollow"
          server: ""
          Cross-Origin-Resource-Policy: "same-origin"
          Cross-Origin-Embedder-Policy: "require-corp"
          Cross-Origin-Opener-Policy: "same-origin"
```

**Comment by BlackDex** [comment, marked as answer]
The following check has failed
- HTTP Response Checks: false

```
2FA Connector calls:
Header: 'content-security-policy' is present while it should not
```

This probably then also is in effect for the icon's endpoint i think, and that is what probably is causing your issues.

I also use traefik, but I do not set any headers via traefik it self. All is done by Vaultwarden and should also be handled by Vaultwarden.

There is just one exception, that is the `STS`, that is something you need to set  your self.
But other then that, nothing should be set by any reverse proxy.

**Reply by se7entynine** [reply]
You are right! It worked with these traefik headers:
```
    vaultwarden2-header-mdw:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true     
```

So Vaultwarden sets a lot of these headers by itself, but I'm a bit curious - when I set exactly the same header by myself it still didnt work. Is it blocked in some way? Why is it working in the web view and mobile app? 
These should be the headers that are used by vaultwarden itself:
```
    vaultwarden3-header-mdw:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true 
        browserXssFilter: false 
        referrerPolicy: "same-origin" 
        contentsecuritypolicy: "default-src 'none'; font-src 'self'; manifest-src 'self'; form-action 'self'; object-src 'self' blob:; script-src 'self' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; child-src 'self' https://*.duosecurity.com https://*.duofederal.com; frame-src 'self' https://*.duosecurity.com https://*.duofederal.com; frame-ancestors 'self' chrome-extension://nngceckbapebfimnlniiiahkandclblb chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh moz-extension://*; img-src 'self' data: https://haveibeenpwned.com; connect-src 'self' https://api.pwnedpasswords.com https://api.2fa.directory https://app.simplelogin.io/api/ https://app.addy.io/api/ https://api.fastmail.com/ https://api.forwardemail.net; base-uri 'self'"
        permissionsPolicy: "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()" 
        customResponseHeaders:
          X-Robots-Tag: noindex, nofollow
          server: "Rocket"
          Cross-Origin-Resource-Policy: "same-origin"    
```
