### DISCUSSION TITLE
Keep getting timed out connection refused os 1111

### DISCUSSION THREAD

**Discussion by Dvalin21** [dani-garcia/vaultwarden#5780] [Q&A]
So I have gone through a ganbit of different solutions trying to figure this out. I use mailcow for sending and receiving email. Of course when you're using smtp its 587 that you use. I'm able to telnet mail.mydomain.com 587 and get connect and it shows ESMTP 220.  I'm able to send and receive email from mailcow with no issue. I made sure there wasn't another software trying to use port 587. I made sure that ISP wasn't blocking it (Cox Internet). I made sure that my firewall wasn't blocking it (ufw allo 587/tcp) and so on. There shouldn't be any reason for it to be not allowing for me to send a verification email to verify the initial account. I attempt using smtp with mailcow with other apps and they all work fine. Any thoughts?

```
services:
  Vaultwarden:
    image: vaultwarden/server:latest
    container_name: Vaultwarden
    hostname: vaultwarden
    security_opt:
      - no-new-privileges:true
    ports:
      - "4080:80"
    volumes:
      - vault_data:/data
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"
#      SIGNUPS_DOMAINS_WHITELIST: 
      ROCKET_PORT: "80"
      ROCKET_ADDRESS: "0.0.0.0"
      ADMIN_TOKEN: long token
      DISABLE_ADMIN_TOKEN: "false"
      DOMAIN: "https://safe.mydomain.com"
      SMTP_HOST: smtp.mydomain.com"
      SMTP_FROM: "email@mydomain.com"
      SMTP_PORT: "587"
      SMTP_SECURITY: "starttls"
      SMTP_USERNAME: "email@mydomain.com"
      SMTP_PASSWORD: 'password'
    restart: always

volumes:
  vault_data:

## Remember to run the argon2 on your local host. Make sure to add $ to each $ you find. Usually 5.
## For example echo -n 'masterpass here' | argon2 "$(openssl rand -base64 32)" -e -id -k 65540 -t 3 -p 4
```
