### DISCUSSION TITLE
ROCKET_TLS doesnt work (invalid type: found string).

### DISCUSSION THREAD

**Discussion by Frill7742** [dani-garcia/vaultwarden#5848] [General]
So I want to encrypt the HTTP traffic of Vaultwarden with a self-signed cert.. I know this isn't the recommend way, BUT it's only the encryption between the KVM (one KVM only for vaultwarden) and the reverse Proxy (Caddy) on my OPNSense.

Now I get this error:
https://privatebin.net/?3da6d12c1a3b8bc9#25Q8FddjF9yexupDAQqrZeixaAjF3UAjYRdxuAEAXhL5

This is my docker compose file:
https://privatebin.net/?1a80bd4f5f5a4ede#DQCoSEqhW8g16ZHjZSVVeA5VFUTxekaEDP9hF7NX1Mmd

I hope somebody can help me.

**Comment by BlackDex** [comment]
See the wiki, you are formatting the value in a wrong way i think. 
https://github.com/dani-garcia/vaultwarden/wiki/Enabling-HTTPS#via-rocket

**Reply by Frill7742** [reply]
I don't see any difference between the two env. var., expect that one is for the docker run command and the other for the docker compose file.
Maybe could you give me a correct one for the docker compose file or tell me what is wrong in the syntax?

**Reply by BlackDex** [reply]
You use quotes around cert and key, while those are not there in the examples.

**Reply by Frill7742** [reply]
> docker run -d --name vaultwarden \
  -e ROCKET_TLS='{certs="/ssl/certs.pem",key="/ssl/key.pem"}' \

> ROCKET_TLS={certs="/path/to/certs.pem",key="/path/to/key.pem"}

In both examples from the link you provided, the "" are around the certs. And the ' needs to be there to be able to insert a string into the docker compose environment variable.

**Reply by BlackDex** [reply]
I mean the actual strings `certs` and `key`, you have `"certs"=` while the example has `certs=`

**Reply by Frill7742** [reply]
Okay I see what you mean now. Sorry I was stupid.
ROCKET_TLS: '{certs:"/ssl/cert.pem",key:"/ssl/key.pem"}'
Now this is the correct format, but it doesn't work either.

**Reply by BlackDex** [reply]
What is the error in the log now?

**Reply by Frill7742** [reply]
If I'm not wrong, it's the same 
(latest error: https://privatebin.net/?3178fa327f73a3e4#HYqQLbLFYNu4B9PAwD9XxhFBe4Ysf1YVv1MBGP5rzYUz)

**Reply by BlackDex** [reply]
The compose env's work different, i think you need to remove the single quotes too

**Reply by Frill7742** [reply]
You mean the ' right? If so, no because if I remove them, docker wouldn't even start.

**Reply by BlackDex** [reply]
https://docs.docker.com/compose/how-tos/environment-variables/set-environment-variables/#use-the-environment-attribute

**Reply by Frill7742** [reply]
I now formatted it in the other way, same error.

```
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - DOMAIN=https://bitwarden.bwgs.eu
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - ROCKET_TLS={certs:"/ssl/cert.pem",key:"/ssl/key.pem"}
      - ROCKET_PORT=443
    volumes:
      - ./data:/data
      - ./certs:/ssl:ro
    ports:
      - '80:80'
      - '443:443'
      - '3012:3012'  # WebSocket port for real-time updates
```
