### DISCUSSION TITLE
Install Self Host with Docker and IP

### DISCUSSION THREAD

**Discussion by ElTomDev** [dani-garcia/vaultwarden#5876] [Q&A]
Is it possible to use Vaultwarden with HTTPS, but instead of using a domain, access it via the server's IP?

I've tried everything and I can't run it via IP.

First I tried to create a self-signed certificate.

```
openssl req -x509 -newkey rsa:4096 -nodes -sha256 -days 365 \
  -keyout vw_selfsigned.key -out vw_selfsigned.crt \
  -subj "/CN=192.168.10.10" \
  -addext "subjectAltName=IP:192.168.10.10"
```

Then I tried to create a Docker Compose, but it gets stuck in an infinite reload loop.

```
version: '3.7'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    ports:
      - "8086:80"     # HTTP
      - "8446:443"    # HTTPS
    volumes:
      - ./vw-data:/data
      - ./certs/vw_selfsigned.crt:/ssl/vw_selfsigned.crt:ro
      - ./certs/vw_selfsigned.key:/ssl/vw_selfsigned.key:ro
    environment:
      WEBSOCKET_ENABLED: "true"
      DOMAIN: "https://192.168.10.10:8446"
      ROCKET_TLS: '{certs="/ssl/vw_selfsigned.crt",key="/ssl/vw_selfsigned.key"}'

```
