### DISCUSSION TITLE
Problem with server on DOKER QNAP Container Station

### DISCUSSION THREAD

**Discussion by Maystero14** [dani-garcia/vaultwarden#5974] [General]
I'm trying to run a Vaultwarden server on a QNAP Container Station Docker. I've managed to create a `docker-compose.yaml `configuration

```
version: "3.8"

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    hostname: vaultwarden
    networks:
      qnet-network:
        ipv4_address: 192.168.88.99
    ports:
      - 80:80  # 
    restart: unless-stopped
    environment:
      - TZ=Europe/Warsaw
      - ADMIN_TOKEN=tajny_kod_123

    volumes:
      - vaultwarden-data:/data

networks:
  qnet-network:
    driver_opts:
      iface: eth0
    driver: qnet
    ipam:
      driver: qnet
      options:
        iface: eth0
      config:
        - subnet: 192.168.88.0/24
          gateway: 192.168.88.1

volumes:
  vaultwarden-data:
```

But serwer look like dosn't start/ Please look on the short movie:

https://github.com/user-attachments/assets/28ed8244-826e-4795-8693-5d3027828288

The "wheel" spins forever. Can anyone help?
