### ISSUE TITLE
Database error after upgrade "Table 'emergency_access' already exists"

### ISSUE THREAD

**Issue by SingingFrog7** [dani-garcia/vaultwarden#2129]
Hello,

   I have been running Vaultwarden for quite a while and did an update of my docker images yesterday. Since then, Vautlwarden doesn't want to start

Here's the error:
```
Running migration 20210830193501
Executing migration script 20210830193501/up.sql
[2021-12-03 21:18:47.733][vaultwarden::util][WARN] Can't connect to database, retrying: DieselMig.
[CAUSE] QueryError(
    DatabaseError(
        __Unknown,
        "Table 'emergency_access' already exists",
    ),
)
```

Here's my docker-compose.yml file:
```
services:
  vaultwarden:
    image: vaultwarden/server:latest
    volumes:
      - /opt/bitwarden/data/:/data/
    restart: always
    ports:
      - "3812:80"
      - "3012:3012"
    environment:
      DOMAIN: 'https://bitwarden.mydomain.com'
      WEBSOCKET_ENABLED: 'true'
      ADMIN_TOKEN: 'SOME_TOKEN'
      DATABASE_URL: 'mysql://vaultwarden:SOME_PASSWORD@db.mydomain.com/vaultwarden'
    container_name: vaultwarden
```
Nothing too wild there. I tried to find the migration script but can't find the "up.sql" file when I connect to the docker container and do a `find / -name "*up.sql"`

So I connected to MySQL and when trying to `select * from emergency_access` I got  `table vaultwarden.emergency_access doesn't exists in engine`. I dropped the table and removed the .idb files associated to it and now I have :

```
Running migration 20210830193501
vaultwarden    | Executing migration script 20210830193501/up.sql
vaultwarden    | [2021-12-03 23:34:17.660][vaultwarden::util][WARN] Can't connect to database, retrying: DieselMig.
vaultwarden    | [CAUSE] QueryError(
vaultwarden    |     DatabaseError(
vaultwarden    |         __Unknown,
vaultwarden    |         "Can't create table `vaultwarden`.`emergency_access` (errno: 150 \"Foreign key constraint is incorrectly formed\")",
vaultwarden    |     ),
vaultwarden    | )
```

I'm not sure what to do there.

If anyone can help, that would be nice!
Thanks
