### ISSUE TITLE
Mutiple Crashes - Failed to turn on WAL: DatabaseError

### ISSUE THREAD

**Issue by FireAmpersand** [dani-garcia/vaultwarden#2206]
Hi Team,

I am looking into switching from bitwarden to vaultwarden but my docker container keeps crashing with the following error. 

`[ERROR] thread 'main' panicked at 'Failed to turn on WAL: DatabaseError(__Unknown, "unable to open database file")': src/db/mod.rs:307`

I am not sure if this is the correct place as the only way to fix it is to restart the computer. Restarting docker or the container does not help. After the reboot, the app works great for i would say about 15-20 minutes before happening again. No other containers are breaking like this so not sure if Docker is the cause. 

I am running Docker Desktop on Windows on Server 2019. I start the container with the following docker-compose file. 

```
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    ports:
      - 85:80
    volumes:
      - E:\Apps\vaultwarden\vwdata\:/data
```

Windows server is up to date as well as Docker Desktop (4.3.2). Image is the most recent build. I have also reinstalled Docker Desktop with no luck.
