### ISSUE TITLE
Update to 1.25.0 database update fails

### ISSUE THREAD

**Issue by ToeiRei** [dani-garcia/vaultwarden#2521]
### Subject of the issue

Vaultwarden constantly tries to update MySQL(mariadb) using 20220302210038/up.sql 

### Deployment environment

* vaultwarden version: 1.24.0

* Install method: docker on Fedora CoreOS

* Clients used: n/a

* Reverse proxy and version: nginx

* MySQL/MariaDB or PostgreSQL version: 10.7.4-MariaDB-1:10.7.4+maria~bullseye - mariadb.org binary distribution

* Other relevant details:

```
services:
  bitwarden:
    image: vaultwarden/server:1.24.0
    restart: unless-stopped
    ports:
      - "816:80/tcp"
      - "3012:3012/tcp"
    environment:
      - DOMAIN=https://vault.domain.here
      - WEBSOCKET_ENABLED=true
      - LOG_FILE="/data/bitwarden.log"
      - INVITATIONS_ALLOWED=true
      - ADMIN_TOKEN=${BITWARDEN_ADMIN_TOKEN}
      - SMTP_HOST=${BITWARDEN_SMTP_HOST}
      - SMTP_FROM=${BITWARDEN_SMTP_FROM}
      - SMTP_PORT=${BITWARDEN_SMTP_PORT}
      - DATABASE_URL=${BITWARDEN_DATABASE_URI}
      - ENABLE_DB_WAL=false
      - SIGNUPS_ALLOWED=false
      - SMTP_SECURITY=off
    volumes:
      - type: volume
        source: bitwarden-data
        target: /data
```

### Steps to reproduce
1. have 1.24.0 running
2. pull 1.25.0
3. try to update
4. wonder why vaultwarden is still down
5. examine logs

### Expected behaviour
I would expect the diesel_schema_migration to just do its job and call it a day

### Actual behaviour
Migration is run over and over and over ... again.

### Troubleshooting data

docker logs:

```
/--------------------------------------------------------------------\
 |                        Starting Vaultwarden                        |
 |                           Version 1.25.0                           |
 |--------------------------------------------------------------------|
 | This is an *unofficial* Bitwarden implementation, DO NOT use the   |
 | official channels to report bugs/features, regardless of client.   |
 | Send usage/configuration questions or feature requests to:         |
 |   https://vaultwarden.discourse.group/                             |
 | Report suspected bugs/issues in the software itself at:            |
 |   https://github.com/dani-garcia/vaultwarden/issues/new            |
 \--------------------------------------------------------------------/

 [INFO] No .env file found.
 [WARNING] The following environment variables are being overriden by the config file,
 [WARNING] please use the admin panel to make changes to them:
 [WARNING] DOMAIN, SIGNUPS_ALLOWED, INVITATIONS_ALLOWED, ADMIN_TOKEN, SMTP_HOST, SMTP_PORT, SMTP_FROM
 Running migration 20220302210038
 Executing migration script 20220302210038/up.sql
 Running migration 20220302210038
 Executing migration script 20220302210038/up.sql
 Running migration 20220302210038
 Executing migration script 20220302210038/up.sql
 Running migration 20220302210038
 Executing migration script 20220302210038/up.sql
 Running migration 20220302210038
 Executing migration script 20220302210038/up.sql
 Running migration 20220302210038
 Executing migration script 20220302210038/up.sql
```
