### ISSUE TITLE
Docker container v1.25.1 persistent check with volumes fails to start

### ISSUE THREAD

**Issue by aclare92** [dani-garcia/vaultwarden#2622]
### Subject of the issue
On starting of the latest (1.25.1) version, it will error stating there is no .env and no persistent storage although configured and working in 1.25.0

### Deployment environment

* vaultwarden version: 1.25.1

* Install method: Docker

* Clients used: Application doesn't start at all so presume all clients

* Reverse proxy and version: N/A

* MySQL/MariaDB or PostgreSQL version: N/A

* Other relevant details:

### Steps to reproduce

Run the below docker compose; (I have every variable populated but removed for this issue raise)
```yaml
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - 50003:80
    networks:
      - proxy
    volumes:
      - vaultwarden_data:/data
    environment:
      - ADMIN_TOKEN=
      - WEBSOCKET_ENABLED=true
      - SMTP_HOST=
      - SMTP_FROM=
      - SMTP_FROM_NAME=VaultWarden
      - SMTP_SECURITY=starttls
      - SMTP_PORT=587
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_TIMEOUT=30
      - SMTP_AUTH_MECHANISM="Plain"
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - DOMAIN=
      - INVITATION_ORG_NAME=
      - INVITATIONS_ALLOWED=true
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_DOMAINS_WHITELIST=
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=6
      - EMERGENCY_ACCESS_ALLOWED=true
      - SENDS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
```

### Expected behaviour

To launch the application and be accessible via it's port or the remapped port if provided i.e. 50003:80 in this case

### Actual behaviour

Application does not start and reviewing the logs, the below is returned;

```
[INFO] No .env file found.
[2022-07-17 04:21:50.752][vaultwarden][ERROR] No persistent volume!
########################################################################################
# It looks like you did not configure a persistent volume!                             #
# This will result in permanent data loss when the container is removed or updated!    #
# If you really want to use volatile storage set `I_REALLY_WANT_VOLATILE_STORAGE=true` #
########################################################################################
```

**Comment by shadoskill** [comment]
Yeah I am experiencing the same issue.

**Comment by BlackDex** [comment]
Which version of docker/docker-compose are you using?
And is the volume a docker volume, or a directory on the host?

**Comment by shadoskill** [comment]
Docker: 20.10.17
Unlike the OP I did not use compose, I just ran commands manually.
docker volume create vaultwarden_data
docker run -d --name vaultwarden -v vaultwarden_data:/data/ -p 20000:80 vaultwarden/server:latest


docker volume inspect vaultwarden_data
`
[
    {
        "CreatedAt": "2022-07-17T07:44:17-05:00",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/vaultwarden_data/_data",
        "Name": "vaultwarden_data",
        "Options": {},
        "Scope": "local"
    }
]
`

And then I see the same error in my logs.

**Comment by BlackDex** [comment]
Looks like this happens when using a `volume` and not a `bind mount` from the host.
For now i suggest to add `I_REALLY_WANT_VOLATILE_STORAGE=true` to the environment config.
That should at least make the latest version work without issues.

**Comment by BlackDex** [comment]
I'm looking into a way to still being able to detect this in a different way.
I have to do some checking but maybe there is an option.

**Comment by teward** [comment]
NOTE: This is a quick workaround to solve this, and it'll be recognized as persistent storage by the container.  It maps 'persistent data' onto your disk.  Which is, in fact, the same thing that the main Bitwarden docker instances want you to do for the same reasons.


Create a local directory for your vaultwarden data in the same directory as your docker-compose file.  Then map it in volumes with `./data:/data` or similar.

What you've done is created an ephemeral volume in Docker's storage that can be deleted by Docker with the right deletion arguments to `docker compose down`.  Using a local directory as a bind-mount inside the Docker container means that Docker can delete the volume, but not the underlying data.

So your volumes should look like this under the container:

```yaml
services:
  vaultwarden:
    ...
    volumes:
      - './vaultwarden_data:/data
    ...
```

... where `vaultwarden_data` is a directory in your local dir where you have your docker compose file.
