### ISSUE TITLE
Attachments option completely missing

### ISSUE THREAD

**Issue by oregonpillow** [dani-garcia/vaultwarden#2648]
### Subject of the issue
Using the latest docker image, i cannot see the attachments option when i click on an item to edit. For all clients i use.

### Deployment environment
```
version: '3.3'
services:
    server:
        container_name: bitwarden
        network_mode: lsio
        volumes:
            - './data:/data/'
        ports:
            - '8121:80'
        image: 'vaultwarden/server:latest'
        environment:
            WEBSOCKET_ENABLED: "true"
        restart: unless-stopped
```

### Steps to reproduce
I can rebuild the container from scratch and the problem persists. I tried changing the default owner of attachments folder from the default `root:root` to `<my username>: users` but it did not help.

### Expected behaviour
Attachment option is available on all clients

### Actual behaviour
Attachment option is not available on any clients i use (web + iphone)

### Troubleshooting data
data folder:
```
drwxr-xr-x 2 <redacted> users 4.0K May 24 07:01 attachments
-rw-r--r-- 1 <redacted> users 588K Jul 27 11:38 db.sqlite3
-rw-r--r-- 1 <redacted> users  32K Jul 27 11:38 db.sqlite3-shm
-rw-r--r-- 1 <redacted> users  17K Jul 27 11:38 db.sqlite3-wal
drwxr-xr-x 2 <redacted> users  12K Jul 27 11:18 icon_cache
-rw-r--r-- 1 <redacted> users 1.7K Jan 19  2022 rsa_key.pem
-rw-r--r-- 1 <redacted> users  451 Jan 19  2022 rsa_key.pub.pem
drwxr-xr-x 2 root   root  4.0K May 24 07:01 sends
drwxr-xr-x 2 root   root  4.0K May 24 07:01 tmp
```

![Screenshot 2022-07-27 at 11 47 32](https://user-images.githubusercontent.com/53374403/181217633-2eab5482-2e7c-4f8b-a5a8-fec1b543fd32.png)

thanks for any help or suggestions! Love the project!
