### ISSUE TITLE
Vaultwarden Subdomain get blank page - Treaefik

### ISSUE THREAD

**Issue by MrDuartePT** [dani-garcia/vaultwarden#2660]
When i use my reverse proxy to route bitwarden to a subdomain i get a blank page saying Bitwarden on top.

Docker compose.yaml
```
version: "2.1"
services:
   vaultwarden:
    image: vaultwarden/server
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - ROCKET_PORT=7780
      - DOMAIN=https://domain.tk/bitwarden/
      - WEBSOCKET_ENABLED=true

    volumes:
      - /home/mrduarte/dockers/vaultwarden/vw-data/:/data/
    ports:
      - 7780:7780
      - 3012:3012
      
    labels:  
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.rule=Host(`domain.tk`) && Path(`/bitwarden`)"
      - "traefik.http.routers.bitwarden.middlewares=bitwarden-stripprefix"
      - "traefik.http.middlewares.bitwarden-stripprefix.stripprefix.prefixes=/bitwarden/"
      - "traefik.http.routers.bitwarden.entrypoints=websecure"
      - "traefik.http.routers.bitwarden.tls=true"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=7780"
      - "traefik.http.routers.bitwarden.service=bitwarden"      
      - "traefik.http.routers.bitwarden_websocket-secure.entrypoints=websecure"
      - "traefik.http.routers.bitwarden_websocket-secure.rule=Host(`domain.tk`) && Path(`/bitwarden/notifications/hub`)"
      - "traefik.http.routers.bitwarden_websocket-secure.tls=true"
      - "traefik.http.routers.bitwarden_websocket-secure.service=bitwarden_websocket"
      - "traefik.http.services.bitwarden_websocket.loadbalancer.server.port=3012"
      - "traefik.docker.network=proxy"


networks:
  proxy:
    external: true
```

config.json
```
"domain": "https://domain.tk/bitwarden",
  "sends_allowed": true,
  "incomplete_2fa_time_limit": 3,
  "disable_icon_download": false,
  "signups_allowed": true,
  "signups_verify": true,
  "signups_verify_resend_time": 3600,
  "signups_verify_resend_limit": 6,
  "invitations_allowed": true,
  "emergency_access_allowed": true,
  "password_iterations": 100000,
  "password_hints_allowed": true,
  "show_password_hint": false,
  "admin_token": "Goncalo@1589@16@duarte",
  "invitation_org_name": "Vaultwarden",
  "ip_header": "X-Real-IP",
  "icon_redirect_code": 302,
  "icon_cache_ttl": 2592000,
  "icon_cache_negttl": 259200,
  "icon_download_timeout": 10,
  "icon_blacklist_non_global_ips": true,
  "disable_2fa_remember": false,
  "authenticator_disable_time_drift": false,
  "require_device_email": false,
  "reload_templates": false,
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "disable_admin_token": false,
  "_enable_yubico": true,
  "_enable_duo": false,
  "_enable_smtp": true,
  "_enable_email_2fa": true,
  "email_token_size": 6,
  "email_expiration_time": 600,
  "email_attempts_limit": 3

```
<img width="1680" alt="Screen Shot 2022-07-29 at 21 17 17" src="https://user-images.githubusercontent.com/68701049/181837290-cb755144-a6da-464d-9c02-df82b41fc756.png">

<img width="1419" alt="Screen Shot 2022-07-29 at 21 19 34" src="https://user-images.githubusercontent.com/68701049/181837449-cb6df54d-79f3-4742-9abc-fa56387326f2.png">
