### ISSUE TITLE
Browser Extension & Desktop App keeps crashing when trying to login

### ISSUE THREAD

**Issue by xbdmHQ** [dani-garcia/vaultwarden#3728]
### Subject of the issue
Browser Extension & Desktop App keeps crashing when trying to login 

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.29.1
* Web-vault version: v2023.5.0
* OS/Arch: linux/x86_64
* Running within Docker: true (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: false
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: PostgreSQL
* Database version: PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** 

```json
{
  "_duo_akey": null,
  "_enable_duo": true,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "https://vault.whateveritworks.org/vw_static/",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 1,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": true,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "**********://*****************************************************************************************",
  "db_connection_retries": 10,
  "disable_2fa_remember": false,
  "disable_admin_token": true,
  "disable_icon_download": false,
  "domain": "*****://*************************",
  "domain_origin": "*****://*************************",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 300,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": 7,
  "extended_logging": false,
  "helo_name": null,
  "hibp_api_key": "***",
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "whatever",
  "invitations_allowed": false,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": 50,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": false,
  "password_iterations": 600000,
  "push_enabled": true,
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": true,
  "signups_domains_whitelist": "*************,**********,*******,*************,**********,*********,***********,************,***********,**********,***************,**********,**********",
  "signups_verify": true,
  "signups_verify_resend_limit": 3,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": false,
  "smtp_explicit_tls": null,
  "smtp_from": "***************",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": "*********",
  "smtp_password": "***",
  "smtp_port": 465,
  "smtp_security": "force_tls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": "***************",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": 7,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": 10,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": false,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

* vaultwarden version: 1.29.1

* Install method: Docker Image

* Clients used: web vault, extension and mobile

* Reverse proxy and version: Nginx + 1.29.1

* MySQL/MariaDB or PostgreSQL version: PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

* Other relevant details:

### Steps to reproduce
```
version: "3.7"

services:
  vaultwarden:
    container_name: vaultwarden
    hostname: vaultwarden
    image: vaultwarden/server:latest
    restart: always
    user: 65534:65534
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    environment:
      - DATABASE_URL=postgresql://{REDACTED}:{REDACTED}@{REDACTED}:5432/{REDACTED}
      - INVITATIONS_ALLOWED=false
      - SIGNUPS_ALLOWED=true
      - SIGNUPS_DOMAINS_WHITELIST=autistici.org,msgsafe.io,cock.li,mailfence.com,posteo.net,posteo.de,courvix.com,kolabnow.com,soverin.net,thexyz.com,countermail.com,runbox.com,hrzn.email
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_LIMIT=3
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - EMAIL_EXPIRATION_TIME=300
      - EMAIL_ATTEMPTS_LIMIT=3
      - ICON_DOWNLOAD_TIMEOUT=10
      - DB_CONNECTION_RETRIES=10
      #- EVENT_CLEANUP_SCHEDULE="0 10 0 * * *"
      #- EMERGENCY_REQUEST_TIMEOUT_SCHEDULE="0 7 * * * *"
      #- EMERGENCY_NOTIFICATION_REMINDER_SCHEDULE="0 3 * * * *"
      #- INCOMPLETE_2FA_SCHEDULE="30 * * * * *"
      #- TRASH_PURGE_SCHEDULE="0 5 0 * * *"
      #- SEND_PURGE_SCHEDULE="0 5 * * * *"
      #- JOB_POLL_INTERVAL_MS=30000
      #- DISABLE_ICON_DOWNLOAD=false
      #- ICON_BLACKLIST_NON_GLOBAL_IPS=true
      #- ICON_BLACKLIST_REGEX='^(192\.168\.0\.[0-9]+|192\.168\.1\.[0-9]+)$'
      #- DISABLE_2FA_REMEMBER=true
      - ADMIN_TOKEN=
      - DISABLE_ADMIN_TOKEN=true
      - WEBSOCKET_ENABLED=false
      - PUSH_ENABLED=true
      - PUSH_INSTALLATION_ID={REDACTED}
      - PUSH_INSTALLATION_KEY={REDACTED}
      - DOMAIN={REDACTED}
      #- YUBICO_CLIENT_ID=
      #- YUBICO_SECRET_KEY=
      - ROCKET_LIMITS={json=10485760}
      - ROCKET_WORKERS=4
      - SMTP_HOST={REDACTED}
      - SMTP_FROM={REDACTED}
      - SMTP_PORT={REDACTED}
      - SMTP_SECURITY={REDACTED}
      - SMTP_USERNAME={REDACTED}
      - SMTP_PASSWORD={REDACTED}
      - SMTP_EMBED_IMAGES=false
      - SHOW_PASSWORD_HINT=false
      - PASSWORD_ITERATIONS=600000
      - INCOMPLETE_2FA_TIME_LIMIT=3
      - TRASH_AUTO_DELETE_DAYS=7
      - USER_ATTACHMENT_LIMIT=10
      - ORG_ATTACHMENT_LIMIT=50
      - INVITATION_EXPIRATION_HOURS=120
      - INVITATION_ORG_NAME=whatever
      - PASSWORD_HINTS_ALLOWED=false
      - AUTHENTICATOR_DISABLE_TIME_DRIFT=true
      - ADMIN_SESSION_LIFETIME=1
      - ADMIN_RATELIMIT_SECONDS=300
      - ADMIN_RATELIMIT_MAX_BURST=3
      - LOGIN_RATELIMIT_SECONDS=60
      - LOGIN_RATELIMIT_MAX_BURST=10      
      #- DUO_IKEY=
      #- DUO_SKEY=
      #- DUO_HOST=
      #- WEB_VAULT_ENABLED=false
      - USE_SYSLOG=true
      - EXTENDED_LOGGING=true
      - IP_HEADER=X-Real-IP
      - EMERGENCY_ACCESS_ALLOWED=true
      - SENDS_ALLOWED=true
      - EVENTS_DAYS_RETAIN=7
      - HIBP_API_KEY={REDACTED}
    ports:
      - '127.0.0.1:8082:80'
    depends_on:
      - vaultdb
    volumes:
      - ./vaultdata:/data
      #- ./images/logo-dark@2x.png:/web-vault/images/logo-dark@2x.png
      #- ./images/logo-white@2x.png:/web-vault/images/logo-white@2x.png
      #- ./images/vault-icon-white.png:/web-vault/images/icon-white.png
      #- ./images/favicon-16x16.png:/web-vault/images/favicon-16x16.png
      #- ./images/favicon-32x32.png:/web-vault/images/favicon-32x32.png

  vaultdb:
    container_name: vaultdb
    hostname: vaultdb
    image: postgres:15
    restart: always
    ports:
      - '127.0.0.1:5433:5432'
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./vaultdb:/var/lib/postgresql/data
      - ./vaultbackup:/backup
    environment:
      - POSTGRES_DB={REDACTED}
      - POSTGRES_USER={REDACTED}
      - POSTGRES_PASSWORD={REDACTED}

volumes:
  vaultdb:
  vaultbackup:

```

### Expected behaviour
Login to my extension and desktop app without it crashing

### Actual behaviour
crashed when logging into desktop app or extensions

### Troubleshooting data
```
GET /admin
(admin_page) GET /admin/ => 200 OK
GET /admin/diagnostics
(diagnostics) GET /admin/diagnostics => 200 OK
GET /admin/diagnostics/config
(get_diagnostics_config) GET /admin/diagnostics/config => 200 OK
GET /notifications/hub?access_token={REDACTED}
Accepting Rocket WS connection from {REDACTED}
(websockets_hub) GET /notifications/hub?<data..> => 200 OK
GET /api/accounts/revision-date
(revision_date) GET /api/accounts/revision-date => 200 OK
GET /api/devices/knowndevice
(get_known_device) GET /api/devices/knowndevice => 200 OK
POST /identity/accounts/prelogin
(prelogin) POST /identity/accounts/prelogin => 200 OK
POST /identity/connect/token
2FA token not provided
(login) POST /identity/connect/token => 400 Bad Request
POST /identity/connect/token
User xbdm@msgsafe.io logged in successfully. IP: {REDACTED}
(login) POST /identity/connect/token => 200 OK
POST /identity/connect/token
(login) POST /identity/connect/token => 200 OK
GET /notifications/hub?access_token={REDACTED}
Accepting Rocket WS connection from {REDACTED}
(websockets_hub) GET /notifications/hub?<data..> => 200 OK
Closing WS connection from {REDACTED}
```

**Comment by xbdmHQ** [comment]
Never, mind i fixed the issue now. It was some bullshit i added into docker.

```
    user: 65534:65534
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
```

to
```
    security_opt:
      - no-new-privileges:true
 ```
