### ISSUE TITLE
[v1.29.2] thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)'

### ISSUE THREAD

**Issue by floatingpurr** [dani-garcia/vaultwarden#3867]
### Subject of the issue

I'm experiencing this error in version 1.29.2. All worked fine up to version 1.29.1.

### Deployment environment

* vaultwarden version: 1.29.2

* Install method: docker-compose

* Clients used: n/a

* Reverse proxy and version: n/a 

* MySQL/MariaDB or PostgreSQL version: n/a

* Other relevant details: temporary fix: downgrade to 1.29.1. My OS:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch
```

### Steps to reproduce

Just launch a container with `docker-compose up` starting from the image `vaultwarden/server:1.29.2`. Here is mine:
```yml
version: '3.7'

services:
  bitwarden:
    image: vaultwarden/server:1.29.2
    container_name: vaultwarden
    restart: always
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - ./bw-data:/data
    env_file:
      .bw.env

    labels:
      traefik.enable: true

      # bitwarden-ui
      traefik.http.routers.bitwarden-ui.rule: Host(`foo.org`)
      traefik.http.routers.bitwarden-ui.entrypoints: websecure
      traefik.http.routers.bitwarden-ui.tls.certresolver: tlsleresolver
      traefik.http.routers.bitwarden-ui.service: bitwarden-ui
      traefik.http.services.bitwarden-ui.loadbalancer.server.port: 80


networks:
  proxy:
    external: true
```

### Expected behaviour
Vaultwarden gets up and running

### Actual behaviour
An error is raised and the container exits

```
Status: Downloaded newer image for vaultwarden/server:1.29.2
Creating vaultwarden ... done
Attaching to vaultwarden
vaultwarden  | thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/worker.rs:447:13
vaultwarden  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Troubleshooting data
Here's the output with `RUST_BACKTRACE=full`

```
vaultwarden  | thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/worker.rs:447:13
vaultwarden  | stack backtrace:
vaultwarden  |    0:     0x55d349a16ca3 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd7d55b7108d2ab8
vaultwarden  |    1:     0x55d34946f3df - core::fmt::write::h6d54cd7c9e155ec5
vaultwarden  |    2:     0x55d349a138d7 - std::io::Write::write_fmt::h6a453a71c692f63b
vaultwarden  |    3:     0x55d349a16a75 - std::sys_common::backtrace::print::h4ddf81241a51b337
vaultwarden  |    4:     0x55d349a184b0 - std::panicking::default_hook::{{closure}}::hff91f1f484ade5cd
vaultwarden  |    5:     0x55d349a18274 - std::panicking::default_hook::h21f14afd59f7aef9
vaultwarden  |    6:     0x55d349a18999 - std::panicking::rust_panic_with_hook::h45f66047b14c555c
vaultwarden  |    7:     0x55d349a188a4 - std::panicking::begin_panic_handler::{{closure}}::h49d1a88ef0908eb4
vaultwarden  |    8:     0x55d349a17096 - std::sys_common::backtrace::__rust_end_short_backtrace::hccebf9e57f8cc425
vaultwarden  |    9:     0x55d349a18642 - rust_begin_unwind
vaultwarden  |   10:     0x55d3493c2883 - core::panicking::panic_fmt::h54ec9d0e3180a83d
vaultwarden  |   11:     0x55d349a519f4 - tokio::runtime::blocking::pool::Spawner::spawn_blocking::h9e0ded7b77863876
vaultwarden  |   12:     0x55d349a50d05 - tokio::runtime::blocking::pool::spawn_blocking::hb15e5178f17f818b
vaultwarden  |   13:     0x55d349a6566b - tokio::runtime::scheduler::multi_thread::worker::Launch::launch::h6ce2d7d02be3860d
vaultwarden  |   14:     0x55d349a783f9 - tokio::runtime::builder::Builder::build::h6fb748647923ea1f
vaultwarden  |   15:     0x55d349e6f52e - vaultwarden::main::h222f937f9ca88bfc
vaultwarden  |   16:     0x55d34a2661d7 - std::sys_common::backtrace::__rust_begin_short_backtrace::h267d3b5af2cab27a
vaultwarden  |   17:     0x55d349dc0c38 - std::rt::lang_start::{{closure}}::h3ae0294076e6f9bb
vaultwarden  |   18:     0x55d349a0bf15 - std::rt::lang_start_internal::hf502095b101390bb
vaultwarden  |   19:     0x55d349e6f895 - main
vaultwarden  |   20:     0x7f20c3e1d1ca - <unknown>
vaultwarden  |   21:     0x7f20c3e1d285 - __libc_start_main
vaultwarden  |   22:     0x55d3494062b1 - _start
vaultwarden  |   23:                0x0 - <unknown>
vaultwarden exited with code 101
```
