### ISSUE TITLE
Panic updating from 1.29.0 to latest docker image

### ISSUE THREAD

**Issue by zionio** [dani-garcia/vaultwarden#4098]
### Subject of the issue

Error (panic) updating from `vaultwarden/server:1.29.0`  to ` vaultwarden/server:latest`

### Deployment environment

* vaultwarden version: 1.29.0

* Install method: Docker image

* Clients used: web vault

* MySQL/MariaDB or PostgreSQL version: MySQL Community Edition 5.7.43

Hint: MySQL User Permissions: `GRANT ALL PRIVILEGES ON vaultwarden.*` schema 

### Steps to reproduce

1) Start with the following `compose.yml` file (image 1.29.0)

```
version: '3'
services:
  vaultwarden:
    image: vaultwarden/server:1.29.0
    container_name: vaultwarden
    restart: always
    volumes:
      - ./vw-data:/data
    ports:
      - "9090:80"
    depends_on: ["database"]
    environment:
      ADMIN_TOKEN: [REDACTED]
      DATABASE_URL: "mysql://[REDACTED]:[REDACTED]@vwdb/vaultwarden"
      DOMAIN: "http://[REDACTED]:9090"

  database:
    image: mysql:5.7.43
    container_name: vw-db
    hostname: vwdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: [REDACTED]
    volumes:
      - "./mysql-data:/var/lib/mysql"
```

2) Update image to `vaultwarden/server:latest`
3) `docker compose up -d`  (to restart with new image)

### Expected behaviour

Updated version up&running

### Actual behaviour

Error 😭 

```
[2023-11-23 11:16:33.075][panic][ERROR] thread 'main' panicked at 'Error running migrations: QueryError(DieselMigrationName { name: "2023-06-17-200424_create_auth_requests_table", version: MigrationVersion("20230617200424") }, DatabaseError(Unknown, "Cannot add foreign key constraint"))': src/db/mod.rs:473
0: vaultwarden::init_logging::{{closure}}
1: std::panicking::rust_panic_with_hook
2: std::panicking::begin_panic_handler::{{closure}}
3: std::sys_common::backtrace::__rust_end_short_backtrace
4: rust_begin_unwind
5: core::panicking::panic_fmt
6: core::result::unwrap_failed
7: vaultwarden::db::mysql_migrations::run_migrations
8: vaultwarden::db::DbPool::from_config
9: vaultwarden::main::{{closure}}
10: vaultwarden::main
11: std::sys_common::backtrace::__rust_begin_short_backtrace
12: std::rt::lang_start::{{closure}}
13: std::rt::lang_start_internal
14: main
15: <unknown>
16: __libc_start_main
17: _start
```

### Troubleshooting data

Rollback (to 1.29.0 tag) seems to works.

### Some notes

Update from:
- 1.29.0 to 1.29.1 works
- 1.29.0 to 1.29.2 fail with same error
- 1.29.1 to 1.29.2 fail with same error
