### ISSUE TITLE
iOS client (include iPhone, iPad) could not display the icon

### ISSUE THREAD

**Issue by Autonomous120** [dani-garcia/vaultwarden#4330]
#### iOS client (include iPhone, iPad) could not display the icons, this issue occoured at those devices:
iPhone 15, iOS 17.3, APP version: 2024.2.0 (6100)
iPhone Xs Max, iOS 16.6, APP version: 2024.2.0 (6100)
iPhone 7, iOS 15.5, APP version: 2024.2.0 (6100)
iPad Pro Gen 4, iOS 17.3, APP version: 2024.2.0 (6100)
![10 10 53 jpeg](https://github.com/dani-garcia/vaultwarden/assets/9163201/f8e8e019-7e64-48f0-b28f-f4fc04e44524)
Unfortunately, I checked logs didn't find any exception.

### Clients which can display icons normally
Windows 11 Pro (10.0.22631.3085), APP version: 2024.2.0
macOS Sonoma 14.1.2, APP version: 2024.2.0
macOS Monterey 12.7.3, APP version: 2024.2.0
Android 10, APP version: 2024.2.0 (9000)

## Server Status
```
Versions
Server Installed
1.30.3
Web Installed
2024.1.2
Database
SQLite: 3.44.0
Checks
OS/Arch
linux / x86_64
Running within Docker
Yes (Base: Debian)
Environment settings overridden
No
Uses a reverse proxy
Yes
IP header Match
Config/Server: X-Real-IP
Internet access Ok
Yes
Internet access via a proxy
No
DNS (github.com) Ok
192.30.255.112
Date & Time (Local)
Server: 2024-02-09 10:14:16 +08:00
Date & Time (UTC) Server/Browser Ok
NTP: Unable to fetch NTP time.
Server: 2024-02-09 02:14:16 UTC
Browser: 2024-02-09 02:14:28 UTC
Domain configuration Match HTTPS
Server: https://<mydomain>:8001/admin/diagnostics
Browser: https://<mydomain>:8001/admin/diagnostics
```

## Docker-compose
```
#---
#Docker-compose file for Vaultwarden
#--- 
version: '3'
services:
  vaultwarden:
    container_name: vaultwarden
    restart: unless-stopped
    image: vaultwarden/server:latest
    environment: 
    - TZ=Asia/Hong_Kong
    - LOG_FILE=/maintenance/vaultwarden.log
    - ORG_EVENTS_ENABLED=true
    - EVENTS_DAYS_RETAIN=365
    - PUSH_ENABLED=true
    - PUSH_INSTALLATION_ID=<my installation id>
    - PUSH_INSTALLATION_KEY=<my installation key>

    volumes:
    - /volume1/docker/Vaultwarden/data:/data
    - /volume1/docker/Vaultwarden/maintenance:/maintenance
    
    ports:
    - 8000:80
    
    network_mode: "bridge"
```

## Server Certificate Chain
AAA Certificate Services → TrustAsia ECC DV TLS CA G2 → <Certificate of my domain, X9.62 ECDSA  SHA-256>
