### ISSUE TITLE
Vaultwarden won't start anymore and I have no idea why

### ISSUE THREAD

**Issue by hvanmegen** [dani-garcia/vaultwarden#4392]
### Subject of the issue
vaultwarden crashes after startup

### Deployment environment
docker compose file:
```
version: '3.3'
services:
    server:
        container_name: vaultwarden
        environment:
          - LOG_LEVEL='warning'
          - WEBSOCKET_ENABLED='false'
          - ADMIN_TOKEN=notmyrealadminpassword
          - RUST_BACKTRACE=full
        sysctls:
            - "net.ipv6.conf.all.disable_ipv6=1"
        volumes:
            - './data:/data'
        ports:
            - '127.0.0.1:8888:80'
            - '3012:3012'
        image: 'vaultwarden/server:latest'
        restart: unless-stopped
```

* vaultwarden version: 1.30.3

* Install method: docker-compose

* Clients used: n/a (it wont even start)

* Reverse proxy and version: nginx

* MySQL/MariaDB or PostgreSQL version: mysql 8.0.36-0ubuntu0.22.04.1

* Other relevant details:

### Steps to reproduce
docker-compose up -d

### Expected behaviour
I get this error in my logs:
```
vaultwarden | /--------------------------------------------------------------------\
vaultwarden | |                        Starting Vaultwarden                        |
vaultwarden | |                           Version 1.30.3                           |
vaultwarden | |--------------------------------------------------------------------|
vaultwarden | | This is an *unofficial* Bitwarden implementation, DO NOT use the   |
vaultwarden | | official channels to report bugs/features, regardless of client.   |
vaultwarden | | Send usage/configuration questions or feature requests to:         |
vaultwarden | |   https://github.com/dani-garcia/vaultwarden/discussions or        |
vaultwarden | |   https://vaultwarden.discourse.group/                             |
vaultwarden | | Report suspected bugs/issues in the software itself at:            |
vaultwarden | |   https://github.com/dani-garcia/vaultwarden/issues/new            |
vaultwarden | \--------------------------------------------------------------------/
vaultwarden |
vaultwarden | [INFO] Using saved config from `data/config.json` for configuration.
vaultwarden |
vaultwarden | [WARNING] The following environment variables are being overridden by the config.json file.
vaultwarden | [WARNING] Please use the admin panel to make changes to them:
vaultwarden | [WARNING] ADMIN_TOKEN
vaultwarden |
vaultwarden | [NOTICE] You are using a plain text `ADMIN_TOKEN` which is insecure.
vaultwarden | Please generate a secure Argon2 PHC string by using `vaultwarden hash` or `argon2`.
vaultwarden | See: https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page#secure-the-admin_token
vaultwarden |
vaultwarden | thread 'main' panicked at src/main.rs:99:51:
vaultwarden | Valid log level: ParseLevelError(())
vaultwarden | stack backtrace:
vaultwarden |    0:     0x55c77836c5dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
vaultwarden |    1:     0x55c777ee5ed0 - core::fmt::write::h3a39390d8560d9c9
vaultwarden |    2:     0x55c7783340c2 - std::io::Write::write_fmt::h5fc9997dfe05f882
vaultwarden |    3:     0x55c77836e11e - std::sys_common::backtrace::print::h23a2d212c6fff936
vaultwarden |    4:     0x55c77836d890 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
vaultwarden |    5:     0x55c77836ea5b - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
vaultwarden |    6:     0x55c77836e47c - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
vaultwarden |    7:     0x55c77836e3d6 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
vaultwarden |    8:     0x55c77836e3c1 - rust_begin_unwind
vaultwarden |    9:     0x55c777191484 - core::panicking::panic_fmt::hbf0e066aabfa482c
vaultwarden |   10:     0x55c7771919f2 - core::result::unwrap_failed::hddb4fea594200c52
vaultwarden |   11:     0x55c777e8945f - vaultwarden::main::{{closure}}::h84356ec7a5056fbd
vaultwarden |   12:     0x55c777e8235e - vaultwarden::main::hdfa2f122a20a85e7
vaultwarden |   13:     0x55c777325fe3 - std::sys_common::backtrace::__rust_begin_short_backtrace::haac2544bc702188f
vaultwarden |   14:     0x55c77732709e - std::rt::lang_start::{{closure}}::h96abe5f6d011bbfa
```

### Actual behaviour
I think my vaultwarden was updated to 1.30.3 and stopped working.. I don't dare roll back to older version in case I break something.

### Troubleshooting data
I have tried setting a password using argon2, but this didn't solve the issue...

```
echo -n "thatpasswordthatwasntmine" | argon2 "$(openssl rand -base64 32)" -e -id -k 19456 -t 2 -p 1 | sed 's#\$#\$\$#g'
```
