### ISSUE TITLE
Error sending incomplete 2FA email ???

### ISSUE THREAD

**Issue by 1mfaasj** [dani-garcia/vaultwarden#4777]
this error is logged every second.
I don't know why because I haven't configured any SMTP client or something.

```
[2024-07-25 13:12:56.325][vaultwarden::mail][ERROR] SMTP 5xx error: permanent error (534): 5.7.9 Application-specific password required. For more information, go to5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor 4fb4d7f45d1cf-5ac64eb3980sm688033a12.60 - gsmtp
[2024-07-25 13:12:56.327][panic][ERROR] thread 'tokio-runtime-worker' panicked at 'Error sending incomplete 2FA email: SMTP 5xx error: permanent error (534): 5.7.9 Application-specific password required. For more information, go to5.7.9  https://support.google.com/mail/?p=InvalidSecondFactor 4fb4d7f45d1cf-5ac64eb3980sm688033a12.60 - gsmtp': src/api/core/two_factor/mod.rs:273
   0: vaultwarden::init_logging::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: vaultwarden::api::core::two_factor::send_incomplete_2fa_notifications::{{closure}}
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::scheduler::multi_thread::worker::run
  11: tokio::runtime::task::raw::poll
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: core::ops::function::FnOnce::call_once{{vtable.shim}}
  14: std::sys::pal::unix::thread::Thread::new::thread_start
  15: <unknown>
  16: clone
```

my docker compose:
```
version: "3.4"
services:
  vaultwarden:
    image: vaultwarden/server:1.31.0
    environment:
      - ADMIN_TOKEN=XXX
      - LOG_FILE=/data/bitwarden.log
      - LOG_LEVEL=error
      - TZ=Europe/Amsterdam
#      - SIGNUPS_ALLOWED=false
#      - WEBSOCKET_ENABLED=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/docker/swarm/appdata/vaultwarden:/data
```
