### ISSUE TITLE
New docker deploy on debian 12 hangs at start

### ISSUE THREAD

**Issue by maxdd** [dani-garcia/vaultwarden#5548]
### Vaultwarden Support String

Hello,
i'm not the owner of the post on the forum [here](https://vaultwarden.discourse.group/t/vaultwarden-web-site-keeps-loading/4366) but i'm facing the exact same issue.
I had to roll back on 1.32.7 on my new debian 12 unit (booted yesterday first time)
I also have a debian 12 which is much older and started on vw 2023 and using watchtower it has updated by itself till sha256:24aa90c2424f2f6b10862ba84dc9141d09c1df2b7025f111c9b2bbc4c078894b which is the server:latest image.

### Vaultwarden Build Version

1.33.1

### Deployment method

Official Container Image

### Custom deployment method

```
version: '3.5'
services:
  app:
    image: 'vaultwarden/server:latest'
    restart: unless-stopped
    ports:
      - '8062:80'
    volumes:
      - ./vw-data:/data:rw
    environment:
      - SIGNUPS_ALLOWED="false"
      #- LOG_FILE=/data/vaultwarden.log
      #- WEBSOCKET_ENABLED=true
```

### Reverse Proxy

none

### Host/Server Operating System

Linux

### Operating System Version

debian 12

### Clients

Browser Extension, Web Vault

### Steps To Reproduce

1. docker-compose up -d
2. browse ip:8062

### Expected Result

Web vault should load

### Actual Result

![Image](https://github.com/user-attachments/assets/c2509a69-e7eb-4630-9d56-741f2864c504)

### Logs

```text

```
